### PR TITLE
Better Squids Part 1

### PR DESCRIPTION
**Pull request by AsciiSquid**
### Step one in an overhaul of the least played race.

1. Squids get a cool new lore name "Yuggolith", cause muh lore.
2. Squids movespeed has been made *slightly* slower at the benefit of free movement without gravity (as long as there is ground beneath them)
3. Squids gain a new ability **Ink spill**, allowing them to spray a puddle of slippery ink on the tile beneath them as a quick getaway. Has a 60 second cooldown and costs a decent amount of nutrients (about the same as spider webs)
4. Squids now have unique footsteps and scream sounds.
5. Grabs from squids are now significantly more difficult to break out of than regular grabs.

This overhaul is not yet complete (hence the "part 1"), however feedback and corrections to what is present would be nice.

## Why It's Good For The Game
Squids are underused cause they aren't very interesting. I would like to change that.

## Changelog
:cl:
add: Squids can now spit ink
del: Removed old squid code that wasn't modularized from the old waspcode move
balance: Squids grabs are now much tougher to break
balance: Squids move slower with gravity than without.
soundadd: Added squid footsteps
soundadd: Added squid screaming
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
These are interesting features, but I would be slightly concerned balance wise.

I'd like to know how much slower they move. Gravity based powers are a bit too niche IMO, hence why moths are useless to a powergamer, as the gravity gen rarely goes out and magboots are just ungodly strong.

You also gave them what is basically a free knockdown ability (Nutrition is frankly not strong balancer, given food is plentiful).

Finally, grabs pretty much end fights, and are incredibly easy to abuse if you do the spam shove + grab technique, and even a regular grab allows the person to land multiple free hits on you with their weapon.

**Comment by AsciiSquid** [comment]
Movement mod is 0.55 (Dorf race has 0.5 as reference) making them the slowest race at default speeds. While gravity is off this mod is set to 0 giving them basically default speed so long as there is a tile under them.

The power at close range is to offset the fact that unless they are in the niche situation of no-grav. The increased damage they take (especially in burn) coupled with their slow movement leaves them vulnerable at any range outside melee.

Also glass shards still poke their exposed feet-tentacles.

**Comment by Sparrowbird611** [comment]
fair enough.  They do have some decent downsides. Nothing here is too extreme, so it should be fine.

**Comment by dee-dubya** [comment]
my calamari has gone stale monsieur

**Comment by AsciiSquid** [comment]
*stale squid noises

**Pull request merged**
