### PR TITLE
The Great Modularization/Fix PR

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Re-modularizing and fixing quite a few things.

## Why It's Good For The Game
We can Mirror /tg/ a lot better, as well as our code is much neater.

## Changelog
:cl:
code: We are now modularized. Be sure to use the `/waspstation/` folder for code changes when you can, and put `//WaspStation edit - <reason>` where you can't.
fix: Lavaland works now
fix: You are no longer cold while wearing space suits
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
margg........ modularization fix wehn..................................

**Comment by triplezeta** [comment]
markg...........................................................................maaaarkg........................................................

**Comment by dinnerwoerror** [comment]
hehe pull request 69 fune sex number

**Comment by triplezeta** [comment]
it's funny because once this PR gets merged Boomerantiswasp will be SEX

**Comment by dinnerwoerror** [comment]
there's 3 players online this round and when i clicked "observe" and immediately saw that it was delta station, i unironically inhaled sharply

**Comment by MarkSuckerberg** [comment]
help how do I connect 2 serb

**Comment by triplezeta** [comment]
IP is byond://47.204.253.81:5513
:salute:

**Comment by MarkSuckerberg** [comment]
ok many thank

**Comment by dinnerwoerror** [comment]
a haiku

ezafa an marg
soaked pants
ezafa an mark

**Comment by dinnerwoerror** [comment]
there's gonna be inquisitive players looking at these old pull requests 2 years down the line and they're gonna wonder what the fuck i smoke

**Comment by triplezeta** [comment]
h

**Comment by MarkSuckerberg** [comment]
what do you smoke though, asking for the kids in the future

**Comment by dinnerwoerror** [comment]
i actually havent consumed any drugs at all for the past five years

**Comment by triplezeta** [comment]
moth feet

**Comment by FancyCyclops** [comment]
Sex!

**Comment by dinnerwoerror** [comment]
every shitpost we make adds to the gitlog channel

**Comment by dinnerwoerror** [comment]
autumn when they eventually get to marks house after traveling all the way across canada to get to illinois

(っ˘з(˘⌣˘ )

**Comment by triplezeta** [comment]
margggggg........... modularzietation................

**Comment by tiramisuapimancer** [comment]
okay class, open your pull requests to page sixty nine

**Comment by triplezeta** [comment]
funny sex number........ funeee....................
heavysmall

**Comment by tiramisuapimancer** [comment]
image
ooouuuugh sixty niiiiine ohoho

**Comment by FancyCyclops** [comment]
sex number! sex! sex! sex! sex! sex! sex! sex! sex! sex!

sex number! sex! sex! sex! sex! sex! sex! sex! sex! sex!

sex number! sex! sex! sex! sex! sex! sex! sex! sex! sex!

**Comment by triplezeta** [comment]
WE MUST GIVE MARGG OUR POWER
SO THAT HE FINALLY FINISHES THIS PR
AND SO BOOMERANTIS CAN FINALLY BECOME SEX

**Comment by FancyCyclops** [comment]
sex~! fuwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~!

**Comment by triplezeta** [comment]
modulrization when

futureshitpost

**Comment by dinnerwoerror** [comment]
you can stop spamming

one mustn't rush a masterpiece

**Comment by triplezeta** [comment]
we need to get to 69 comments

**Comment by triplezeta** [comment]
it is only fitting for the 69 pr

**Comment by Baldir-Odensen** [comment]
Marg you are awesome keep it up!

**Comment by triplezeta** [comment]
marg you are good and cool and good and keep it up

**Comment by triplezeta** [comment]
t-th... the modaueraziation........ marg............................

**Comment by MarkSuckerberg** [comment]
???

**Comment by MarkSuckerberg** [comment]
ok what

**Comment by MarkSuckerberg** [comment]
Trying again in a new PR, maybe

**Comment by triplezeta** [comment]
mark no 
pr 69.................

**Comment by MarkSuckerberg** [comment]
it's the same on other branches too, guess we're stuck with 69

**Comment by triplezeta** [comment]
69!! 69 yes

**Comment by MarkSuckerberg** [comment]
Bruh.

**Comment by triplezeta** [comment]
m-mark.........

**Comment by triplezeta** [comment]
MAARG......

**Comment by triplezeta** [comment]
trabis... trabis blease.......

**Comment by triplezeta** [comment]
TRABIS!! TRABIS NO!!

**Comment by MarkSuckerberg** [comment]
whoops hehe

**Comment by triplezeta** [comment]
MARGG! WHY DRABIS NO WORK!!

**Comment by SynnGraffkin** [comment]
fug tabis in the bussy

**Comment by triplezeta** [comment]
no

**Comment by triplezeta** [comment]
MARGG!!! DE DRABIS!! DRABIS NO WORK!!

**Comment by triplezeta** [comment]
maaaaaaaark..............

**Comment by triplezeta** [comment]
m..margr...........

**Comment by triplezeta** [comment]
margrgr

**Comment by triplezeta** [comment]
mgrggrargrgrg plesaes

**Comment by triplezeta** [comment]
YES

**Comment by triplezeta** [comment]
image
SEX

**Comment by triplezeta** [comment]
WE DID IT!! SEX NUMBER!!

**Comment by MarkSuckerberg** [comment]
image
we're so close

**Comment by triplezeta** [comment]
SEX NUMBER
SEX NUMBER
SEX NUMBER
SEX NUMBER

**Comment by MarkSuckerberg** [comment]
fifty seven is a decent number, but not a great number

**Comment by triplezeta** [comment]
do you know what is a great number though

**Comment by SynnGraffkin** [comment]
42

**Comment by MarkSuckerberg** [comment]
3 is a good number ngl

**Comment by triplezeta** [comment]
sex

**Comment by triplezeta** [comment]
7

**Comment by triplezeta** [comment]
6

**Comment by triplezeta** [comment]
5

**Comment by MarkSuckerberg** [comment]
62 is good and all but like, not THAT great

**Comment by triplezeta** [comment]
4

**Comment by dinnerwoerror** [comment]
when will you moths eat my food

**Comment by triplezeta** [comment]
1

**Comment by triplezeta** [comment]
69!!! WE DID IT!!!!

**Comment by dinnerwoerror** [comment]
everyone refers to mark's characters as "mark" in character and only mark cares about it when they do

**Pull request merged**
