### PR TITLE
Ports the Cat Surgeon turning people into cats from bee

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
Ports https://github.com/BeeStation/BeeStation-Hornet/pull/1447 and https://github.com/BeeStation/BeeStation-Hornet/pull/1622, now the cat surgeon commits warcrimes.

## Why It's Good For The Game
Its not
## Changelog
:cl:
add: The cat surgeon now has a syringe gun
add: The cat surgeon now turns you into a cat when you fall unconcious/crit and pacifies you
/:cl:

### CODE REVIEW

**Comment by FancyCyclops** [comment]
n-nya

**Comment by TheNeoGamer42** [comment]
do we even have the nya brain damage, if so, whats the filepath so I can try to make him add it too

**Comment by dinnerwoerror** [comment]
Now see, this is where you're wrong.

My character is actually a ex-nanotrasen military official that has cracked down on multiple different syndicate leaders. His body is riddled with scars from all of the missions he's done during his line of duty. He was the bravest and most confident soldier in his squad, earning the most medals in all known nanotrasen history; which he still wears to this present day. His fighting skills outmatch any terrorist, let it be a space ninja, traitor, nuclear operative, he'll kill them with his bare fist. He's better then the entire security force on station when it comes to dealing with threats, which is why he does the so called "valid hunt" you talk of. He doesn't even need a weapon to kill you, he'll slip you on a bar of soap and punch your face in! Maybe, if you got a bit better.. You wouldn't have this problem of my character "valid hunting", but no one is better then him. So maybe think again, kid. B)

**Comment by TheNeoGamer42** [comment]
I realized I fucked up when doing the cherry picking so im gonna redo it

**Comment by TheNeoGamer42** [comment]
wait what it autoclosed it goddamnet

**Pull request merged**
