### PR TITLE
hopefully this makes dynamic playable

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

we've missed out on like half a dozen bug fixes related to dynamic giving people antag sec

i'm very certain i missed something though

https://github.com/tgstation/tgstation/pull/51502
https://github.com/tgstation/tgstation/pull/54452
https://github.com/tgstation/tgstation/pull/54477

## Why It's Good For The Game

if i'm very lucky we might make dynamic the default gamemode

## Changelog
:cl:
fix: caught up the past couple months worth of bug fixes for dynamic
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
hi yes please link the PRs ported in the PR description

**Comment by dinnerwoerror** [comment]
ok

**Comment by dinnerwoerror** [comment]
did it

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by dinnerwoerror** [comment]
hopefully these hot fixes add another layer of protected antag prevention

**Comment by dinnerwoerror** [comment]
the time has come

**Pull request merged**
