### PR TITLE
Papertown and other fixes

### PR DESCRIPTION
**Pull request by Vorak2**
## About The Pull Request

fixes a few problems with midway  and adds courtroom and solgov ofices
## Why It's Good For The Game

becouse having walls in doors is bad and new jobs need ofices

## Changelog
:cl:
add: papertown added to midway
fix: fixes some of the problems on midway
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
PR 666 people.

**Comment by Vorak2** [comment]
> PR 666 people.

God damit should have delayed longer

**Comment by SynnGraffkin** [comment]
I'd rather issues related to Midway be fixed that meme the pr number.

**Review by triplezeta — COMMENTED** [review]
needs table flags

**Comment by Vorak2** [comment]
CLosing this becouse it is scuffed and it is easier to juse remake it

**Pull request closed without merging**
