### PR TITLE
GalaxyStation [Many Testmerges Needed]

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
(name subject to change, this was just the codename for it)

A side project that I've been working on since about November (ignoring the fact I did nothing on it for almost half that time). It originally had only one floor and was planned to be a lowpop map, but I got carried away and here we are. I haven't told many people about it, since I wasn't sure I would be able to finish it, but I had a sudden burst of inspiration and since the 12th I've been working nonstop on it. 

This map both needs more small fixes, such as light switches, request consoles, and a few security camera tweaks, but otherwise, it's completely playable. (Ignore the changed files besides the main map file, that's just me being lazy.)

## Why It's Good For The Game
An original map. Something no other codebase has but us. I think it'll be half-decent to play on.

image
image
image
image
image
image
*(finally, the lieutenant gets an office!)*
image

## Changelog
:cl:
add: Galaxystation, a brand new medpop multiz map!
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
jahwol

**Comment by triplezeta** [comment]
im one of the people who've been able to play on the map and I can say that it's overflowing with SOUL

**Comment by SynnGraffkin** [comment]
Many Testmarges needed

**Comment by MarkSuckerberg** [comment]
very broken

**Comment by dinnerwoerror** [comment]
are you going to furiously beat your meat in shame since you spent the past six months making this

**Comment by MarkSuckerberg** [comment]
[Galaxystation](https://trello.com/c/avtAHvv3/14-galaxystation)

**Comment by WindowsErrors** [comment]
to think that so many things would have been different if this had happened just a week later

**Pull request closed without merging**
