### PR TITLE
Jake from The Syndicate (Lone Op Alternative)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About the Pull Request
When Loneop is triggered and the population is below a certain threshold (set to 10 currently), the equipment the op starts with is a lot more limited. 

### Specifics
* Softsuit and Helmet with armour equivalent to someone wearing a sec helmet and an armour vest
* Jet harness so that they can actually get to the station (Warning, this replaces the backpack)
* Syndicate Uplink with 10TC (Enough to buy an emag and a bag of X4)
* Surplus rifle with one additional magazine in the pocket
* Complimentary Syndicate microbomb implant
* Crisp, ironed Syndicate Non-Copyrighted:tm: Red Polo
* Khakis

## Why It's Good For The Game
"Yeah I run the station, why does it matter?"
"Who are you talking to, Captain?"
"It's... Jake from the Syndicate."
"Jake from the Syndicate, only 20 minutes into the round? Who is this?"
"It's.... Jake from the Syndicate, I told you."
"What are you wearing, 'Jake from the Syndicate?'"
image
"Uhhhhhhhhhhhhhhhhhhhhh.... Khakis?"

## Changelog
:cl: MarkSuckerberg, Superyodeler
add: Jake from State Fa- er, the Syndicate has been sighted near Nanotrasen space. Be suspicious of any Khaki-wearing crewmembers.
/:cl:

Edit by Superyodeler: Updated Changelog

### CODE REVIEW

**Comment by Superyodeler** [comment]
Not sure about the 10 tc, being able to get an emag would lead to the same sudden Delta scenario.

**Comment by SynnGraffkin** [comment]
Again, this all spurred from someone not securing an easily secureable item to prevent an easily preventable antag.

**Comment by dinnerwoerror** [comment]
you supported the lawyer so your opinion doesn't count

**Comment by SynnGraffkin** [comment]
4fded840c8168f2f25b0919b3ee300b1

**Comment by MarkSuckerberg** [comment]
honestly this spurred from someone saying what if we gave the syndicates a polo and then me realizing that could be a jake from state farm joke

**Comment by SynnGraffkin** [comment]
Cooder fools was two weeks ago.

**Comment by MarkSuckerberg** [comment]
but... but... The Funny

**Comment by Maldaris** [comment]
I mean a less kinetic Lone Op on lowpop kinda makes sense. 

bump the threshold down to 8 and I'll give it a testmerge after review. That at least gets us one person in every department + 2-3 others.

**Comment by triplezeta** [comment]
sprites have too much soul please fix

**Comment by MarkSuckerberg** [comment]
time to yell at the headspriter to fix it

**Comment by triplezeta** [comment]
wait

**Comment by SynnGraffkin** [comment]
I would also like to say that 10 tc is pretty low. It limits the amount of meme gear you can do. The OP last night was able to do their job with just an emag and bluespace launcher (suitcase), but 10 tc isn't enough to even do a decent full stealth setup with chameleon gear.

**Comment by dee-dubya** [comment]
> 
> 
> I would also like to say that 10 tc is pretty low. It limits the amount of meme gear you can do. The OP last night was able to do their job with just an emag and bluespace launcher (suitcase), but 10 tc isn't enough to even do a decent full stealth setup with chameleon gear.

This is likely the intent and I do agree with it honestly, as long as the threshold stays at 10 or below.

It's a midround ghost role on lowpop, and you do get a free gun and allahu ackbar button on top of your TC.

**Comment by SynnGraffkin** [comment]
Speaking of the gun, @MarkSuckerberg , did you make sure it has a Syndicate firing pin?

**Comment by triplezeta** [comment]
new sprites good i approve

**Pull request merged**
