### PR TITLE
Felinids eat more like a cat , fixes allegedly bad felinid carpotoxin immunity code

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Makes it so felinids like meat and dairy and dislike vegetables and sugar. They are neutral to gross and raw now as well.

Also changes the code for felinid carpotoxin immunity to somehow be better maybe ?

## Why It's Good For The Game
Makes felinids a bit less like humans, makes the fact that they're immune to carpotoxin actually matter now that you don't need a quirk to not throw up the fish anyways.

Also less bad code maybe??

## Changelog
:cl:
tweak: Felinids now like meat and dairy, and dislike vegetables and sugar
code: made the code for felinids immunity to carpotoxin less bad maybe????
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
hold cat like hambrbubrger

**Comment by Sparrowbird611** [comment]
Don't see the point to giving them carpotoxin immunity tbh, but if it means I can lynch cats for eating my precious carpo, I'm in.

**Comment by Epsilos** [comment]
while we're here, what if poison chocolate

**Comment by Tallvisit** [comment]
What if Felinids when someone says psspsps see it in big bold text to get their attention?

**Comment by triplezeta** [comment]
allegedly

**Comment by Superyodeler** [comment]
For future reference, you should make changes on a separate branch from your master.

**Comment by tiramisuapimancer** [comment]
why for

**Review by Superyodeler — APPROVED** [review]

**Comment by Superyodeler** [comment]
It lets you make multiple prs at the same time, plus if one of your prs doesn't get merged you don't need to revert it, just delete the branch.
You can also make the branch name a funny joke.

**Comment by tiramisuapimancer** [comment]
i will learn how to do this once gitkraken does nto fuck my computer to a stand still

**Pull request merged**
