### PR TITLE
[Fix] Packedstation compiled fixes

### LINKED ISSUE #571: [BUG] Packedstation doesn't have simple robot pathing for cleanbots and such
## Testmerges:

#549: 'Loadout/Preferences Tweaks II' by MarkSuckerberg at commit b94f5e7b97
#548: 'Kiloproovements' by triplezeta at commit e8401c622e
#471: 'Sleeper rework(?)' by MarkSuckerberg at commit 65aeb043f3
#565: 'CI Update' by MarkSuckerberg at commit 85ad349292
#389: 'Galaxystation [Let's try this again.]' by MarkSuckerberg at commit 

## Reproduction:

Set robot to patrol, it doesn't move.

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Fixes the following: 
- Simplebot pathing
- Replaced floor tiling in maint with plating like maint should be
- missing piping to aft solars
- missing wiring to armory apc
- replaced modular hop ID console with standard hop ID console

## Why It's Good For The Game

Fixes #571 

## Changelog
:cl:
fix: Robots can now properly path around the main halls of Packedstation when on Patrol (｀∇´ゞ
fix: Floor tiles in maint replaced with plating on Packedstation.
fix: Missing wires and piping have been laid down.
fix: Modular HoP console on Packed was replaced with standard HoP console.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Updated with fixes from bug reports

**Comment by dinnerwoerror** [comment]
i never really figured out what it was with the whole zoomer ass modular id console when the one we know already works just fine

officer beepsky is back with the under-the-floor grey and orange bot waypoint markers

there still isn't like, any kind of security evidence locker to dump all of the traitor's stolen items into, unless you're expecting security to keep it in their backpacks which we were kind of already doing and also the straightjacket would be nice because sometimes people buy freedom implants and theyre annoying as fuck and it would be nice to have a countermeasure since you cant freedom implant out of one

there also isn't any kind of brig physician locker or security infirmary or even just a nanovend on the wall, of all the roles i know of, security is probably the one that legitimately deserves some form of portable healing like the heavy's sandvich in TF2, and unlike what minius tells me, there are indeed situations where sec won't have the time or the opportunity to go down to the medbay to be given shitty tier 1 trek chems in a sleeper

**Review by MarkSuckerberg — APPROVED** [review]
personally I want a vote on the plated maint, but the changes are sound

**Comment by dinnerwoerror** [comment]
how are we supposed to get the safe open if there is no stethoscope anywhere

**Pull request merged**
