### PR TITLE
TG Merge 6

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
*Notable exclusions:*
- [x] Nu-botany
- [x] Hydrogen
- [x] The weird lizard speaking change thingy
- [x] Compact combat shottie removal (why was this even a thing?)
- [x] Runescape Chat defaulting to on
- [x] Strange new shuttle wall icons
- [x] Tiered canisters
- [x] The CLARKE mech

## Why It's Good For The Game
Improvements from /tg/ and keeping modularized.

## Changelog
:cl:
rscadd: the original compact combat shottie has been reunited with its family
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
if there is anything from recent TG (Anything from April 24th to now) that you do NOT want on waspcode, please add a comment stating what it is (and preferrably linking a PR.)

**Comment by MarkSuckerberg** [comment]
What zeta said. Also I'm aware it isn't working, I just haven't been able to test anything lately so until then I'm gonna stick a DNM on this until I can test this thoroughly.

**Comment by MarkSuckerberg** [comment]
[/tg/ Update #6](https://trello.com/c/ZeC5JX3M/33-tg-update-6)

**Comment by SynnGraffkin** [comment]
These may cause conflicts to a degree. (I am aware one is Bee)

https://github.com/tgstation/tgstation/pull/50740
https://github.com/BeeStation/BeeStation-Hornet/pull/1692

**Comment by CRITAWAKETS** [comment]
https://github.com/tgstation/tgstation/pull/50775 (major balance issues, including instant-kill acid and 6 burn damage per tick syringes, which can be 36 if you get an entire rapid syringe gun volley in)
https://github.com/tgstation/tgstation/pull/50734 (C20r is an almost instant-kill on unarmored targets with this PR. Need i say more?)
https://github.com/tgstation/tgstation/pull/50713 (We still have medical genetics)
https://github.com/tgstation/tgstation/pull/50636 (We should do our own vote for how to handle the emag, but so far it should remain in the current state it is)
https://github.com/tgstation/tgstation/pull/50610 (just remove the CRAB)
https://github.com/tgstation/tgstation/pull/50608 (This should be voted or decided by you, if you wonder, its runechat)
https://github.com/tgstation/tgstation/pull/50552 (metalgen removal should be on a vote, but so far this just seems like a "stop having fun" PR, i mean what do you even expect from goof)
https://github.com/tgstation/tgstation/pull/50535 (we're planning on removing skills, also easy mythril)
https://github.com/tgstation/tgstation/pull/50521 (fetish content)
https://github.com/tgstation/tgstation/pull/50471 (there are many ways of rebalancing cryo syringes, and removing both them and the reasonable substitute is not one of them, also the PR was half-assed and keeps in cryobeakers, which might actually be worse)
https://github.com/tgstation/tgstation/pull/50482 (test on ministation before merge, it might be too big for the escape shuttle area and thus engulf the arrivals shuttle)
https://github.com/tgstation/tgstation/pull/50465 (removes ai integrity restorer for a change we dont need)
https://github.com/tgstation/tgstation/pull/50420 (nubotany pr that can affect us)
https://github.com/tgstation/tgstation/pull/50384 (hurr durr, me good coder, me totally fix issue of them changing their production consoles to the proper console!!! just ignore the imprinter which is used more often)
https://github.com/tgstation/tgstation/pull/50342 (this is dumb and powergamey, though honestly penthrite's explosive effect should be removed as this is literally just how nitroglycerin acts IRL but without being nitro)
https://github.com/tgstation/tgstation/pull/50290 (**HAHA, NO. FUCK THAT**)
https://github.com/tgstation/tgstation/pull/50292 (man xenobio is so fun when you cannot pocket your bag)
https://github.com/tgstation/tgstation/pull/50183 (merge this, but special attention to this cursed PR)
https://github.com/tgstation/tgstation/pull/50074 (nerf something thats trash already 10/10)
https://github.com/tgstation/tgstation/pull/49964 (tider role, do not want)
https://github.com/tgstation/tgstation/pull/49899 (**TG AT ITS FINEST**)

And thats my short list of what not to include. I havent included any PRs that already have one of its dependancies under this list.

**Comment by dinnerwoerror** [comment]
a lot of these "im deceased" tier removals or 'rebalances' do hold quite a bit of water

**Comment by dinnerwoerror** [comment]
the emag's remained functionally unchanged since it was first added in 2010

the crab 17 is just a fuckin meme item to be honest

i think morg said something about how he felt uncomfortable about runechat

eventually there's an instance where you get instantly blown I to pieces by a nitroglycerin cryo syringe one too many times, especially considering how the cat is out of the bag now; there were many ways of rebalancing null crates and the 'reasonable' c*ntractor kit substitute, and look how all of them turned out, eventually you get wearied from trying to pinpoint where some cargonian/contractor is concealing their shit like it's a game of Operation

moving the research and development console to the bridge seems like another attempt at centralization, which in my eyes is OK, since if you've ever played europa universalis then youll know how more centralization is pretty much always a good thing, although it does show its own risks though considering how petty criminals are hacking open the doors to the bridge every quarter hour

overall yes, it is IN BOLD TG AT ITS FINEST

**Comment by triplezeta** [comment]
We actually *aren't* planning on removing skills, the github project board is outdated.

**Comment by MarkSuckerberg** [comment]
a downside of centralization on CK2 however is that you have a lower vassal limit, which means you have to make like, 5 really powerful losers who could all overthrow you instead of like, 50 little baby losers who you can curbstomp in your sleep

**Comment by triplezeta** [comment]
tgstation/tgstation#50471 As a previous abuser of these fucking syringes, please remove them. Completely. I don't see a way these pieces of hellfuck could ever be truly balanced when at the moment they outclass every other form of ammo. Also, I have tested cryo beakers to see if they could potentially be abused. They can't.

**Comment by dinnerwoerror** [comment]
the only real way cryo beakers could be abused is if you slip them in someone's bag and blow them up from far away, or in grenades or something

wait isn't that just what meth bombing is for

**Comment by triplezeta** [comment]
even in grenades, you're much better off just going with the highest capacity beakers you have access to instead of using the noreact 50 unit beakers, as you can already use how grenades work to create much larger and better explosions.

**Comment by dinnerwoerror** [comment]
personally i get a box and fill it with like, a thousand units of black powder and then light it up and leave it somewhere like im a wild west bandit using dynamite to blow up the slave plantation manor

**Comment by triplezeta** [comment]
my method is to stuff 5 meth grenades into a toolbox or something and then leave it somewhere where you'd expect a red toolbox to be, then set it off with a signaller.

**Comment by dinnerwoerror** [comment]
the joke is that dynamite is made of nitroglycerin and was made in 1867 so nothing i said actually related to my analogy

**Comment by SynnGraffkin** [comment]
Personally, I don't care about the pounce from catgirls and I like cryosyringes as an ammunition type, even if it is abused with things like Nitro. 

In regards to the Emag change, which would be its own discussion, if we wanted to nerf the Emag, I would just suggest going towards Citadel's change by making it a limited use item and you can spent TC on an recharge to add more uses. It makes emag less of a free access card and more so requires better decision making on the user end. In regards to Ops, just let them have the original emag, since op rounds aren't long anyways.

**Comment by MarkSuckerberg** [comment]
I believe that it's ready for a testmerge.

**Comment by MarkSuckerberg** [comment]
*total rebase merge conflict resolution failure detected*

**Comment by MarkSuckerberg** [comment]
Closing until it's updated to latest /tg/ again.

**Comment by MarkSuckerberg** [comment]
Fuck it, it needs to happen, and it's probably smarter to update to here before trying to update to current /tg/

**Comment by MarkSuckerberg** [comment]
Ready for testmerge. I would normally ask someone to review this for me now that we have maintainers, buuuuuut...
image
Yeah.

**Comment by dee-dubya** [comment]
who are we going to blame for all the trash we inherit now that orange is kill

**Comment by Superyodeler** [comment]
Oranges will always be at fault in our hearts

**Comment by Superyodeler** [comment]
The same error from the smartwire revert

**Comment by SynnGraffkin** [comment]
So mappdiff bot just sucks at rendering

**Comment by Superyodeler** [comment]
It turns out [this pr](https://github.com/tgstation/tgstation/pull/49307) made it so that /obj/machinery/mineral no longer starts processing automatically.

Add this line to machine_bluespaceminer.dm to make them work again.
`	processing_flags = START_PROCESSING_ON_INIT`

**Comment by Superyodeler** [comment]
[This PR](https://github.com/tgstation/tgstation/pull/50225) added an additional argument to `/mob/living/carbon/human/proc/hardset_dna`, which broke cloning.

In cloning.dm and exp_cloner.dm replacing this
`	H.hardset_dna(ui, mutation_index, H.real_name, blood_type, mrace, features)`
with this
`	H.hardset_dna(ui, mutation_index, null, H.real_name, blood_type, mrace, features)`
should fix it, and is how TG's admin respawn command handles the new argument.

**Comment by Superyodeler** [comment]
Unless anyone knows of any more issues, I think this is ready for another test merge.

**Comment by Superyodeler** [comment]
At least on metastation, the mining shuttle has a different shuttle door that doesn't seem to fit

**Comment by MarkSuckerberg** [comment]
notes from testmerge: FIX REPLAYS YOU DUMKASS, shuttle door still bad, remove clarke

**Comment by dee-dubya** [comment]
clarke did nothing wrong

clarke is a good boy

**Comment by MarkSuckerberg** [comment]
i will eat the clarke's family one by one in front of them whilst slowly deleting their code line by line until there is nothing left but a sprite that i can't remove because that wouldn't be modularized

**Comment by dinnerwoerror** [comment]
Don Arbuckle did nothing wrong

**Comment by TheNeoGamer42** [comment]
don arbuckle needs to be removed via code, along with the clarke, also please remove the TG brand Lagware from this

**Comment by dee-dubya** [comment]
fr though, I really enjoy the clarke on a visual level as a replacement for the firefighter, which is just a bleh reskin of the ripley.

If functionality is people's main concern, then why not make the clarke functionally identical to the firefighter it should be replacing?

**Comment by SynnGraffkin** [comment]
Clark is bad mech. It's worse than firefighter in every way.

**Comment by MarkSuckerberg** [comment]
FUCK

**Comment by MarkSuckerberg** [comment]
I'm stopping adding any more non-fixes from this point on, since we need this merged.

**Comment by dee-dubya** [comment]
https://www.youtube.com/watch?v=XqNjl7HfCXM

**Pull request merged**
