### PR TITLE
Shard logging part 2

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Improves caltrop logging by logging after damage is dealt and logging even if the victim isn't being dragged.

## Why It's Good For The Game

Makes NEW HP accurate, and makes it more obvious when someone is being pushed into a pile of glass.

## Changelog
:cl:
fix: NEW HP logged when stepping on caltrop is accurate
admin: Taking damage from a caltrop is reported in the attack logs
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
seems pretty spammy for the admin logs, I imagine they wouldn't want to hear about how an ashwalker stepped on cactus for the Xth time.

**Comment by Superyodeler** [comment]
It doesn't show up in the chat, just if you download the attack logs.

**Comment by triplezeta** [comment]
understandable

**Comment by Superyodeler** [comment]
Making a change to this real quick

**Comment by Superyodeler** [comment]
Alright, I'm done

**Pull request merged**
