### PR TITLE
Galaxystation & Better MultiZ Support

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
(name subject to change, this was just the codename for it)

A side project that I've been working on since about November (ignoring the fact I did nothing on it for almost half that time). It originally had only one floor and was planned to be a lowpop map, but I got carried away and here we are. I haven't told many people about it, since I wasn't sure I would be able to finish it, but I had a sudden burst of inspiration and since the 12th I've been working nonstop on it. 

This map both needs more small fixes, such as light switches, request consoles, and a few security camera tweaks, but otherwise, it's completely playable. (Ignore the changed files besides the main map file, that's just me being lazy.)

## Why It's Good For The Game
An original map. Something no other codebase has but us. I think it'll be half-decent to play on.

image
image
image
image
image
image
*(finally, the lieutenant gets an office!)*
image

## Changelog
:cl:
add: Galaxystation, a brand new medpop multiz map!
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
NSV Galaxystationship

**Comment by triplezeta** [comment]
you may want to change the plasma windows over the HE junctions in the SM to reinforced walls

**Comment by dinnerwoerror** [comment]
where will you be during the random chimp event

**Comment by dinnerwoerror** [comment]
Spending all my nights, all my money going out on the town
Doing anything just to get you off of my mind
But when the morning comes, I'm right back where I started again
Trying to forget you is just a waste of time

Baby come back, any kind of fool could see
There was something in everything about you
Baby come back, you can blame it all on me
I was wrong, and I just can't live without you

All day long, wearing a mask of false bravado
Trying to keep up the smile that hides a tear
But as the sun goes down, I get that empty feeling again
How I wish to God that you were here

Baby come back, any kind of fool could see
There was something in everything about you
Baby come back, you can blame it all on me
I was wrong, and I just can't live without you

Now that I put it all together
Give me the chance to make you see
Have you used up all the love in your heart
Nothing left for me, ain't there nothing left for me

Baby come back, any kind of fool could see
There was something in everything about you
Baby come back, listen, you can blame it all on me
I was wrong, and I just can't live without you

I was wrong, and I just can't live

**Comment by dinnerwoerror** [comment]
there will be a time when technology becomes so advanced that we'll rely on it to make maps rather than talent

maps will lose its soul

**Comment by triplezeta** [comment]
shut the fuck up github

**Comment by dinnerwoerror** [comment]
he's gone

**Comment by MarkSuckerberg** [comment]
I would have tried to get it in more if people had helped debug why it wasn't starting when I had asked :eyes:

**Comment by dinnerwoerror** [comment]
the place i had to live in burnt down but i do have a box of moths

**Comment by MarkSuckerberg** [comment]
it actually works again, lads

**Comment by dinnerwoerror** [comment]
i gotta say, dropping things on people from the 2nd story rafters is too fun, you should implement it more somehow

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
