### PR TITLE
Project Unfuck Box Phase 1 - Rewiring

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Using [Screw Box Part 1: Phantom Mapping #50430](https://github.com/tgstation/tgstation/pull/50430) for reference, I rewired Box Station similarly to this. Most of the APCS that were in Maint are now in their respective rooms as well. 

This includes

- Art Storage
- AUX Base Construction
- Bar
- Botany
- Cargo Warehouse
- Cargo Bay
- Courtroom
- Chapel
- CMO Office
- Cremator
- Detective
- Dorms
- Fitness Room
- Garden
- Gateway
- HoP office
- Incinerator
- Janitor closet
- Kitchen
- Labor Shuttle Dock
- Lawyer
- Library
- Locker Room
- Locker Room Toilets
- Medbay
- Medbay Treatment Center
- Meeting room
- Mech bay
- Port Emergency Storage
- Security Checkpoint (Arrivals)
- Starboard emergency storage
- Telecomms Monitoring
- Theatre
- Vacant Commissary
- Vacant Office

## Why It's Good For The Game

Trying to solve the wonky powernet issues. I ran two tests locally using only purely solars, no hotwiring, random events off (no extra mice), and making sure all wire chewing rodents were dead. First test ran about two hours, and the second ran about 7 (partially while I slept), with no powernet drops.

Due to the nature of Box's notorious powernet problems, this would require a test merge to fully see if there are any noticeable drops, since it is hit or miss if the powernet fucks up or not.

With significant feedback on if this works or not, there is another potential solution.

## Changelog
:cl:
balance: Nanotrasen has decided to re-draw boxstations powergrid blueprint to make it easier to work with, for both the engineers they employ on the station and the engineers who they employ to maintain and work on their blueprints.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
[Fixing box](https://trello.com/c/7AJBmGJm/26-fixing-box)

**Comment by MarkSuckerberg** [comment]
It's gone a few rounds without any issues, is it ready for a fullmerge?

**Comment by dee-dubya** [comment]
This still needs medbay(at the very least) to be wired correctly

**Comment by SynnGraffkin** [comment]
@dee-dubya Read the previous commit

image

**Comment by SynnGraffkin** [comment]
>Conflicting files
 since when?

**Comment by MarkSuckerberg** [comment]
Just recently, I'll try to resolve them sometime today

**Pull request closed without merging**
