### PR TITLE
s p a g h e t t i

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
anyone who doesn't have stuff in their pockets roundstart now has boiled spaghetti in their pockets
## Why It's Good For The Game
spaghetti
## Changelog
:cl:
add: most people have spaghetti in their pockets for no reason at all
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
based

**Comment by kurpingspace2** [comment]
i can't believe you actually took time to change everything

**Comment by TheNeoGamer42** [comment]
it was easy as copy paste the file path for spaghetti and typing l or r and having it autofill

**Comment by Superyodeler** [comment]
Save us, @github-actions.

**Comment by TheNeoGamer42** [comment]
speed merge now its literally the best PR

**Comment by dinnerwoerror** [comment]
buddy, today is just the tip of the iceberg, just you wait

wait 4 minutes and 43 seconds actually

**Pull request closed without merging**
