### PR TITLE
Fixes gateway (Goddammit.)

### PR DESCRIPTION
**Pull request by miniusAreas**
## About The Pull Request

Makes the gateway room not look like a horrendus mess of 9 gateways, and lowers it down to the one gateway it SHOULD have been.

## Why It's Good For The Game
 
Fixes the fact that someone played "assemble the gateway so it looks nice in the mapping interface" because that's not how it works.

## Changelog
:cl:
del: Removed the eight extra gateways. God bless mini.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
needs a vote

**Comment by miniusAreas** [comment]
zeta I am going to fucking smite you

**Comment by SynnGraffkin** [comment]
Blame the guy on TG who turned every gateway piece into a singular gateway object. I've been meaning to get around to this, but have been distracted.

**Comment by dinnerwoerror** [comment]
heha minis is morg

**Comment by MarkSuckerberg** [comment]
whooopsies

**Pull request merged**
