### PR TITLE
White Sands

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The PR
Adds the previously secretly in development White Sands content.

Firstly, non direct contributor credit:
- Powerfulbacon for custom shuttle creation (also most of the shuttle creation wiki page)
- Also Powerfulbacon for the initial engine code, but it has been since near completely rewritten.
- Multiple Baystation12 coders (I couldn't manage to find many names, but if you'd like your name here please contact me) for the overmap concept and minimal amounts of code, although what snippets have been taken have since been completely rewritten. 

Secondly, I'm not a good writer so I will just quote from the forum announcement [here](https://forum.white-sands.space/d/68-boomerstation-year-two):
> As some of you might be aware, we've been working in secret for awhile on a project (its name itself a meme and misdirection). Started in mid-June, our goal was to develop a brand-new set of content for Boomerstation, cultivate a set of unique features for the server, and further develop and solidify our uniqueness as a codebase.

## Why It's Good For The Game
Lotsa new, unique content. It'll make our server stand out from the rest, I hope, and will give us a good platform to build on further.

## Changelog
:cl: The White Sands Development Team
add: Deepcore mining drills, allowing for BSM-like mining while being significantly less braindead.
add: Two mining planets, including the Icemoon and an entirely new location, Whitesands.
add: A few new chems to go with the new locations.
add: New mobs and plants for icemoon and whitesands.
add: A new overmap system to give space a lot more depth.
add: Custom shuttle creation
add: Powered/fueled engines to fly around the overmap with
tweak: All configs now (by default) reference White Sands rather than TG or Waspstation.
imageadd: Security and command have been resprited. Yes, again.
del: BSMs are gone.
balance: Most of the mining mobs and gear have been rebalanced a small degree.
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
281 file changes marg this is alotta file change

**Comment by MrFagetti** [comment]
what does this mean

**Comment by MarkSuckerberg** [comment]
PR #679

**Review by Shadowtail117 — CHANGES_REQUESTED** [review]
The HoS jacket in waspstation/icons/mob/clothing/suits.dmi has some extra pixels on its right-facing side that look out of place:

image

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
