### PR TITLE
Pet collar wearable

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request

You can wear pet collars again. Also changed the description slightly

## Why It's Good For The Game

It's not really honestly

## Changelog
:cl:
fix: you can be a degenerate again
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
uwu

**Comment by TheNeoGamer42** [comment]
goddamnet ogan

**Comment by dee-dubya** [comment]
no fetish content please

the pet collar is for pets

**Comment by dinnerwoerror** [comment]
wait, no fetish content? really?

**Comment by triplezeta** [comment]
Deedubya, everything is fetish content.

**Comment by MarkSuckerberg** [comment]
comment

**Comment by TheNeoGamer42** [comment]
this entire PR was a mistake, but I am not closing it, I will not back down from my mistakes in life

**Pull request merged**
