### PR TITLE
Less murderbone traitors

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Flips the maroon with assassinate in the objective possibilities and changes up percentages for getting theft or murder/strand objectives. Traitors now only have a 10% chance of getting a murder objective, and a 30% chance of a maroon objective, with the rest being item theft.

## Why It's Good For The Game

As an initial step down the path of reducing player-removing events during traitor rounds, this gives traitors more incentive to play along long enough to strand the person on the station. This should be expanded on later with additional types of objectives that affect other players other than maroon or murder as discussed previously.

## Changelog
:cl:
balance: 10% Chance for Murder as Traitor objective, 30% Maroon, 60% Theft.
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
haha gun go pwap pwap

**Comment by triplezeta** [comment]
image
the commits mald

**Comment by Maldaris** [comment]
> image
> the commits mald

Yeah I think I fucked this up, hang on, I'll open another one when I'm not screaming at git.

**Comment by dinnerwoerror** [comment]
no no, i do the same thing all the time, let him pass

**Pull request closed without merging**
