### PR TITLE
Sleep Healing

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Sleeping through the IC tab Sleep verb will now heal you even when below 80 hp, with changes based on sleeping on a bed/table, blanket, mood, and metabolism.
Healing sleeping on a bed with sheets gives 10 hp, with up to 5 bonus from mood and metabolism.
The healing amount is intentionally low in order to encourage alternatives like meds, surgery, and donk pockets.
Base: 5hp
Bed: 4
Table: 2
Sheet: 1
Mood: +2, -1
Metabolism: +3, -2

## Why It's Good For The Game

Could provide a source of passive healing as in the To-Do list. Would give players a reliable source of healing while hopefully not strong enough to eclipse methods that take resources/other players.

## Changelog
:cl:
tweak: Sleeping now always heals
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
zzz

**Comment by SynnGraffkin** [comment]
Between the Sheets is now a stronger medicine than cobbymed

**Comment by Epsilos** [comment]
is this only the basic damage types, or can you nap off a bad cloning?

**Comment by Superyodeler** [comment]
@Epsilos Only brute, fire, stamina, and toxin at half strength

**Pull request merged**
