### PR TITLE
better robot icon handling

### PR DESCRIPTION
**Pull request by kurpingspace2**
## About The Pull Request
Added a function instead of a switch wall for each icon change

## Why It's Good For The Game
It's much faster and it's much better to look at

## Changelog
:cl:
Tweak: Renamed the icons
Add: A temporary define for icon sets
Add: Proc for changing icons
Add: More icons!
Remove: Removed switch wall and replaced them with the proc
Tweak: Replaces massive switch walls with a proc for each job and also moved everything close together so it's actually easier to get to what you want to change.
/:cl:

### CODE REVIEW

**Comment by kurpingspace2** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by kurpingspace2** [comment]
probably gonna add icon changes for the syndie and peacekeeper bots since i can see a few there

**Comment by SynnGraffkin** [comment]
Yeah, I didn't grab the Syndicate models.

**Comment by kurpingspace2** [comment]
@SynnGraffkin did you remove the transform animations too for the default borgs? or were they gone before you made your PR or did I remove them?

**Comment by SynnGraffkin** [comment]
The "Default" borgs that TG uses should still have animations. The icons didn't have transform animations so they just sit there for a second and poof.

**Comment by kurpingspace2** [comment]
mm.. i'll test again soon then, i remember testing and seeing the engi borg animation not there for some reason.

**Comment by kurpingspace2** [comment]
holy shit it actually fucking passed this time

**Comment by kurpingspace2** [comment]
there's a graphical bug i need to solve. the eyes are shown before the animation finishes, which is a problem. need to figure out how to add the eyes later.

**Comment by kurpingspace2** [comment]
some thing to note, php failed on that commit for some reason?
the eyes for the bot still appear when doing animation, and this isn't a new bug.
i added a lot more icons.

**Comment by kurpingspace2** [comment]
Waiting for spriters

**Comment by dinnerwoerror** [comment]
haha, stale moth!

**Comment by MarkSuckerberg** [comment]
do moths get chewy when stale like pretzels, or crunchier like biscuits

asking for a friend

**Comment by dinnerwoerror** [comment]
they get chewy

**Comment by Superyodeler** [comment]
Moths are supposed to be crunchy, so yes, they get soggy if you leave them out.

**Comment by dinnerwoerror** [comment]
i always thought they got chewy from decomposition

**Pull request closed without merging**
