### PR TITLE
[Port] Updates Box Brig to Citadel's

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

This PR redesigns Box's Brig to be more similar to Citadel's Brig. 

Changes include the following. 

Permabrig - Adds some grass to the garden, some comfy chairs, a couch, a mirror to the bathroom, and the option to Cryo on long rounds.

image

Adds a firing range near the Gulag shuttle. 

Redesigned the Brig infirmary, with operating equipment included. 

image

Warden's brig control is now additionally the front desk for the Brig, further cementing their role to not leave the damn brig. 

image

Armory was separated from brig control, but easily accessible for the Warden or related access, including the option to open some shutters for when the team needs to gear up. EVA equipment was separated into its own room nearby.

image

HoS office has been reinforced, including some shutters for all the windows as well as replacing the simple walls with R-Walls. Why was his office not reinforced in the first place? 

image

Security office has a couch, microwave, and some DONK. Techfab and computer consoles were moved to Brig central, with the same security access required to access.

image

Fore / Port Bow maintenance has been modified to accommodate the moving of the Gulag shuttle. The small chemical storage closet by Beepsky's room has been expanded a bit to encourage ghetto chems a bit. A new room has been added next to it, where Birdboat now resides with his own pet bed and some general maint loot. 

image

## Why It's Good For The Game

image

## Changelog
:cl:
add: Permabrig on Boxstation is a bit more cozy for your stay.
balance: Boxstation's Brig and parts of the Fort / Port Bow maintenance has been redesigned.
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
supposedly this map design is from citadel station, and it does show

the pbrig having a green sleeper is a no brainer, to encourage the people there to finally just end it all and rid themselves of the incessant 8 hour greenshifts
it seems like the pbrig has intentionally been left barren and unfun by mappers over the years, except with the addition of the prisoner role the trend is reversing, because now people are complaining about how there's nothing to do in the pbrig, which is a case of irony

it's still beyond me why the security firing range even exists as a tangible thing, considering how the only thing i ever used that place for was for strangling people i didn't like

i personally think the infirmary was fine as it was, but i guess different people have different ideals, whatever the western edge of the room is rwalled for is beyond my comprehension though

putting the warden near the main hallway will probably give some unintended side effects, such as the place being too small to add any extra consoles
i personally haven't had all that many outstanding grievances related to wardens leaving their post, usually related to it either being too irresponsible an action to remain or them being too incapable to, such towards the station being too chaotic or them being too dead respectively, so your issue probably stems from them as a security player rather than something us game contributors should fix

yes, i know the warden is "only 3 tiles away from the armory", although my point of contention is what is replacing the area between the warden and the armory, that being the main hallway connecting the entire department together, if there's like, a single issue in that hallway, particularly one related to red fire airlock hallway fastmos, you're kinda boned aren't you
some servers such as bay station do have the disconnected warden, although they seem to mitigate the issue relatively well by having the warden's access to the armory be properly secured with something like a side tunnel or a section of the hallway outside of common view, instead of here where there are quite literally windows allowing a clear view of the guns sitting on the racks
i hope there's a table under one of those shutters, so that the warden can hand out weapons on a selective basis, instead of being forced to awkwardly throw them through the door or having to open the floodgates and commence trick or treating for lack of a better phrase, even tg got that one right
Screenshot (1073)

i don't know what it is about tg map design, but why do they have so few space suits? there's 8 seccie job slots yet pretty much every tg related map i've seen has had only like 3 hardsuits for the entire department
~~i remember a round on beestation presage where atmos was fucked and the silicons had to divvy out the 21 space suits on the entire map for all 49 crew not including the plasmaman~~

kinda beyond my line of thinking why the security techfab was moved to the center of the department instead of just leaving it at its normal place in the actual security office, does that mean we have two security offices now or something?

i don't really care too much for the quality of maintenance as long as it's not like, directly adjacent to a critical area of the station, freakin choomists thermiting into the craptains office 10 minutes into the round

yes, i do just think it is neat

**Comment by dinnerwoerror** [comment]
i would say my issue with the hallways is only exacerbated by the fact that there isn't a single firelock in that hallway

i shit you not, there's like, a 32 tile stretch of hallway where there are no firelocks, i can't even show the whole length in a single screenshot

Screenshot (1075)

compare this to, say, the research or medical department hallway, where there's firelocks or proper airlocks splitting apart the different sections of hall

Screenshot (1074)

**Comment by dinnerwoerror** [comment]
see, i was right, no tables

Screenshot (1140)

**Comment by SynnGraffkin** [comment]
It doesn't need the tables. If you're opening the shutters, shit clearly hit the fan.

**Comment by MrFagetti** [comment]
Remember lads, as long as your Perma doesn't look like this I will not complain

image

**Comment by SynnGraffkin** [comment]
Skyrat, lol

**Comment by triplezeta** [comment]
bro that's not a permabrig that's a fucking resort hotel

**Comment by Sparrowbird611** [comment]
Prisoner role was a mistake :)

On another note, I'm gonna go commit some crimes so I can get thrown into that cell. Free food, large area, hell I bet they got a personal bar in there somewhere.

**Review by Superyodeler — APPROVED** [review]

**Comment by dinnerwoerror** [comment]
oof

**Comment by SynnGraffkin** [comment]
3 to 10 vote, if you don't include my own.

**Pull request closed without merging**
