### PR TITLE
Just Another Cargo Re-balance

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

morkag, will cargo ever be balanced

probably not

but at least it is a much more noble quest than zesko's dead horse beating in virology

and yes i did test it and it works

## alright, so like

**the good**

the new crates change the dichotomy between the antags and cargo by forcing a more active involvement with them if they want the gaymur geer, instead of hacking the supply console and hacking your way into cargo's hearts as well

there's also a couple other new crates to the manifest as well too but they aren't too much to go into

also, the inducer crate has the engineering inducers instead of the poo poo pee pee science inducers

**the bad**

the BZ export price is slashed and miasma exports have been made into a bounty 

and nulls no longer exist as well

ive repented, zesko

**the ugly**

Dangerous crates now exist, which, when ordered, silently send a message to the admins

other than that, nothing else happens when you buy a dangerous crate

the higher administration reserves the right to crack down on non antag cargo workers that buy crates of armory weapons in the dozens and then resist arrest with lethal weapons when security comes to confiscate them

this is a warning

Screenshot (525)

## Why It's Good For The Game

gas harvesting has kind of become a bit of a meme meta when randomized lavaland atmos was added

with randomized lavaland atmos, the meta is to turn the aux base into one huge gas succ refinery and harvesting hundreds of thousands of credits worth of gases from the atmosphere of lavaland alone by the 30 minute mark

now, miasma farms have existed ever since time immemorial, but they were always a small scale supplementary form of income, but with the combination of randomized lavaland atmos, it kind of got out of hand, and cargo should not be buying fucking bicycles in the dozens with nothing but max level parts and a Paradox dice roll

## Changelog
:cl:
cuts: le ebin nulls
nerfs: mi ass ma is a bounty and bz exports have been slashed
adds: a couple new crates as listed...

1. emmets vintage heater crate (yes this is a GTA san andreas reference)
2. and heater supplies
3. literally just a telecrystal, at least it requires active collusion with an antagonist requiring an uplink and all
4. cooler autorifle ammo, still expensive as balls tho
5. the fashion crate to end all fashion wars, you gonna be looking fly as frick when you're walking down the aisle, the aisle of the security department in handcuffs that is

tweaks: dangerous crates now exist, yet another way to spam the admin logs with you buying 30 shotguns for no reason
/:cl:

### CODE REVIEW

**Comment by Baldir-Odensen** [comment]
Yes removing miasmas value would remove content as it would remove the reason to make a miasma farm and then you have less things for a cargotech to do except tide and buy guns

**Comment by Superyodeler** [comment]
It looks like this needs to be modularized.

**Comment by dinnerwoerror** [comment]
edited to actually clarify on dangerous crates

**Comment by dinnerwoerror** [comment]
I would rather not have unneeded nerfs to things that aren't problems.

**Comment by SynnGraffkin** [comment]
Removing the ability to sell Miasma, outside of RNG bounty generation, is completely unneeded. As I said before, this could be resolved by just removing Miasma from Lavaland's random atmos, considering one of the main counterpoints was people turning the Aux base into just a gas farm planetside. Cargo techs, or anyone else, would have to actually work on producing Miasma instead of just farming it on the planet.

**Comment by MarkSuckerberg** [comment]
Unironically removing miasma from Lavaland would be a really good idea in my opinion, since it as a gas is generally performance-heavy. I don't think anyone would really have any issues with it being gone.

**Comment by SynnGraffkin** [comment]
Cargo would still be able to farm Miasma if they make a farm for it, and it removes turning the aux base into a giant gas farm on the planet if you roll Miasma. Cargo can still make their money but they require more work. Removing the ability to sell Miasma entirely, outside of an RNG bounty, is fucking retarded.

**Comment by SynnGraffkin** [comment]
Zeta knows that's the only real way to balance that since we are both guilty of Aux base brap farming. 😂

**Comment by triplezeta** [comment]
yeah lavaland gas harvesting is kind of ridiculous

**Comment by dinnerwoerror** [comment]
alright, since you wooden headed jesters of peasants seek reform in my ways, i've decided to look up to history to find an answer

https://github.com/tgstation/tgstation/pull/44427/files#r296460507

Screenshot (536)

@zeskorion null crates fucking disgust me now

**Comment by dinnerwoerror** [comment]
personally i think that modularizing the wrong things is better than modularizing nothing

a failing grade is always better than no grade

**Comment by triplezeta** [comment]
what's modularization

**Comment by dinnerwoerror** [comment]
i think it's a tactic the ZAR kommandos used during the Boer wars of the 1890s

**Comment by SynnGraffkin** [comment]
But you're making what is essentially a one line change into a full modularization.

**Comment by dinnerwoerror** [comment]
and does this make it unworthy?

**Comment by SynnGraffkin** [comment]
Considering that modularization is better for additional content, not existing content, yes. If it is a one line change, it is a one line change. It doesn't need to be modularized.

**Comment by MarkSuckerberg** [comment]
I hafta agree this's just making more work for yourself

**Comment by MarkSuckerberg** [comment]
It's been testmerged for a while, it passed the vote, and nobody seems to have complained, so I'm going to merge it even though it's a bit over-modularized.

**Comment by dinnerwoerror** [comment]
NOOOO, NOT MY HUNDREDS OF THOUSANDS OF MIASMA BUCKS

images

**Pull request merged**
