### PR TITLE
Wig suicides

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Adds the ability to commit suicide with wigs. Species that have any business having hair will strangle themselves, other species stitch it to their head.
Thanks to FancyCyclops for the idea!

## Why It's Good For The Game

R E Q U E S T E D

## Changelog
:cl:
add: Added wig suicides
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
YOU DID IT OH MY GOD

**Comment by triplezeta** [comment]
based

**Comment by Superyodeler** [comment]
Fixed a bug where dullahans and zombies could strangle themselves

**Comment by FancyCyclops** [comment]
Hacky code. Maybe. But it's amazing.

**Pull request merged**
