### PR TITLE
WT550 resprite

### PR DESCRIPTION
**Pull request by 1glitchycent**
## About The Pull Request
Resprites the WT550 and it's magazine states

## Why It's Good For The Game
It looks better, was also requested by the head spriter

## Changelog
:cl:
add: New WT-550 sprites
del: the old sprites, while still technically in the game, wont be used anymore
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
"""head""" spriter




I feel now is a good time to remind everyone that the """head"""spriter role is a joke role and that i have no actual authority

**Comment by 1glitchycent** [comment]
> """head""" spriter
> 
> I feel now is a good time to remind everyone that the """head"""spriter role is a joke role and that i have no actual authority

I am aware, I just put that there because I wanted something in the why it's good for the game section besides "muh sprite good"

**Comment by triplezeta** [comment]
heyyy it passed nice

**Comment by 1glitchycent** [comment]
haha coder!

**Comment by MarkSuckerberg** [comment]
what in hell

**Comment by triplezeta** [comment]
MARK WHY

**Comment by MarkSuckerberg** [comment]
I don't know how this happened what in

**Comment by MarkSuckerberg** [comment]
fuck

**Comment by triplezeta** [comment]
how

**Comment by MarkSuckerberg** [comment]
I'm just gonna merge it directly anyways, *what could go wrong?*

**Comment by triplezeta** [comment]
HEADCODER NO

**Comment by MarkSuckerberg** [comment]
my brain is melting

**Comment by MarkSuckerberg** [comment]
fuck

**Comment by dee-dubya** [comment]
uh oh, stinky

**Pull request closed without merging**
