### PR TITLE
Remove beachbum

### PR DESCRIPTION
**Pull request by ADepressedPyroshark**
## About The Pull Request
REMOVE BEACHBUMS remove beachbums you are worst ruin. you are the ruin idiot you are the ruin smell.
I took the oga route of nuking it from the codebase.
## Why It's Good For The Game
No one goes it and no one likes it. We removed hotel so why not this? This doesn't even have any gamer gear so its pointless to even the powergamers.

## Changelog
:cl:
del: Nukes Beachbums from the time stream
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
good pr, beachbums are a shitty ruin that do nothing but take up precious ruin budget and space.

**Comment by Picklesoup** [comment]
BEGONE BEACH BUM

**Comment by SynnGraffkin** [comment]
I agree beach bum is dumb, but literally just ask @dee-dubya to config it out.

**Comment by Superyodeler** [comment]
Mapping freeze until oldwires, also fixed in config

**Pull request closed without merging**
