### PR TITLE
lizar fire breath for race restricted tator item

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

adds the lizard firebreath DNA injector to the syndicate uplink (restricted to lizard)

basically a somewhat weaker, genetic version of the devil's hellfire spell that (kind of) can't be blocked by the muzzle mask or the krav maga neck chop or other sources of muting afflictions

if you try to shoot it with a muzzle on (or any mask item really), it'll say "something that was blocking your mouth caught on fire" and you'll be set on fire

## Why It's Good For The Game

nothing wrong with adding something to the relatively untouched species restricted section of the uplink

## Changelog
:cl:
adds: firebreath DNA injector to syndicate uplink, cost of 5 telecrystals, species restricted to lizard
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
The fuckin flavor text for this sucks ass

the fuck you mean lizards are ascended from dragons boyo

**Comment by dinnerwoerror** [comment]
you're ass

**Comment by Sparrowbird611** [comment]
I don't know. that's just the flavor text. Don't question the flavor.

**Comment by zeskorion** [comment]
Nah im fine with the pr but the flavor text is arse

**Comment by dinnerwoerror** [comment]
simultaneously says that there's nothing wrong with the PR while also downvoting it

**Comment by zeskorion** [comment]
I hate the flavor text

**Pull request merged**
