### PR TITLE
MiniPacked Station (WIP)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
(Now in a pseudo-permanent state of being testmerged)

Original idea from that one PR on TG that tried to bring back ministation. (Can't link it since the TG main repo is suspended at the moment) I spruced it up a bit, made it look more like a modern map. Toast then proceeded to take the map to where it is now, which is a merge of TG's ministation and VG's packedstation. (a version of old mini)

## Why It's Good For The Game
It's a pretty good map for lowpop, and having different maps from other codebases differentiates us a lot.

image

image

image

## Changelog
:cl:
add: Ministation, a halfway decent map for lowpop rounds. Comes with a TEG!
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
this change log makes me have the idea or impression that something or someone is of questionable, dishonest, or dangerous character or condition

**Comment by MarkSuckerberg** [comment]
me no want to press backspace on phone

**Comment by MarkSuckerberg** [comment]
Will reopen when more progress has been made.

**Comment by MarkSuckerberg** [comment]
[Ministation](https://trello.com/c/4JsQvxEi/13-ministation)

**Comment by SynnGraffkin** [comment]
What even needs to be done?

**Comment by MarkSuckerberg** [comment]
Just needs general improvements, I suppose

Another round of testmerges as well

**Comment by SynnGraffkin** [comment]
Gonna reopen so I can see if I can do something to this.

**Comment by dinnerwoerror** [comment]
haha, stale! like galaxy station!

**Pull request closed without merging**
