### PR TITLE
[DO NOT MERGE] [DNM] [DO NOT TESTMERGE] [DNTM] [WIP] Kiloproooooooooooovements

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

this improves kilo
as of right now this extends some external maintenance airlocks to be two tiles long instead of just one so it's possible to drag stuff into space, as well as nuking a lot of additional decals

This also swaps the sleepers for stasis beds and the stasis bed for a sleeper

## Why It's Good For The Game

i will maintain this map even after i die

## Changelog
:cl:
tweak: kilo
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Map diffs being fucky, can you post some screenshots of changes?

**Comment by triplezeta** [comment]
i think its because the changes i made span the entirety of the station

yeah i can post some diffs later

**Comment by Superyodeler** [comment]
How horny does a moth have to be to react like this to kilo?

**Comment by triplezeta** [comment]
uwu

**Comment by triplezeta** [comment]
shut up stupid bot

**Comment by Superyodeler** [comment]
Requested by @triplezeta

**Pull request closed without merging**
