### PR TITLE
edits some of Quantumm's plumbing sprites

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

this basically just makes the tank and acclimator a little smaller so that its easier to read the ducting when positioned vertically
## Why It's Good For The Game

clarity good

## Changelog
:cl:
tweak: The chemical acclimator and tank have been made slightly shorter to make it easier to tell which way it's facing
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Looking at the Diff bot, is the hot and cold supposed to have a single white pixel blinking in the top left?

**Comment by triplezeta** [comment]
FUCK

**Comment by triplezeta** [comment]
These stray pixels aren't showing up on my .dmi. Weird.

**Comment by triplezeta** [comment]
image
icondiff is drunk

**Comment by Maldaris** [comment]
Where was this a week ago when I went on my chemfactory meth-making spree?

**Pull request merged**
