### PR TITLE
makes regen jelly mixable with omnizine, soft-nerfs the tricord regen jelly recipe

### LINKED ISSUE #459: Can't make regen jelly
Issue reported from  Round ID: [1616](https://scrubby.melonmesa.com/round/1616) (BoomerStation - MRP)

Reporting client version: 513.1528

Basically, The chemical recipe for regen jelly (1u omnzine and slime jelly) doesn't work and can't be made
I'm unshure if this is a bug since the wiki doesn't have the recipe but I don't remember any pr saying you can't make it anymore so i'm putting this here just incase

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

closes #459 
makes omnizine + slime jelly produce regen jelly again
changes the current regen jelly recipe to be tetracord + slime jelly and produces 1 unit instead of 2 

## Why It's Good For The Game

uhh

## Changelog
:cl:
balance: tetracord + slime jelly produces one unit regen jelly instead of two
fix: regen jelly is mixable with omnizine and slime jelly again
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
oh yeah while I'm here I should take this opportunity to be based and epic again and slap on a bunch of unatomized chem changes because I'm

**Comment by ADepressedPyroshark** [comment]
> 
> 
> oh yeah while I'm here I should take this opportunity to be based and epic again and slap on a bunch of unatomized chem changes because I'm

do it you won't

**Comment by Superyodeler** [comment]
Don't do it, please

**Comment by triplezeta** [comment]
fine

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
