### PR TITLE
Felinids can't eat chocolate again

### PR DESCRIPTION
**Pull request by AsciiSquid**
## About The Pull Request
Makes it so felinids suffer sickness and organ damage by eating chocolate similar to how it once was on /tg/. Values and effects have been slightly adjusted compared to the original to make it less damaging and more annoying.
Shoutout to @GuyonBroadway for the original [coco food poisoning code](https://github.com/tgstation/tgstation/pull/46238).

## Why It's Good For The Game
Haha chocolate cat go huuurg.

## Changelog
:cl:
balance: felinids have adverse reactions to chocolate now, oh no
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
i do not approve of cocoa based terrorist attacks

**Comment by MarkSuckerberg** [comment]
good

**Comment by TheObserver-sys** [comment]
I feel like this is going to be shitter bait more than anything else. TG got rid of it in part because of it just causing headaches for everyone involved, I'm not sure exhuming this particular dead meme is a good idea.

**Comment by MarkSuckerberg** [comment]
I... wish I didn't kind of agree with this point. It's funny, but it might not be worth drudging up old hate for /tg/ for ourselves. This ~~somehow~~ requires further discussion, so I"m just going to put a DNM for now.

**Comment by AsciiSquid** [comment]
In defense of this, we aren't tg.

Squidpeople have had negative reactions to salt for the longest time with little to no issue, despite it effectively meaning saltshakers or potato chips are public access hardstuns. Additionally this nerfed version of poisoning isn't as lethal (however switching from organ damage to toxin damage might be a better balance fix than just lowering the numbers)

Secondly this is a partial counterbalance for felinids immunity to carpotoxin on the code currently.

**Comment by triplezeta** [comment]
carpotoxin isnt even that good of a poison though.........

I'm overall neutral to this change, but I'd need to see how it plays out in an actual round to form a better opinion. When this was merged on TG, people intentionally poisoned food with chocolate because "muh felinids" and emptied out snack vendors so felinids would either have to starve or eat the poisoned food.

**Comment by triplezeta** [comment]
As an alternative, we could look at finding other ways to modify the felinid diet that doesn't happen to be making chocolate toxic to them.

**Comment by dinnerwoerror** [comment]
gcat

**Comment by AsciiSquid** [comment]
I could let them eat rats so they can sidestep the chef the same way the lizards do with their glucose intolerance.

**Comment by dee-dubya** [comment]
alternatively, instead of coding out interesting interactions because of shitmins not doing their job(the /tg/ solution), how about we just ban the shitters that forcefeed cats cocoa

**Comment by AsciiSquid** [comment]
I'm considering making this even weaker so it's more inline with bad food reactions over being an actual toxin.

I just like species diversity and this was preexisting code which achieved that. Even if the original implementation got abused to shit.

**Comment by triplezeta** [comment]
As a suggestion, you could cap the organ damage that cocoa does and lower the stamina damage.

**Comment by TheNeoGamer42** [comment]
holy shit I forgot this PR existed, nice

**Pull request closed without merging**
