### PR TITLE
Revenant can READ!

### PR DESCRIPTION
**Pull request by Epsilos**
## About The Pull Request

Previously, most of revenant's text (anything that doesn't reveal you immediately) was something close to black. This is, obviously, not a good idea for dark mode, unless you've had years of training as an alien with no nightvision.

The text color has been changed to a dark purple, making it actually legible. It's also stilldarker than the more danger-alerting text colors Rev has, allowing differentiation in how bad a situation is.

## Why It's Good For The Game

I like to see.

## Changelog
:cl: Epsil
tweak: you can now see ALL the text that revenant shows you. no more black wit a little blue on dark mode.
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
qaStaHvIS ram puS Do'qu' jIH

🏴󠁧󠁢󠁷󠁬󠁳󠁿

**Comment by dinnerwoerror** [comment]
alien with no night vision my ass

**Comment by Epsilos** [comment]
only NTstation boomers remember

**Comment by MarkSuckerberg** [comment]
Merging as it's a small change and if (for some weird reason) people don't like it, it can be changed back quickly.

**Pull request merged**
