### PR TITLE
Kiloproovements

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

this improves Kilo, allegedly. 
I will add a full writeup of all of the major changes to Kilo, along with screenshots once I am finished, which should be soon.

## Why It's Good For The Game

if you want kilo to go unmaintained you will have to send at least 5 bitcoin assassins after me 

## Changelog
:cl:
add: Kilo has public mining, as god intended
del: the checkerboarding in kilo's medbay is gone
del: some stray tape bits that were left behind have been sent to caution tape hell
tweak: Kilo's brig infirmary now violates the Geneva convention
tweak: MEGABAR
fix: many kilo APCs that were not wired at roundstart are now wired at roundstart
fix: CE has his monitor decryption key again on Kilo
fix: fax machines are on kilo now
fix: the phantom wall mechas on kilo are gone
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I'll make it 6, just to be safe.

**Comment by TheNeoGamer42** [comment]
what about a bitcoin ICBM with a bright ass lamp taped to the front so you stand there and look at it while it comes towards you about to blow your ass up

**Comment by triplezeta** [comment]
if you can actually afford one

**Comment by triplezeta** [comment]
ok lets start this from the top:
gigachad bar
image
surgery observation deck ( yes its built into the break room ) 
image
ai upload
image
lawyer office, courtroom 
image
all of security
image
outside of engineering
image
also engi foyer
image

**Comment by Baldir-Odensen** [comment]
If you replace all the parts of a station. Is it still the same station

**Comment by triplezeta** [comment]
Yes.

**Comment by Baldir-Odensen** [comment]
Do you the destroyer of soul suggest that kilo has soul?

**Comment by triplezeta** [comment]
ye

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by triplezeta** [comment]
pog

**Pull request merged**
