### PR TITLE
[Port] Jukebox rework + environment/reverb controls for sounds played via playsound_local

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Source PRs
[Jukebox rework + environment/reverb controls for sounds played via playsound_local #7367](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7367)
[Buffs jukeboxes - gives music played by jukeboxes double the falloff #7458](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7458)
[Fixes jukeboxes not exiting the active jukebox list when destroyed #7604](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7604)
[Changes Jukebox Availability #7905](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7905)
[Makes jukeboxes work again after 512.1459's changes to SOUND_UPDATE (and other small fixes/tweaks) #9616](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9616)
Various runtime fixes by Ghommie

## Why It's Good For The Game

Makes the Jukebox actually work and functions much better. Also adds a reverb effect to things use playsound_local, such as the jukebox and station alerts.

[Video of it working](https://streamable.com/dwrv6y)

Also, for Headmins / anyone messing with config, sound names must be in the format of [song name]+[length in deciseconds]+[beat in deciseconds]+[associated ID].ogg, and I kept the file I used in to be an example.

Jukeboxes are now purchaseable in Cargo as well for $35,000 and the access requirements for jukeboxes were extended to Botany, Kitchen, Engineering, Theater, and Cargo.

## Changelog
:cl: deathride58
add: Jukeboxes now have realtime directional audio, complete with occlusion when you're far away or behind a wall.
add: More than one jukebox can play a song at a time now. Have up to 5 jukeboxes playing at once!
add: Devs can now control the wet and dry channels of sounds played via playsound_local. The new envwet and envdry arguments will control the volume of the wet and dry track, respectively.
code: Jukeboxes have been turned into a subsystem. Track initialization, audio playing, etc, are now handled via SSJukeboxes instead of via the jukebox object procs.
config: Jukebox tracks now require an additional ID field at the end of their name. This will make it easier to add jukebox-style objects that are only capable of playing specific songs, without worrying about copyright issues.
balance: The jukebox now falls off over a greater distance. You can now actually hear the jukebox while sitting in a far corner of the bar, or while passing through the main hallways.
fix: Jukeboxes now properly remove themselves from the active jukebox list when destroyed
tweak: Jukeboxes now have 6 audio channels available to them, up from the previous accidental 2 and previously intended 5 channels.
fix: Jukeboxes now work again on clients running versions higher than 512.1459.
fix: People will no longer have their ears consumed by an eldritch god if multiple jukeboxes are active and the first jukebox in the jukebox list stops playing, then tries to play again
tweak: Instead of the debug text for invalid jukebox behavior being printed to world, the debug text is now restricted to the runtime panel.
add: Jukeboxes can be purchased from Cargo for $35,000. By Ignari-Coldstorm
balance: More jobs can now interact with the Jukebox's playlist! Kitchen, Botany, Cargo, Engineering, and Theater access can now modify the jukebox instead of just bartender access. By Ignari-Coldstorm
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
@Superyodeler The sound folder already exists though. I just deleted the exclude in it.

**Comment by Superyodeler** [comment]
The folder didn't show up for me, and the jukebox didn't work until I created a sounds folder and put the .ogg in it.

**Comment by SynnGraffkin** [comment]
Weird, because the folder was there by default. I just have the .ogg in the base jukebox config folder because I had one both IN and OUT of the sound folder during my testing, since Yog / Cit don't have a sound folder by default, but I assume theirs on live does.

**Comment by SynnGraffkin** [comment]
It ain't stale ye dumb bot

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
