### PR TITLE
TGUI Upgrades and new UI features

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Multiple new TG UI features and backend ports. Doing this small so it doesn't cause major conflicts. Original TG PRs listed on commits where applicable.

## Changelog
:cl:
add: TGchat, replacing goonchat
add: Browser stat console, which reduces the lag caused from the classic panel immensely
add: Photocopier and shuttle UI
tweak: Fax UI has been overhauled
code: Numerous TGUI upgrades to make life easier for TGUI development and use
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
image
relevant screenshot

**Comment by triplezeta** [comment]
where's the sleeper UI..............

**Comment by Superyodeler** [comment]
This is from TG, so prob no sleeper

**Comment by Superyodeler** [comment]
HAHA, funny weed number XD

**Comment by Maldaris** [comment]
This has baked awhile in test merge, is there anything still todo here?

**Comment by Superyodeler** [comment]
The file conflict needs to be fixed, but other than that I think it's good to go.

**Comment by Maldaris** [comment]
> The file conflict needs to be fixed, but other than that I think it's good to go.

on closer inspection it looks like #424 and #437 are still valid. #437 is mission critical.

**Pull request merged**
