### PR TITLE
Sleeper power cells

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
image

Adds a cell to sleepers to draw power from. Cell is fully upgradable, and power usage efficiency is as well. Also updates the TGUI to include the current power.

## Why It's Good For The Game
No more completely unrealistic and more or less broken sleepers producing infinite reagents.

## Changelog
:cl:
tweak: Sleepers now draw from an internal power cell instead of producing chems infinitely out of thin air.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
there was a whole lot of undocumented changes in this PR to access on jobs lmao

**Comment by triplezeta** [comment]
bottom text

**Comment by FancyCyclops** [comment]
bruh momento

**Comment by MarkSuckerberg** [comment]
Seems to have accumulated changes from #51 somehow

**Comment by dinnerwoerror** [comment]
nah bro it's just because genetics was never meant to be part of science

**Comment by Iamgoofball** [comment]
borrowed this PR for beestation, thanks

**Pull request merged**
