### PR TITLE
Alt Clothing Part 1

### PR DESCRIPTION
**Pull request by Quantum-M**
## About The Pull Request

Adds different clothing, mainly jumpsuits, to several alt jobs, mostly medbay, science, and most of engineering. Some additional coats and ties were also included, along with outfit datums for said alts.
image
_Mostly alt jumpsuits shown_

## Why It's Good For The Game

Makes each alt job stand more instead of it being largely fluff.

## Changelog
:cl: Quantum-M
add: Adds several alt jumpsuits, ties, and coats to Medical, Science, and most of Engineering alt jobs, along with relevant datums.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
The clothing datums should be under the actual job file. 
```c
/datum/outfit/job/engineer/maintenancetechnician

**Comment by MarkSuckerberg** [comment]
Either work fine,  I had just put the alternate uniform datums in the respective job files because at that point nothing was really modularized in them. Conpletely your call if you wanna move them or not

**Comment by SynnGraffkin** [comment]
It's where the rest of the outfit datums are for each job, so it makes sense for them to be there.

**Comment by Quantum-M** [comment]
Moved the outfit datum to the relevant jobs, @SynnGraffkin

**Pull request merged**
