### PR TITLE
deletes lag

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
rebases to nocode, cant lag if theres no code (mark please don't kill me over this joke PR)
## Why It's Good For The Game
lag bad
## Changelog
:cl:
del: deleted lag
fix: fixed lag
refactor: rebased to nocode
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
moment

**Comment by dee-dubya** [comment]
>−2,663,762

ah yes we're taking the /tg/ method of code improvement

**Comment by TheNeoGamer42** [comment]
it cant lag if theres nothing to lag

**Comment by TheNeoGamer42** [comment]
I wonder if theres a way I can ADD lag

**Pull request closed without merging**
