### PR TITLE
Baytiles [okay maybe testmerge]

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
This is a draft PR just to see if the code passes checks and stays mergable. **DO NOT MERGE** this until I can give the full, deserved credit to the baystation spriters who made this.

Credit mostly to this PR and it's author CakeQ: Baystation12/Baystation12#21935, which is where most of the sprites came from. Also credit to these PRs and multiple others that I can't seem to find for the decals. Baystation12/Baystation12#10749, Baystation12/Baystation12#10275

## Why It's Good For The Game
It's a large change of style, and one I think would diversify us more from /tg/.

## Screenshots

<details>
  <summary>Expand</summary>

  image
wew
image
image

</details>

## Changelog
:cl:
add: Added new tiles, including more patterns as well as the addition of monotiles.
del: Painted floortile turfs are now GONE. Sorry lads who like em, but it was either they go or all the decals go.
add: Added a whole load of new decals from Bay.
code: dark/normal/light floortiles now are coloured by colour vars instead of coloured sprites.
imageadd: Floortiles now use Bay12 sprites.
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
I like it, they look good but not too noisy.

**Comment by triplezeta** [comment]
can we merge already

**Comment by dinnerwoerror** [comment]
yea but it says to not merge

**Comment by Maldaris** [comment]
Have we even testmerged this?

**Comment by dinnerwoerror** [comment]
we have, actually

**Comment by MarkSuckerberg** [comment]
Updated, all bugs (that I currently remember) are fixed. Added Citadel-Station-13/Citadel-Station-13#12388 since it allegedly decreases memory usage by decals, which there are a lot more of now. Probably ready for another testmerge.

**Comment by triplezeta** [comment]
the king is back

**Comment by MarkSuckerberg** [comment]
I wanna test merge for this eventually

**Comment by MarkSuckerberg** [comment]
Maybe some other time.

**Pull request closed without merging**
