### PR TITLE
drink resprites 2 electric boogaloo, 10 PM edition

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
replaces like a few sprites, the wine glass by terg, the sugar rush, the crevice spike, the fringe weaver, and the wizz fizz done by bunzel, and THEN the martini, and the allies cocktail, driest martini, goldschlager, patron, fanciulli, manhattan, project manhatten, devilskiss, and the rubberneck by triplezeta
## Why It's Good For The Game
new sprites good
## Changelog
:cl:
imageadd: New wineglass sprite by Tergius, and Sugar Rush, Crevice Spike, Fringe Weaver, and Wizz Fizz sprites by Bunzel, and once again the Allies Cocktail, the Martini, driest martini, goldschlager, patron, fanciulli, manhattan, project manhatten, devilskiss, and the rubberneck by TripleZeta
imagedel: a shitton of old drink sprites but only in the modularized folder
/:cl:

### CODE REVIEW

**Comment by rabbetbunzel** [comment]
ah yes funny spicy water

**Comment by TheNeoGamer42** [comment]
isn't spicy water just acid or pepperspray

**Comment by dinnerwoerror** [comment]
i swear on the lord i JUST updated the images in the wiki earlier today

**Review by triplezeta — APPROVED** [review]
based

**Review by Superyodeler — APPROVED** [review]

**Comment by TheNeoGamer42** [comment]
*scream

**Comment by TheNeoGamer42** [comment]
mmmmmmm PR merged, time to make another PR whenever zeta throws 50 sprites at me or some shit again, or terg, or bunzel.

**Pull request merged**
