### PR TITLE
Improves lowpop map rotation

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Makes the map voter only remember this map and the one before it. As a result, maps should only be excluded from votes if they are run twice in a row.

## Why It's Good For The Game

More democracy.

## Changelog
:cl:
tweak: persistance controller only remembers 1 round (plus the current) for the purposes of map votes
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
D E M O C R A C Y

**Comment by Maldaris** [comment]
Does this mean democracy in the sense that we have a choice?

**Comment by dee-dubya** [comment]
Does this axe oranges' anti-metastation mechanism as well?

**Comment by Superyodeler** [comment]
No, I haven't heard of that one. Can you post the PR?

**Comment by SynnGraffkin** [comment]
Knowing Orange, probably no PR for it. I thought that was this PR because TG is always on Meta and this would have stopped it from always being meta.

**Pull request merged**
