### PR TITLE
Adds Flavourtext (someone end me)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Adds flavortext from cit. I could not find the original PR that added it after searching for about half an hour, so I'm just going to vaguely point at citadel for the code, which is where I got it from. If someone wants to claim credit for it, just ask and I'll be happy to add credit for you.

*ahem*

image
image
image
this image does not represent my feelings towards the subject in any way

## Why It's Good For The Game
Some people have been asking about it a lot, and it's not too difficult of a feature to add. It could be more modularized, I suppose, but it's such a small feature that if the need arises, I'll modularize it from there.

## Changelog
:cl:
add: Flavortext can now be set, to be shown to anyone who examines you.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
[Flavour Text](https://trello.com/c/emJ5SSO2/6-flavour-text)

**Comment by dinnerwoerror** [comment]
will i be able to have this as my flavor text

**Comment by MarkSuckerberg** [comment]
I despise you

**Comment by triplezeta** [comment]
he'll find a way to do it

**Comment by MarkSuckerberg** [comment]
the scary part is I think he will

**Comment by dinnerwoerror** [comment]
i happen to be forced to contend with an execrate of your presence

**Comment by triplezeta** [comment]
that's one of the trello board cards done

**Comment by Superyodeler** [comment]
Rate my flavortext

AssistantFlavorText

**Comment by dinnerwoerror** [comment]
b orb

**Pull request merged**
