### PR TITLE
Tool Resprites (Take II) By TripleZeta

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Resprites the previously resprited tools, plus adds a few more redone icons. Also adds on-belt sprites because that's nice. (Apologies for low quality PR, it's lat- er, early in the morning and I need to sleep)

image
image

(will get comparison photo if actually needed)

## Why It's Good For The Game
removes even more soul

## Changelog
:cl: TripleZeta
imageadd: New tool sprites (basic tools, power tools, analyzer, geiger counter, tray)
imagedel: Old tool sprites (duh)
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
NuTools
here's what everything looks like

**Comment by TheNeoGamer42** [comment]
did ye do the funny toolbelt sprits too

**Comment by triplezeta** [comment]
look at the checks????





the answer is yes

**Comment by TheNeoGamer42** [comment]
e

**Comment by Maldaris** [comment]
Wirecutters look like shears or boltcutters more than they look like wirecutters.

For reference wirecutters often have less round portions, or if they do, they're short cutting surfaces: 
image

**Comment by triplezeta** [comment]
Fixed already, due to feedback from Sabringer 

Example syndi wirecutters here
image

**Comment by triplezeta** [comment]
well... wirecrimps. Which is what the original and first resprited version were based off of.

**Comment by triplezeta** [comment]
not again

**Comment by triplezeta** [comment]
NuTools
updated spritesheet

**Comment by SynnGraffkin** [comment]
T-Ray scanners are invisible when in use.

**Comment by triplezeta** [comment]
nuke screwdriver still uses the oldsprite
he;[

**Comment by triplezeta** [comment]
geiger counter still uses old inhands

**Comment by triplezeta** [comment]
I....... 

may not have done new inhands for the tools other than the geiger

oops

**Comment by triplezeta** [comment]
stop it you bot

**Comment by SynnGraffkin** [comment]
Were miniwelders supposed to not have a weld on? 
image

**Comment by triplezeta** [comment]
the jaws of life using old inhands is intentional ~~because I didn't do new ones~~

MAAAAAAARK THE GEIGER INHANDS AREN'T WORKING

**Pull request merged**
