### PR TITLE
MidwayStation

### PR DESCRIPTION
**Pull request by Vorak2**
## About The Pull Request
This adds midwaystation a map I have been working on for a while and is now finished ish. main engine is not entirely working but I am not confortable enough with other engines to remake it. I have not yet done whiteship or an escape shuttle but I feel that it isnt entirely necesary to finish those before anny tests.
I also need to limit the amount of jobslots on multiple jobs

## Why It's Good For The Game
Midway is a map made for lowpop wich is what we mostly have around here so having a map made to be used on smaller crews is good

## Changelog
:cl:
add: Adds midwaystation as a playable map

/:cl:

### CODE REVIEW

**Comment by Vorak2** [comment]
image
This is the station with area overlay
image
Without area overlays

**Comment by dinnerwoerror** [comment]
if we honest-to-god keep kilo station around i think we can consider this

**Comment by Vorak2** [comment]
@dinnerwoerror I saw later that you had a lot of complaints about the cameras. can you tell me in witch areas the lacking coverege was so I can fix it. I have fixed it in genteics already but other than that I will try to find and do tomorow

**Comment by dinnerwoerror** [comment]
it's really just weird things regarding room security in general

telecoms and the gravity generator are adjacent to a main maintenance area, 1 camera with no motion sensor in telecoms, no cameras in grav gen, adequate security by my standards if you ask me, especially for the 3rd and 4th most sensitive areas on the station (right below the 2nd place armory and the 1st place AI sat)

there's only 4 ways into the bridge and they can all really easily be blocked off, one is through space, one is through the AI sat, one is through the HoP office which has toggleable shutters, and one is the front door that has blast doors although no button to open or close them seemingly enough

by that measure, the bridge is literally more secure than tcomms and the grav gen

the main medbay area is a really long hallway with the sleepers and cryo and stasis beds all kind of just parked up alongside the wall, and also apparently medbay has no APC but that's not really that important

in the security execution room, the vent there has its pressure regulator turned off, so it's just set to pressurize the room endlessly, which is like a clown tier prank, i think you should keep that in

there's no lights or cameras in the pbrig

in fact, you should just proofread security camera coverage in general, remember that despite the name, security cameras are designed with the AI in mind, not security in mind, since the cameras are the AI's eyes, so there should be cameras all about 5 to 10 tiles apart from each other (view range is 7 tiles), as well as maybe an extra camera or two in certain sensitive areas for redundancy

when the arrivals shuttle docks there's just a random chance of the entire arrivals dock depressurizing and shooting out all the air, somehow

i donno what it is with the recent trend of the teg being made the primary power source on newer maps, but i'm probably too security to understand this so it's beyond me
i guess i just feel like it's _too_ safe, since there's pretty much zero chance of a catastrophic malfunction apart from deliberate sabotage, like how there's always that one incompetent engineer who forgets to set the scrubbers to siphon or forgets about the gas filters, or something like that, so the supermatter starts blowing up
there's no real overarching risk with the teg, despite the fact that the teg and the sm share the same concept of moving hot gas out and moving cold gas in

tomorrow is the 1 month anniversary of me being banned from the discord and not being able to report any of this into the bug reports channel

**Comment by dinnerwoerror** [comment]
also, i think the ventilation in the toxins mixing chamber is the wrong way around, the injector is supposed to input the gas while the air scrubber is supposed to output it, but the pipes and the pumps suggest that it's the other way around

**Comment by Vorak2** [comment]
I think I have fixed some of the camera issues and added an extra camera to perma. among other things.
None of the maps I used for reference has motion sensors in Tellecoms wich is why I dont have it eather. though the fact they dont might be questionable.
gravgen now as its cameras though not montion sensor becouse of the reson stated earlier. and I dont recon they are a lot more exposed to danger than those same facilities are on other maps. and you can secure both of them by securing a single maint room

**Comment by Vorak2** [comment]
image
The bridge shutters are closed by the button on the table in the middle of the bridge

**Comment by Vorak2** [comment]
I created a small medical maonitoring thing to break it upp a little hope this inproves things
image

**Review by Maldaris — APPROVED** [review]
This has been un-testmerged in favor of other stations, but it's in good shape. Further fixes can come out of other PRs. If nobody objects before about 6pm EST tonight I'm merging this.

**Comment by dinnerwoerror** [comment]
i donno why, but i kind of just feel like it _feels_ too large

mini packed station has the advantage of basically just being a remaster of an actually good map and galaxy station kind of cheats by having half of the main on the second floor

meanwhile this place just feels off with its 5 tile wide hallways and intersection in the center (where the medbay lobby and the bar is) that makes it feel like a mall

**Comment by Maldaris** [comment]
> meanwhile this place just feels off with its 5 tile wide hallways and intersection in the center (where the medbay lobby and the bar is) that makes it feel like a mall
Personally think this is where the appeal lies, the design is definitely a departure from traditional stations, and has that 90s mall vibe that I think honestly isn't played up _enough_.

compared to the other stations we're adding I can see the criticism but I don't think it's actually functionally much larger than box or meta.

**Comment by dinnerwoerror** [comment]
exactly, it's kind of the same thing as with mini packed but the opposite, where when i first saw mini packed i noticed how there's an ass ton of maintenance and it's all focused around the starboard side of the station, to the point that this map is probably about as large as pubby station, but the actually relevant bits (the departments) are what you see 85% of the time, which is why the map feels small

**Comment by Vorak2** [comment]
Ok so with the general layout I was partially going for it being a transit point something similar to an airport in a way where you get people in on one side and they exit on the other.
 And with the central area I was kindof going for a plaza though I admit it might be a bit big and I have some ideas for minor reworks of that that came upp when I made the podtrack.

As for the size when I measured it and if you put this station put it in a box it is about 150x130 or something close to that witch is about 50 tiles smaller than box on both axis and I think actualy a similar size as mini. Though I am not shure of the area footprint of mini so with that I am not shure.

With maint I am not realy shure I am following you as I think maint on this map might be a bit small so much that I was actualy considering adding a separate Zlevel for maint transport corridors as most departments have fewer than recommended exits. Though the maint I have probably feels bigger becouse it is more inbetween departments than other stations so it breaks upp camera vision more than usual stations

**Comment by dinnerwoerror** [comment]
that's the thing, it doesn't have to actually be large or small, it just has to feel large or small

there were about 1,550 miles of trenches dug during the great war, yet many reports of them complain of how **small and cramped** they were, because they were dug to certain **small and cramped specifications**, about 5 feet wide and 6 feet deep, as well as with an embankment on the top and played out in a zig zag pattern

**Comment by Baldir-Odensen** [comment]
One of the positives I felt playing midway was that it had a unique feeling to it.

Like it felt both claustrophobic and open at the same time in a very strange and interesting kind of way.

**Pull request merged**
