### PR TITLE
adds some marketable plushies

### PR DESCRIPTION
**Pull request by triplezeta**
spritercode

## About The Pull Request

This adds two new plushes that bear a strong resemblance to the Knight and Hornet from Hollow Knight. They can be bought from the loadout for 2000 metacoins each.
EDIT: i added a lesbian pride hornet plush too for 6969 metacoins
EDIT 2: i should mention that the original hornet plush is made by tiramisu
image
image

## Why It's Good For The Game

shaw

## Changelog
:cl: tiramisuapimancer & triplezeta
add: marketable plushes
/:cl:

**Edit by @Superyodeler: improved changelog**

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
bubge

**Comment by triplezeta** [comment]
image

gay hornet plush has been added for 6969 metacoins

**Review by MarkSuckerberg — APPROVED** [review]
dying

**Comment by AsciiSquid** [comment]
This will not save you from #518

**Review by Superyodeler — CHANGES_REQUESTED** [review]
Hornet isn't void

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
