### PR TITLE
Paranerf

### PR DESCRIPTION
**Pull request by Superyodeler**
Moving this here for now.

## About The Pull Request

Reduces paramedic access, especially to non-medical departments.
Parameds lose access to: the engine, cargo, hydroponics, and research.
In addition, EVA access is restricted to skeleton crew.

## Why It's Good For The Game

Currently paramedics have an extreme level of access, allowing them to tide large parts of the station and get valuable gear without hacking. With this pr the main access benefit of picking paramedic over doctor is getting maint access over surgery access.
I've left EVA as a skeleton crew option in case they need to get someone out of space when there is no one to allow them to grab a suit.

## Changelog
:cl:
balance: reduced paramed access
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
If we want Paramed to be the most bare bones in terms of access for what they do, consider the way VG has their access. 
```c
	access = list(access_paramedic, access_medical, access_sec_doors, access_maint_tunnels, access_external_airlocks, access_eva, access_morgue, access_surgery)
	minimal_access=list(access_paramedic, access_medical, access_sec_doors, access_maint_tunnels, access_external_airlocks, access_eva, access_morgue, access_surgery)
```

When I get to mapping Paramed offices, I will make the associated access / area for them.

**Comment by Superyodeler** [comment]
I don't really want to give parameds sec or surgery access. Sec because that should be more secure, and surgery because I think that would make them too much of an upgrade to doctors.

**Comment by SynnGraffkin** [comment]
Taking into context that they don't have genetics (cloning) or Viro access like VG doctors, it isn't that much of a trade off they get surgery. 
```c
	access = list(access_medical, access_morgue, access_surgery, access_chemistry, access_virology, access_genetics, access_eva)
	minimal_access = list(access_medical, access_morgue, access_surgery, access_virology)
```

That's Doctors there. We have Brig Phys, so Parameds don't "need" brig access.

**Comment by Superyodeler** [comment]
Our MDs don't have access to viro at all. I looked at vg's virologists and they seem to have "access_biohazard" not sure what that's for.
I bring this up because this is the only thing that VG MDs have that parameds don't on mini access.
Also, paramedics in our code and in my nerf have access to cloning in both skeleton and minimal access.

**Comment by SynnGraffkin** [comment]
Looking at VG access, /var/const/access_biohazard = 69 // Virology crates is just that, instead of CMO access for crates.

**Review by SynnGraffkin — CHANGES_REQUESTED** [review]
I would heavily suggest EVA access being on minimal access as a benefit of picking Paramed over other medical staff.

**Comment by Superyodeler** [comment]
Gave the paramedic EVA access back

**Review by SynnGraffkin — APPROVED** [review]
Looks good.

**Pull request merged**
