### PR TITLE
Strike the Earth!

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
On the 21st of Hematite, the Lavaland Dwarves settled in WaspStation.

## Why It's Good For The Game
It was inevitable.

## Changelog
:cl:
add: Added Dwarves and their language
tweak: Made it so dwarves are not forced to be drunk to communicate properly.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
LETS FUCKING GOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Maldaris** [comment]
Is this a /tg/ port or from somewhere else?

**Comment by DerFlammenwerfer** [comment]
> Is this a /tg/ port or from somewhere else?

I ported it from skyrats. There's no furfag stuff in it, just a change that lets them have human bloodtypes

**Comment by Maldaris** [comment]
Okay then put these new files in the `waspstation` folder, and update your imports in the .dme file. Attempting to keep new shit and ports out of the main files makes maintaining our own code easier.

**Comment by DerFlammenwerfer** [comment]
Sure fam

**Comment by MarkSuckerberg** [comment]
YOU PEOPLE ALWAYS MAKING ME KNOCK OVER MY GLASS OF ORANGE JUICE AAAAAAAAAARGH

**Comment by Superyodeler** [comment]
Oragne juic bad

**Comment by TheNeoGamer42** [comment]
as a person who barely played dwarf fortress and has no clue how to watch it, but has watched it and found it to be an enjoyable to watch and probably would be enjoyable to play if I was to put in the effort to learn it, yes

**Pull request closed without merging**
