### PR TITLE
the gender wage gap

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

females only get paid 70% as much as men

this is exactly what it sounds like

i hope you don't doubt me, dee

## Why It's Good For The Game

20th century realism is what we're all about

i am the hero that this station deserves but doesn't need

we'll see where this goes and whether i want to follow up on this

## Changelog
:cl:
balance: because women already hold all influence among the station simps they are being punished by only getting paid partially as much from now on
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Joke PR.

**Comment by dinnerwoerror** [comment]
no no, i'm deathly serious

**Comment by SynnGraffkin** [comment]
20th century "realism" is what got Cobbymed in 255X

**Comment by dinnerwoerror** [comment]
20th century realism is where it is more economically profitable to compete in a women's workplace as a male, deliberately registered and labelled as a woman

**Comment by Sparrowbird611** [comment]
Bruh..... what.

**Comment by Picklesoup** [comment]
the female character metagang will just get their simps to steal everyone else's payday via the station budget, bad PR

**Comment by dinnerwoerror** [comment]
ok, pickle wickle, think of it like the Vorkuta plan

step 1: secure the keys

not everything can be made in one grand pull request

**Comment by Sparrowbird611** [comment]
Ok but like, unrelated to that.

The only reason I see for this is "realism" in funny spess man game where I can tank bullets and stab myself with funni miner pen for super heals while fighting a wizard and a traitor who can deflect bullets with his bare hands.

**Comment by dinnerwoerror** [comment]
see? realism

**Comment by Sparrowbird611** [comment]
Ok my mind is changed, this makes perfect sense.

~~Jokes aside though, I don't see a point to this, and unless your plan also involves changing the lore, and restricting females from head positions, I don't see the point.~~

**Comment by dinnerwoerror** [comment]
it doesnt have to have a point

**Comment by Maldaris** [comment]
Hah. No.

**Comment by MarkSuckerberg** [comment]
someone pinch me

**Comment by dee-dubya** [comment]
he actually did it the madman

**Comment by dinnerwoerror** [comment]
there was an attempt

**Pull request closed without merging**
