### PR TITLE
new pwasma meme enviwo soots: only partially latex

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

new plasmaman envirosuits for the brig physician and the heads

my mum said they looked very nice and matched well so please like them and match well also

Screenshot (576)

Screenshot (575)

## Why It's Good For The Game

im not doing this for cyclo
im not doing this for morg
im not doing this for zeta
im not doing this for bitey solly
im not doing this for a depwessed pywo shark
im not doing this for the server
im doing this for me

because i am the only one who will be benefiting from this

## Changelog
:cl:
adds: plasmaman command envirosuits
adds: a new brig physician envirosuit
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
ok im really sorry for speaking in owospeak, it's 11:15 at night and im eating fucking cocoa pebbles cereal

**Comment by dee-dubya** [comment]
non-human heads were a mistake and I hate that you made me do it

**Comment by dinnerwoerror** [comment]
i am inevitable

**Comment by MarkSuckerberg** [comment]
i'm scared

**Comment by dinnerwoerror** [comment]
you better smack your chest like a primate at least once when you're in the process of making a branch for a pull request

**Pull request merged**
