### PR TITLE
Removes swarmers

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
Removes the swarmer ruin. Also deletes the swarmer ruin file to make sure they are extra gone

## Why It's Good For The Game
Literally nobody likes the swarmer ruin.

## Changelog
:cl:
del: Swarmers and their bullshit ruin are now banished to the shadow realm
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
finally, these pieces of shit are gone from existence.

**Comment by dinnerwoerror** [comment]
to be fair, we could just remove lavaland

literally nobody on the station likes the 2016 era wild west that is lavaland balance

**Comment by DerFlammenwerfer** [comment]
> to be fair, we could just remove lavaland
> 
> literally nobody on the station likes the 2016 era wild west that is lavaland balance

I like it, but there needs to be more things for the miners to do than just fight megafauna

**Comment by MarkSuckerberg** [comment]
[Removes/changes swarmers on Lavaland](https://trello.com/c/00tFMgBg/49-removes-changes-swarmers-on-lavaland)

**Comment by MarkSuckerberg** [comment]
I'm in favor of this, since they really don't do much but be annoying. Usually by the time someone arrives and finds them, they've already taken over half of lavaland.

**Comment by triplezeta** [comment]
the only time I was able to successfully take these fuckers out was as a golem on a scooter with a 600 unit meth bomb

**Comment by SynnGraffkin** [comment]
I would suggest just removing the ability for the ruin to spawn, thus allowing admemes to still force the ruin if need be.

**Comment by dinnerwoerror** [comment]
what kind of admin would want to force this antiquated version of blob

**Comment by SynnGraffkin** [comment]
Could be useful for an event if we ever had consistent pop above 20

**Comment by DerFlammenwerfer** [comment]
>if need be.

No admin should ever need to spawn this ruin.

**Comment by dinnerwoerror** [comment]
don't we have actual swarmers instead of these bullshit simplemobs

**Comment by SynnGraffkin** [comment]
I haven't seen the event for swarmers ever pop up here, but that probably has a pop requirement.

**Comment by dee-dubya** [comment]
We do have actual player controlled swarmers, yes.

I agree with the notion that just removing its spawn while keeping the ruin would be ideal, but I also don't see a situation where an admin would ever need or want to spawn this ruin.

**Comment by MarkSuckerberg** [comment]
It's a bit of a summon events situation. Having the option there would be *somewhat* more optimal, but nobody would or should ever use it, so there's really no point keeping it in.

**Comment by dinnerwoerror** [comment]
please do not fall victim to rosy retrospection and sunken costs

**Comment by MarkSuckerberg** [comment]
Merging a bit earlier than normal due to overwhelming votes for it.

**Pull request merged**
