### PR TITLE
[DNM] Ministation 2 - Electric FREAKIN' Boogaloo

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Opening the PR so someone who does know how to fix shuttle related issues can take a crack at it because I already lost a majority of my sanity trying to get that sh*t to work.

## About The Pull Request

- [x] - Actually uh, make the damn shuttles work (Arrival, mining, escape, ect.)
- [x] - Forgot if I haven't made firelocks and stuff monstermos compliant or not
- [x] - Re-wired
- [x] - Fix the Engine wiring so the powergen and emitters aren't on the same net.

## Changelog
:cl:
add: New station map: Ministation
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
the place is nice and all

it's just kind of like, missing some things, somewhere, per se

like how the only shower in medbay is at the other end of where cloning is
or how that huge wide open 8 by 7 area in the middle of the medbay with only the sleepers and no tables or walls or anything to break it apart just feels awkward
or how there aren't any windoors or shutters or an airlock separating the medbay desk to deter desk jumpers
or how it seems off how all the maps have this wide open area for atmos unless i'm too security to understand something why it's like that
or how telecoms has only one server (for the common channel)
or how telecoms just has this tank of carbon dioxide there for some reason even though the server room is filled with 100% nitrogen
or how the HoP's office is really just absurdly far away from the rest of the bridge (might as well merge the office and arrivals customs)
or how the cargo warehouse has no maintenance door unlike the other maps (isn't that against fire code?)
or how security doesn't have any kind of crew monitor or anything like that, not even the detective or the HoS
or how there aren't any windows into the nanites lab
or how the science experimentor and the bepis chamber are in the same corner

the map is nice and all ever since you got rid of that accursed maintenance armory connection, but it's just these stupid freakin minor things that just betray the taste of the map, like how me and my grandma and the aunts and the extended family in San Jose all went down to the beach when i was 5 and my grammy packed me a tupperware bowl of spanish rice but i couldn't really enjoy it because it's the beach and there's all this damn sand getting in my rice and then getting in my teeth and my mouth and byeah

**Comment by Maldaris** [comment]
The station has a very cramped, shoestring feeling in a lot of places, which I personally enjoy. Cargo's warehouse being a sort of last stand location, but with the entirety of cargo being visible i

The exception being Medical. It has more open space than atmos, which compared to the other maps in our rotation, is unheard of, as atmos usually has by far the most open tile spaces. A solution that comes to mind is a proper medbay waiting room, and sleepers/stasis beds moved more to the right to make room for that.

As an addendum there are two outstanding wiring issues with the mining shuttle dock APC and Security main hall APC. Neither are wired at round start.

**Comment by Maldaris** [comment]
Fucking mobile moment. Why is close with comment the default enter key result even though it's not the primary button?

**Comment by MarkSuckerberg** [comment]
Working on improvements as I'm writing this.

**Comment by dinnerwoerror** [comment]
close with comment

**Comment by dinnerwoerror** [comment]
but still, after those two rounds, my hope for this place got that much higher

**Comment by dinnerwoerror** [comment]
is it just me or is the AI chamber APC not connected to the energy storage or something

i don't know if it's just me but i don't think i see a wire knot there

**Comment by dinnerwoerror** [comment]
one might think of more creative room names for their power net considering how i count 4 or 5 Aft Maintenance APCs

**Comment by dinnerwoerror** [comment]
othere than that its nice

**Comment by Vorak2** [comment]
After 3 hours alone I have a few issues to report.
1 the lower starboard bow solar airlock dosent work.  ight just have been a one time thing but I dont think it is
2 the solars require 2 and some fullstacks of wires to do. this is almost dubble what most other station require you do use
3 the lack of a whiteship/auxilary dock on station means that you can travel to station with the whiteship (unless something has changed that makes it so you can place custom destinations on station zlevel
4 the armory APC is not wired from the start it seams.
otherwise I say it is a good map and it was enyoyable spending 3 hours alone trying to get the air to become funny colours

**Comment by untrius** [comment]
A bluespace gigabeacon on station would allow the whiteship to travel to the station's z level, without construction of an auxiliary dock.

**Comment by dinnerwoerror** [comment]
both the buttons of the virology airlock only open the exterior airlock, meaning that anyone who is in virology with the interior door closed is trapped inside

**Comment by dinnerwoerror** [comment]
also, there aren't any boxes of replacement lights, so if the lights go out and there is no janitor (which there probably isn't) you're kinda fucked

**Comment by dinnerwoerror** [comment]
the brig physician is jobless and doesn't exist here

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by dinnerwoerror** [comment]
you know, i just remembered, where's the captain's medal box supposed to be

**Pull request merged**
