### PR TITLE
renames the "oh hi mark" to the "oh hi marg"

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

this is exactly what it sounds like

## Why It's Good For The Game

continuity

ascii will love me now, everybody loves a good hard coded character reference in the evening

## Changelog
:cl:
tweak: the oh hi marg emergency shuttle
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
dude, mark is gonna love this when he comes back from the Albanian prison

**Comment by dee-dubya** [comment]
nobody will even see this apart from admins because it's a disabled shuttle


speedmerge anyway

**Comment by TheNeoGamer42** [comment]
marg should be the only hardcoded character ref, and its not even technically an ingame character ref, marg is marg, do it

**Comment by dinnerwoerror** [comment]
didn't you just make the emergency shuttle the oh hi mark last round

**Comment by Maldaris** [comment]
> didn't you just make the emergency shuttle the oh hi mark last round

He can make it that but it's not purchaseable

**Comment by dee-dubya** [comment]
yes, I meant the name of the shuttle itself won't ever be visible to players

**Comment by dinnerwoerror** [comment]
except when it says that the Oh Hi Marg has just docked with the station and that it will be departing in 3 minutes

**Comment by dee-dubya** [comment]
this is true

this does not change my opinion on speedmerging it

**Comment by triplezeta** [comment]
based

**Pull request merged**
