### PR TITLE
Box Facelift part 2 - EVA

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Changes Box's EVA to a more VG style layout.

image

It contains two Engineering suits, two Atmos suits, two medical suits, and two standard eva suits.

This PR also adds EVA access to the follow jobs, but not under their minimal access, just skeleton crew.

- HoS 
- Warden 
- Detective 
- Security Officer 
- Brig Phys 
- Engineer 
- Atmos Tech 
- Doctor 
- Chems 
- Genetics 
- Viro

Note that the jobs who normally have EVA access, regardless of skeleton crew or not, are Paramed, HoP, CE, and LT.

## Why It's Good For The Game

Utilizes the entire EVA space, considering that the right side that just had materials was hardly ever used.

## Changelog
:cl:
add: EVA access has been added to Security, Engineering, and Medical jobs during skeleton shifts.
tweak: Boxstation EVA has been completely redesigned.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
I think my brain thought I already put the access on chems.

Also, I accidentally buggered up the atmos door looking at it, putting 
```c
req_one_access_txt = "list(24,11)"
```

instead of 
```c
req_one_access_txt = "11;24"
```

**Review by MarkSuckerberg — APPROVED** [review]
approving now, but am hoping other station's EVA areas are modified to resemble this as well.

**Comment by SynnGraffkin** [comment]
I can definitely do Meta, unsure about Pubby / Kilo with how small the EVA rooms are there.

**Comment by triplezeta** [comment]
if you shrink down the tech storage room on kilo you can make room for it

if you cut into the big weird useless space decoration hallway thing on pubby you can make room for it

**Comment by SynnGraffkin** [comment]
space deco is cool though

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
