### PR TITLE
thou n t not-glockn't 2 - the morgan smittenburg remorese edition

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## A preface

so morg, you thought you could be sad at my pull request getting automatically closed for being too stale, huh

Screenshot (606)

think again bitch ligger boy

## About the pull request

cops get guns, except they run on 9mm

Screenshot (567)

i might be adding ammo variants but probably not right now, so feel free to do it for me

by the time science has researched the ammo for this thing in the protolathe, shits probably already hit the fan

i'm sure there's gonna be at least one moronic seccie that walks around with this strap for no reason and gets it stolen at roundstart

## Why It's Good For The Game

it's always nice to have alternatives

this will tell the space hobos and greifers to not fuck with security

Screenshot (565)

bop bop bop bop, i'm reachin for my gun, sunglasses emoji left pointed finger emoji

## Changelog
:cl:
add: the commander pistol
add: commander pistol in warren den and head of shitcurity lockers
add: unloaded commander pistol in security gear lockers
add: commander ammunition in the armory
add: commander ammunition in the techwebs
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
I think the reason it was originally failing the linter checks was because tgstation.dme didn't have the waspstation.dm included.

**Comment by dinnerwoerror** [comment]
but it's not failing the linter checks now, is it

**Comment by Superyodeler** [comment]
I'm saying you should MoDuLaRiZe

**Comment by dinnerwoerror** [comment]
hey lads, remember that time i re-added the antimatter reactor

**Comment by MarkSuckerberg** [comment]
god is dead

**Comment by dinnerwoerror** [comment]
if there is no god, then man will see fit to create one in time

**Comment by TheNeoGamer42** [comment]
all gods are meant to be shot and killed

**Comment by dinnerwoerror** [comment]
i was quoting Voltaire

**Comment by MarkSuckerberg** [comment]
in the far future


when someone is trying to hire me for some coding position or recruiting people for some project


please don't use this against me, a man can only take so much before he breaks

**Comment by dinnerwoerror** [comment]
mission accomplished boys, we did it

**Comment by MarkSuckerberg** [comment]
apc destroyed

**Comment by TheNeoGamer42** [comment]
ok gonna force the current round to end even though its zero pop so I can shoot people next round

**Comment by dinnerwoerror** [comment]
master shifu said that anything is possible when you have inner peace

**Comment by dinnerwoerror** [comment]
and because of my inner peace, @TheNeoGamer42 finally began playing security

**Comment by TheNeoGamer42** [comment]
nah probably just gonna be headcurity more

**Comment by dinnerwoerror** [comment]
dear zeta moth
i did not necessarily steal the sprites, i simply gave them a new life
considering how the pull request they were born in did not ever pass
https://github.com/tgstation/tgstation/pull/43407

**Pull request merged**
