### PR TITLE
hitscan lasers

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

this makes most laser weapons hitscan, excluding the accelerator laser cannon.

## Why It's Good For The Game

it's not

## Changelog
:cl:
tweak: most laser weapons are now hitscan. Sigh.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
IMPORTANT CHANGE: disablers are not hitscan

**Comment by triplezeta** [comment]
whoops i forgot to actually push the commit

**Comment by triplezeta** [comment]
actually im probably gonna close this 


this PR isn't worth the effort and balancing nightmare that will come afterward

**Comment by Superyodeler** [comment]
If you didn't want this, why did you cood

**Comment by triplezeta** [comment]
i thought it was funny

**Comment by triplezeta** [comment]
sike

**Comment by dinnerwoerror** [comment]
no

**Comment by MarkSuckerberg** [comment]
I will testmerge this tomorrow (two hours and 17 minuted from now) and will leave it testmerged until I get a major complaint from two people or the day ends, whichever comes first. Godspeed.

**Comment by triplezeta** [comment]
fuck

**Pull request closed without merging**
