### PR TITLE
minor fix to hypercharged slime cells

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

raises the charge rate for hypercharged slime cells from 225 to 2250, the original value.

## Why It's Good For The Game

i don't know, is it?

## Changelog
:cl:
fix: hypercharged slime cores have their proper recharge rate as well.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Balance is... questionable, but since this is the default for /tg/code, we might as well set it back to what it was before.

**Comment by dinnerwoerror** [comment]
to be honest i don't give a shit about balance anymore, the crew should be allowed to have what they rightfully should, what kind of argument is "balance", this isn't a competitive esport where every minor update is going to completely throw the entire meta into disarray

**Comment by triplezeta** [comment]
fuck balance

**Comment by dinnerwoerror** [comment]
yea morg, i've seen the ways of the bay station

**Pull request merged**
