### PR TITLE
Removes unneeded slang/slurs in response to GitHub

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Read title

## Why It's Good For The Game
Getting our repo suspended from github is not a good idea

## Changelog
:cl:
tweak: Faggots are now called meatballs in the code, as they have the same meaning, just one also happens to be a slur.
del: removes other slurs found via a regex
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Even travis hates it

**Comment by triplezeta** [comment]
nig

**Comment by SynnGraffkin** [comment]
Why is there no FUCK label?

**Comment by triplezeta** [comment]
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being closed by a maintainer if it is not updated or reviews are not addressed. If your PR is closed as stale, feel free to open a new one after dealing with the issues. This may also be an indication that the maintainers do not have interest in this change, you can try to convince them otherwise, or persist in the doomed world you have created.

**Pull request closed without merging**
