### PR TITLE
Fixing misc piping issues

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Fixes the following: 
image

image

## Why It's Good For The Game

Because Bee fuckers can't repipe around Cryo.

## Changelog
:cl:
fix: Pipes
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
I made the piping error ;-;

**Comment by SynnGraffkin** [comment]
<3

**Comment by Cenrus** [comment]
Screenshot_20200301-021618

Imagine not using modern and ROBUST layered piping.

- [ ] no sinful pipes through walls
- [ ] atmosians love it
- [ ] well organized and easy on the eyes
- [ ] hell yeah

**Comment by MarkSuckerberg** [comment]
*Thanks, Cen...*

**Pull request merged**
