### PR TITLE
Makes oral implants possible

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Makes surgical drills sharp and therefore able to start surgery, making oral implants possible. Also makes it so surgical drills are very very bad at butchering and deal 10 damage instead of 15.

## Why It's Good For The Game

Corrects a minor oversight that made oral implants impossible. Hopefully shouldn't add too much power to the drill.

## Changelog
:cl:
tweak: surgical drills are sharp, but bad at butchering and deal less damage
fix: oral implants are possible
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
i always thought the future was like the victorian era where nobody brushes their teeth and we chop a native's hands off if we feel the need to

**Comment by Superyodeler** [comment]
In the future we don't brush our teeth, we just apply the drill to any cavities

**Comment by triplezeta** [comment]
why the drill nerf tho

**Comment by Superyodeler** [comment]
Adding sharpness allows it to dismember limbs. I reduced the damage so it wouldn't be as good as the surgical saw.

**Comment by triplezeta** [comment]
drill go vrrrrrrrrr

**Comment by Superyodeler** [comment]
What do you mean "non-modular"!?

**Comment by dinnerwoerror** [comment]
LoOkS lIkE tHiS nEeDs To Be MoDuLaRiaZeD

**Comment by Superyodeler** [comment]
Telling people to modularize is MY job

**Comment by MarkSuckerberg** [comment]
Pff, since this is a fix I don't think it needs a vote. If there's an issue with the drill being nerfed, that can be reverted later although I don't see why people would want drills to be that powerful.

**Pull request merged**
