### PR TITLE
Pyroclastic anom rebalance

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Reduces the tick rate for a pyro anomaly spawning Oxygen/Plasma, and reduces the temperature, making them less of a cataclysmic event when they spawn.

## Why It's Good For The Game

Monstermos made cleaning these up a 20-30 minute affair, for a single anomaly that goes all the way to the slime stage. This should hopefully reduce the pain of doing so (a bit).

## Changelog
:cl:
balance: reduced the tick rate for pyroclastic anomalies to 1/5th original (5 ticks/emission to 25 ticks/emission)
balance: reduced the temperature for tick spawned plasma/oxygen by 500 Kelvin
balance: reduced the temperature and mols of detonation spawned plasma/oxygen by 300 Kelvin and 250mols.
balance: reduced the weight for pyroclastic anomaly spawns from 20 to 15.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
dude it took me like the entire round to clean up the fallout of one of these, and that was with the help of two other engineers

**Comment by Maldaris** [comment]
> dude it took me like the entire round to clean up the fallout of one of these, and that was with the help of two other engineers

That round had two hit the same relative area in Box medical; I remember that. Someone eventually just gave up and vented the entire section into space which seems to be the solution.

**Comment by triplezeta** [comment]
yeah that was rin


coincidentally, I happened to get a can filled with ungodly amounts of somewhat cool airmix on that same round

**Comment by MarkSuckerberg** [comment]
I'd recommend reducing both the amount of plas/O2 spawned and the temperature when it detonates ([anomalies.dm:274](https://github.com/WaspStation/WaspStation-1.0/blob/master/code/game/objects/effects/anomalies.dm#L274)). Yes, it's supposed to be destructive, but it's not supposed to permanently make a quarter of the station uninhabitable.

**Comment by MarkSuckerberg** [comment]
Also I think the atmospheric burn test holodeck program may need to be revisited, since at the moment it can destroy a good chunk of the station. Luckily nobody's done it yet.

**Comment by Maldaris** [comment]
> I'd recommend reducing both the amount of plas/O2 spawned and the temperature when it detonates ([anomalies.dm:274](https://github.com/WaspStation/WaspStation-1.0/blob/master/code/game/objects/effects/anomalies.dm#L274)). Yes, it's supposed to be destructive, but it's not supposed to permanently make a quarter of the station uninhabitable.

hot take (haha): If you let it explode, it should be dangerous still. alternatively we could increase the time it takes to detonate (lifespan).

**Comment by MarkSuckerberg** [comment]
I know that, but it's literally a self-sustaining fire that incinerates everything and anything, and personally I think it should be at least partially reduced.

**Comment by Maldaris** [comment]
> I know that, but it's literally a self-sustaining fire that incinerates everything and anything, and personally I think it should be at least partially reduced.

I'm cool with that. Doing now.

**Pull request merged**
