### PR TITLE
Trekchem Changes (Consider them nerfs)

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

This PR does the following: 
Nerfs the healing of basic trekchems down to 0.5 damage per tick for all basic types. 
Adds Bicaridine Plus and Dermaline, "Upgraded" versions of Bicaridine and Kelotane that heal 2 damage per tick.
Lowers Dexalin Plus' healing to 2 damage per tick. 
Lowers Carthatoline's healing to 2 damage per tick but increased the purge rate to 2.
Lowers the healing of Tricordrazine down to an average of .2 damage of all types healed per tick. No longer heals oxyloss.
Added Tetracordrazine, which heals at the same rate of Tricord but also heals oxyloss. Make by mixing 3 units Tricord with 1 unit Dexalin.
Removed Tricordrazine's OD.
Commented out Hepanephrodaxon and it's recipe. Will be readded at a later date along with more chem changes.
Readds corazone's recipe.

I'm coming for you next, goonchems.

## Why It's Good For The Game

The basic trekchem nerfs are to encourage putting effort into mixing more involved chems, such as libital, trophazole, salicylic, etc. instead of simple 3 button press chems that heal just as well. 
The tricordrazine nerf is to encourage its use as a dilutant rather as a cureall for basic damage.
The (temporary) removal of Hepanephrodaxon is because.. it's OP as hell? As of right now, it heals 12 toxin damage per tick (more than thializid, anti-toxin, pentetic, and charcoal combined) on top of healing liver damage, on top of healing 10 stamina damage per tick, on top of having a *beneficial* OD that makes you sleep immune, speeds you up, and gives you Pump-Up's stun resistance!  All this for a chem you can mix with just a chem dispenser and a bar of plasma for a catalyst is very powerful.

## Changelog
:cl:
add: New chems. Bicaridine Plus, Dermaline, and Tetracordrazine.
del: Hepanephrodaxon. Will return at a later date.
balance: Lowered the healing on many trekchems
balance: Tricordrazine no longer has an OD
fix: Corazone has a recipe again
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
"tetracordrazine" I saw what you did there...

**Comment by triplezeta** [comment]
you make it with 4 chems

thats the joke

**Comment by SynnGraffkin** [comment]
Tetrischordine

**Comment by AsciiSquid** [comment]
For the sake of wiki maintenance, if this PR goes through I expect the wiki to be updated with the new recipes before merging. I'd rather it not become messy **and** outdated.

**Comment by triplezeta** [comment]
hokay

**Comment by dinnerwoerror** [comment]
yea but what about survival medipens

**Comment by triplezeta** [comment]
...good point. I should swap tricord out for something more potent.

**Comment by dinnerwoerror** [comment]
bro fuck survival medipens all my homies hate survival medipens

**Comment by triplezeta** [comment]
based?

**Comment by triplezeta** [comment]
the tricord in medipens has been replaced by equal parts bicaridine plus and dermaline

bicaridine plus will now slowly stem bleeding while it's in the system
dexalin plus will now regenerate blood loss at about twice the rate of iron

**Comment by triplezeta** [comment]
silibinin should now heal liver damage on inject

polypyr oligmers metabolizes slower and heals more as well as stemming bleeding faster

**Comment by Superyodeler** [comment]
silblblblblblin

**Pull request merged**
