### PR TITLE
Compact shotgun additions

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
image
Adds multiple new subtypes of the compact shotgun. Why? I honestly don't know.

## Why It's Good For The Game
It's not

## Changelog
:cl:
add: Compact compact combat shotgun and it's sawn-off equivalen
add: Compact compact compact combat shotgun and IT'S sawn-off equivalent
/:cl:

### CODE REVIEW

**Comment by dee-dubya** [comment]
this right here is the sort of quality code we expect to see

**Comment by triplezeta** [comment]
yes

**Comment by triplezeta** [comment]
speedmerge 
now

**Comment by AsciiSquid** [comment]
Legends say if you compact enough the shotgun will fire a singularity

**Comment by dinnerwoerror** [comment]
so does this mean that you'll be able to saw down a full sized combat shotgun now

**Pull request merged**
