### PR TITLE
Meta Atmos and Foyer Update

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Updates Metastation Atmos to a more open setup, similar to Box, that was done by @MrJWhit . 

Changes the Engineering foyer back to what it was previously, in order to make room for some of the atmos changes, using Yog's setup for a reference.

This also provides an outlet from port for special mixes that leads to the supply / waste setup in front of the Atmos desk.

## Why It's Good For The Game

More open space for Atmos techs to do their thing, as well as changing the Engineering foyer back to what it was before. Personally, I would like to use Citadel's foyer, but they put the Engineering circuit printer and protolathe by the Engine and I don't want to cuck Atmos techs out of it without changing door access.

image

image

image

## Changelog
:cl: BigFatAnimeTiddies
add: The Atmospherics department on Meta have been given a second hardsuit to fit their needs.
tweak: The blueprints for Metastation have been updated to reduce the amount of pipes in the Atmospherics department, encouraging experimentation. Additional lighting has also been provided.
/:cl:

### CODE REVIEW

**Comment by Victor239** [comment]
Can you move the manifold for N2 and O2 output down one tile? You can't otherwise place a layer adapter before the existing gas pump.

**Comment by SynnGraffkin** [comment]
Now that I think about, Atmos techs DO have engine access when it isn't a skeleton shift, right?

**Comment by triplezeta** [comment]
no lol

**Comment by Victor239** [comment]
Delete the pipe dispenser machines and replace with water tank, fuel tank and a fire safety closet like Delta has. Nobody uses them.

**Comment by SynnGraffkin** [comment]
There already is a water and fuel tank for Atmos though.

**Comment by Victor239** [comment]
I'd prefer them swapped for large air scrubber and another pump. It's weird how only toxins gets a large air scrubber and not the department whose responsibility it is to clean up gas leaks.

**Comment by Victor239** [comment]
I presume the mats are all the grey crate now too right?

**Comment by SynnGraffkin** [comment]
Yeah, materials in the crate.

**Pull request merged**
