### PR TITLE
Random rooms framework and templates

### PR DESCRIPTION
**Pull request by Victor239**
##  About The Pull Request
This adds 93 random maint room templates and the framework for adding them to a map. These are not actually mapped into any station yet. 

Random rooms can be weighted to make them rarer or more common. They can be optionally stocked to make them spawn more than once. Some additional items have also been added that may spawn in maint including an unlicensed PDA, hair growth spray, spray tan, hair dye, straight razor, hand mirror aand beer nuke codes.

## Why It's Good For The Game
Randomised rooms makes maint much more interesting and fun to explore, adding variety to a station. The framework also lays the foundation for later PRs like a randomised engine room, and for special unique jobs which may spawn if the room is present for them.

## Changelog
:cl:
add: Adds the ability to load room templates. Not currently utilized by any map.
add: Adds 93 random maint rooms templates.
add: Adds some assorted items that may spawn in maint.
/:cl:

Ports:
https://github.com/BeeStation/BeeStation-Hornet/pull/254
https://github.com/BeeStation/BeeStation-Hornet/pull/1128
https://github.com/BeeStation/BeeStation-Hornet/pull/1129
https://github.com/BeeStation/BeeStation-Hornet/pull/1554
https://github.com/BeeStation/BeeStation-Hornet/pull/1947

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Does the work for me, I was going to take Cit's framework for Engines.

**Comment by SynnGraffkin** [comment]
@MarkSuckerberg can you check the lints?

**Comment by Maldaris** [comment]
> @MarkSuckerberg can you check the lints?

`file ./code/game/objects/items/cosmetics.dm is missing a trailing newline`

**Comment by Victor239** [comment]
Newline fixed

**Comment by MarkSuckerberg** [comment]
I'll do one more check over it, and then I believe it's merge-ready.

**Comment by SynnGraffkin** [comment]
Once mapping changes are done I plan on looking into this.

**Comment by Maldaris** [comment]
Since Monstermos is in, @SynnGraffkin can you revisit this?

**Comment by MarkSuckerberg** [comment]
Extremely stale.

**Pull request closed without merging**
