### PR TITLE
A New Syndicate Special Bundle: The Made Man

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
On one of the Gorlex Marauder's raiding runs, they stumbled upon an unmarked vessel, engines on impulse, guns retracted, and communications completely dark. A few operatives were dispatched to search the ship, and their findings were rather peculiar. Crates upon crates of old Thompson Machine Guns, stills of a very clear and alcoholic liquid, and uniforms reminiscent of those worn by organized crime families of Old Earth. A meeting was called, and plans made, culminating in the kits now occasionally being seen sported around NT stations by Gorlex operators.

This adds a new potential kit into the Syndicate Special pool, which brings the Tommygun out of retirement, and lets you pretend you're an actual crime boss from the safety of your local Nanotrasen station. Comes with:
A Tommy Gun
Mafia Outfit (complete with fedora!)
Three kits to make Molotov Cocktails
Cigars
An Agent ID
A spare trench-coat
A Zippo Lighter
A Switchblade (This might eventually get swapped out for a fountain pen E-dagger)

## Why It's Good For The Game

More potential choice is good, also brings back a weapon trapped in code and nudges the stats a little bit. 

## Changelog
:cl:
add: The Gorlex Marauders now are offering a new kit to Operators looking to take a chance, code-named as The Made Man. Are ya' feeling lucky, Operator?

balance: Reduces the outright bonkers lethality level of the Tommygun, bringing it down to fire_delay 2, and burst_size 3.

/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
cant wait for full auto to be ported from bee so i can mow down waves of people with this

**Comment by dinnerwoerror** [comment]
ratatat tat tatada

**Comment by CRITAWAKETS** [comment]
https://youtu.be/d7dfsLfWJvc?t=122

**Comment by Acer202** [comment]
"The station wanted booze and I organized it. Why should I be called a public enemy?"

Hopefully people will take the mindset of Al Capone and be rather classy with it. Good stuff!

**Comment by dinnerwoerror** [comment]
heha more murdering tools

**Pull request merged**
