### PR TITLE
Ports dynamic bugfixes

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Ports TG dynamic bugfixes that prevent blacklisted roles from becoming traitors.

## Why It's Good For The Game

Less antag sec, less drama.

## Changelog
:cl:
fix: dynamic will no longer make blacklisted roles antags
config: antag blacklist now effects dynamic
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
pretty sure windowserrors ported this and some other dynamic fixes, what PR does it port even?

**Comment by Superyodeler** [comment]
These aren't in. Earlier today there was a dynamic round where Windowserrors, as a warden, got traitor, resulting in a lot of people being very salty.

**Comment by TheNeoGamer42** [comment]
you know that happened to me too, like one of the first rounds it was dynamic with me as RD and a secoff being the only traitors, but that was before that was merged, so I guess it was never fixed, sad

**Comment by WindowsErrors** [comment]
please you gotta

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by Superyodeler** [comment]
Integration test moment

**Comment by WindowsErrors** [comment]
we said that last time

**Pull request merged**
