### PR TITLE
Roundstart report no longer elevates alert level

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About The Pull Request

The roundstart report that happens after a secret round starts will no longer elevate the alert level. The message, as well as the audio file, have been edited to reflect this. The original intercept audio file has been kept for legacy purposes and if it needs to be used elsewhere.

## Why It's Good For The Game

Given that Syndicate chatter is intercepted almost every single shift, there's a high IC chance that it is a false positive and the station is put under blue alert for no valid reason. The heads of staff should coordinate to change the alert level if and when hostile activity is reported on the station itself. This also gives the alert levels a bit more meaning as code green sees use outside of extended rounds.

## Changelog
:cl:
tweak: The roundstart "enemy communication intercepted" message will no longer elevate the security level.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Wouldn't this entirely defeat the purpose of secret extended?

**Comment by triplezeta** [comment]
not really

**Comment by Shadowtail117** [comment]
How would it? The alert level would still be green on actual antagonist rounds; you still wouldn’t know whether or not it IS extended, you just don’t have to be on high alert from the get-go.

**Comment by SynnGraffkin** [comment]
> 
> 
> The alert level would still be green on actual antagonist rounds

This exactly. Fake greenshift is absolutely shit to deal with. At least with the blue alert at roundstart, players can guess there may or may not be an antag. If you begin a round, and it's green, you can assume it's a safe shift to begin a project then WHOOPS, you were an antag target and round removed.

**Comment by triplezeta** [comment]
the alert is different than actual extended, I think players will be sharp enough to know the difference

**Comment by SynnGraffkin** [comment]
It's still forcing a false sense of security of the safest alert level.

**Comment by dinnerwoerror** [comment]
jobbies saying they want heads to actually work with eachother

Screenshot_20190529-011144_Instagram-1

i have a feeling that this will get swatted down in the voting phase because ive heard numerous people say how it would be a stupid change, which to be fair, it kind of is

while you're here, you could also make the round start status reports actually tell what antagonists are gonna be on today instead of it basically being a shitpost about antags that we'll never have enough pop for, antags that straight up don't exist anymore, and why we should care about whatever that wall of text about "dimensional cataclysm code OMEGA TYPED IN ALL CAPS"

**Comment by Shadowtail117** [comment]
It gives a "false sense of security" the way that code blue keeps the station on high alert during secret extended when there's no actual threat. The point isn't so that the crew thinks it's extended (as it'll be code green no matter what now and it can be considered metagaming to think it always means extended), it's so that they don't have to start the round already on high alert for a threat that, given the IC uncertainty of Syndicate activity, might not actually be there.

The heads of staff are still able to up the security level if and when hostile activity is spotted on the station. Bear in mind as well- this PR does not touch anything other than the alert levels, and stuff like station projects are still locked/unlocked like normal.

**Comment by SynnGraffkin** [comment]
and what I am saying is Fake Green is an awful idea. I'm sure @dee-dubya can chime in from experience on Hyper or @tiramisuapimancer on Cit.

**Comment by tiramisuapimancer** [comment]
Fake green is pretty eh, it's not that good or that bad. I think it's inherently different on cit than it would be on here simply because citadel has extended rounds a lot more frequently as well as differently than here- we have extended forced at (sadly common) dead pop, they have a vote every preround between extended and secret. I feel like a rework of the round start report and alert level would be interesting though

**Comment by SynnGraffkin** [comment]
Cit codes roundstart voting for secret or not isn't that good either, imo. The dynamic they have is better, imo, but flat out making roundstart blue not be a thing is absurd.

**Comment by triplezeta** [comment]
there is still a different alert for when there is a threat to the station (or it's just sextended)

the only thing this does is make it so that the alert level doesn't get changed roundstart

functionally there is no difference other than the escape shuttle takes 20 minutes to come when a crew transfer vote passes instead of 10

**Comment by SynnGraffkin** [comment]
Again, this is essentially fake greenshift, which is bad.

**Comment by triplezeta** [comment]
it's not
I just explained why it's not

fake green baits you into thinking nothing is wrong so powergamers have an excuse to powergame on green alert
you still get an alert saying something is wrong at the start of the round when there are threats or it is sextended

**Comment by SynnGraffkin** [comment]
If you're there for roundstart, but if you aren't you don't get that notification but see it's green, then you get fucked by possible antag. Still fake green.

**Comment by triplezeta** [comment]
image
three words removed

I don't think anyone conscious will confuse this for actual extended
image

**Comment by triplezeta** [comment]
I can't believe I'm using this as an argument, but there are these things called "newscasters" everywhere on the station that have a newsfeed of all global announcements that happen during the round because of random events, including the enemy communication interception alert.

there are already means of confirming if it is extended or not other than the roundstart alert level

**Comment by Shadowtail117** [comment]
I'm not sure I understand your argument that it being code green automatically making people think it's an extended shift. There is still a command report suggesting possible antagonist activity, and other servers (Baystation, for example) handle roundstart code green without issue. It's just the difference of "oh, we're not starting the shift off with a security emergency" - the crew should still be alert for anything that may happen.

**Comment by dinnerwoerror** [comment]
it's probably because people think that it's a stupid change

**Comment by Maldaris** [comment]
Closing as controversial.

**Pull request closed without merging**
