### PR TITLE
Scav comerce tech

### PR DESCRIPTION
**Pull request by Baldir-Odensen**
## About The Pull Request
Do NOT MERGE

this is all the scav related code i have made. remember if you make it work ill give you 2 game kays from the list i published on the discord of your choice
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
What's missing that needs to be added or not working that needs to be fixed?

**Comment by Baldir-Odensen** [comment]
The issue that got me stuck was it unable to find the tgui routing for the uplink.

**Comment by Superyodeler** [comment]
I see the issue, going to try to work out what's causing it

**Comment by Superyodeler** [comment]
Here is an image that shows the issue in case anyone has seen this before:
Scav_Uplink_Bug

**Comment by Baldir-Odensen** [comment]
as long as the implementation achieve the goal of allowing the scav bois to buy stuff from a list and that it uses the bank account I'll accept it.

So if you find a better solution than the one I have been working on do that one instead.

Just some clarification

**Comment by MarkSuckerberg** [comment]
Closing due to it being stale and having file conflicts.

**Pull request closed without merging**
