### PR TITLE
Recolors plasma and reinforced plasma windows.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR resprites plasma and reinforced plasmas to be more blue, and less garishly pink.

THIS IS TEMPORARY UNTIL ZETA MAKES NEW SPRITES FOR LITERALLY EVERY WALL AND WINDOW

## Why It's Good For The Game

Right now map makers do not want to reinforce windows by being plasma for a simple reason: They are way too obnoxiously pink. This changes that to a nice purple.

image
image

## Changelog
:cl:
tweak: Nanotrasen has decided to add blue dye into their patented plasma windows. Station designers rejoice!
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
haha blurple

**Comment by triplezeta** [comment]
also im only done with the regular walls so far and i still have to finish the titanium, reinforced, plastitanium, titanium window, regular window, reinforced window, plastitanium window.......



ae

**Comment by MarkSuckerberg** [comment]
why is it that every time I need to see maps, the mapdiffbot doesn't work, and when I need to see sprites, the icondiffbot doesn't work

**Comment by Superyodeler** [comment]
F

**Comment by CRITAWAKETS** [comment]
Major update to the icons have been done. Now this PR is ready for merge. (This time i didnt forget the directional windows and stack objects!)

**Pull request merged**
