### PR TITLE
Better security jumpsuit sprites, plus for suits and chef

### PR DESCRIPTION
**Pull request by Victor239**
## About The Pull Request
Current security gear looks like ass, this resprites most sec jumpsuits, armor vest and helmet. Also resprites chef & bartender uniforms and all basic civilian suits.

## Why It's Good For The Game
Much better looking sprites.

## Changelog
:cl: Sprites by triiodine
imageadd: New sprites for security clothing, chefs and civilian suits.
/:cl:

Ports: https://github.com/BeeStation/BeeStation-Hornet/pull/487

### CODE REVIEW

**Comment by triplezeta** [comment]
as the """head"""spriter, I approve of this

**Comment by SomeAngryMiner** [comment]
might wanna note that this are done by triiodine on the changelog.

**Comment by Victor239** [comment]
Sure thing.

**Comment by MarkSuckerberg** [comment]
Triio, if you see this, you da best, don't you forget that

**Pull request merged**
