### PR TITLE
adds the dexterous type guardian spirit

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

the title says it all partner

## Why It's Good For The Game

because a holoparasite should be able to help out around the kitchen in ways other than tenderizing the meat

## Changelog
:cl:
adds: the dexterous type stand to the traitor holoparasite injector
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
this isn't in the traitor injector for a reason. it's nodrop with any item and pretty damn busted

**Comment by dinnerwoerror** [comment]
yea its pretty damn busted because it's supposed to be a martial arts tier item

**Comment by MarkSuckerberg** [comment]
this WAS tested, correct?

**Comment by MarkSuckerberg** [comment]
Not merging until tested.

**Comment by dinnerwoerror** [comment]
oh yea this compiles in case thats what you were wonrding

**Comment by dinnerwoerror** [comment]
i actually legitimetely properly tested it now and its ok, i give it the nintendog squeal of approval

**Pull request merged**
