### PR TITLE
Removes Donutstation

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Completely removes donutstation, but the white ship is still intact.

## Why It's Good For The Game

I don't know of any other big codebase that still maintains Donut, and I am not willing to maintain it here.

## Changelog
:cl:
del: Donutstation has been decommissioned.
/:cl:

### CODE REVIEW

**Review by JacobJ-coder — APPROVED** [review]
Yes, please

**Comment by triplezeta** [comment]
i am going to piss on the grave of donutstation

**Comment by TheNeoGamer42** [comment]
donutstation, more like, do not maintain

**Comment by dee-dubya** [comment]
it's time to end this farce

**Review by Superyodeler — APPROVED** [review]
Do not station

**Pull request merged**
