### PR TITLE
Hardhat Helmet Sprites

### PR DESCRIPTION
**Pull request by Quantum-M**
## About The Pull Request

Changes the hardhat helmet sprites to look less crappy (hopefully), adds a new green helmet, and updates the code for said hardhats a bit.

Also adds in safety helmets and mining helmets, and adds some of the safety helmets to the QMs, Atmos, and Electrical closets, and the mining one to the mining closets.

## Why It's Good For The Game

Attempts to make helmets look nicer, along with giving them a object icon that isn't essentially the same as the on mob one.

image

image
_Mining hardhat object sprite by thatangryminer_
## Changelog
:cl: Quantum-M, thatangryminer
add: Green Hardhats, Safety Helmets, and Mining Helmets, and adds them to some of the lockers.
tweak: Updates sprites for hardhats.
code: Updated Hardhat code to not use the weird 0 and 1 numbers logic to look for relevant icon states.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Is it just me or has Ian ALWAYS been spawning in with a helmet on now?

**Comment by Superyodeler** [comment]
I was assuming people were giving him one every shift.

**Comment by SynnGraffkin** [comment]
I've been the only one on shift and he had one already on multiple times.

**Comment by triplezeta** [comment]
ian's hat is persistent

**Comment by dee-dubya** [comment]
If Ian doesn't die, his hat persists between rounds.

If he does, he spawns as a puppy during the next round.

**Comment by ADepressedPyroshark** [comment]
I fucking hate these sprites because they are out of place. They go from the top down and NO OTHER SPRITE DOES THIS(citation needed).  OR AT LEAST THE CLOTHING. THE FUCKING LIGHT MAKES ME THINK ITS A REALLY WEIRD MASK BECAUSE TOP DOWN IS SO OUT OF PLACE FOR THIS AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA. Other than that good job

**Comment by ADepressedPyroshark** [comment]
Like, I mean when they are an item or whatever the worn sprites are fine its just change the item sprites PLEEEASE

**Comment by AsciiSquid** [comment]
Gonna have to agree, worn sprites are fine but the item sprites (excluding the miner one) seem off compared to other hats for some reason.

**Comment by triplezeta** [comment]
From experience with these in game, 

The perspective of the helmets is odd. Putting it at a perspective that looks more similar to hats such as the berets or softcaps may help.
The palettes aren't to my liking. They feel very cartoony and generally aren't appealing to me. I'd prefer something a bit less saturated.
The headlamp lights are done in an odd way and don't fade away like the old ones did, leading to an odd appearance where the light will "cut off" abruptly.

Otherwise these are good

**Comment by SynnGraffkin** [comment]
The more I see these in game, the more it just feels extremely off to what we have prior. The cone of light especially feels way too different from just a lit bulb.

**Pull request merged**
