### PR TITLE
Misc. Lighting Fixes

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
Fixes: #573

## Changelog
:cl: Azarak, Bobbahbrown, Mark Suckerberg, ShizCalev, Timberpoes
fix: Mecha lights work again
fix: Directional lighting overlays no longer blind anyone looking at security camera feeds
fix: Gunlight runtime fully fixed
fix: Foods crafted with glowy ingredients no longer glow when in someone's inventory
add: Runechat now appears even in pitch darkness
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
do security cameras still emit god rays

**Comment by SynnGraffkin** [comment]
Does this fix #573 ?

**Comment by MarkSuckerberg** [comment]
No.

**Comment by SynnGraffkin** [comment]
Well, this makes mining mechs incredibly hard to use, unless you are wearing NVGs.

**Comment by dinnerwoerror** [comment]
light

Screenshot (988)

**Comment by MarkSuckerberg** [comment]
Neither issues have been addressed upstream, and this was supposed to be a port from upstream. I can probably see about fixing them at some other point.

**Comment by dinnerwoerror** [comment]
i personally think it adds to the security camera experience, considering how often you need to shut the blinds because the lens flare and the glare keeps blocking your view of the monitor

**Comment by MarkSuckerberg** [comment]
Both issues addressed.

**Pull request merged**
