### PR TITLE
"TG Merge 6.9: Misadventures in Non-Atomization Land" 

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Not going to write much, full credit to everyone from TG who did the pull requests listed by PR number on each commit, I just slapped it all in and made sure it worked. I apologize that this PR is un-atomized and somewhat hypocritical in that regard, but I really just don't want to ruin the last semblances of modularization we have remaining.

## Why It's Good For The Game
Lots of good performance improvements and some base features. Hopefully gets us modularized *enough* against TG for the near future.

## Changelog
:cl: <a href="https://github.com/WaspStation/WaspStation-1.0/pull/539">Multiple Authors<a>
add: Lights are a lot less laggy due to being overlays.
add: Some lights are now directional.
add: Runechat now shows emotes.
add: Eye contect, if you examine someone and they quickly examine you back, you both get shown a small, non-intrusive message.
add: glass floors?
fix: You can sing over comms and all that now.
fix: Adjusting view range shouldn't break as much when using full screen.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
can we do the funny we did with pr number 69 and get this pr to 69 comments

**Comment by Superyodeler** [comment]
We can try

**Comment by triplezeta** [comment]
lights are cool

**Comment by TheNeoGamer42** [comment]
haha 6.9 69 sex number haha sex

**Comment by triplezeta** [comment]
@dinnerwoerror you are phoronic

**Comment by Superyodeler** [comment]
oof

**Comment by tiramisuapimancer** [comment]
@dinnerwoerror you are phoronic

**Comment by triplezeta** [comment]
@zeskorion you are phoronic

**Comment by tiramisuapimancer** [comment]
@zeskorion you are phoronic

**Comment by zeskorion** [comment]
do you all really want me on your github?

**Comment by triplezeta** [comment]
iunno

**Comment by dinnerwoerror** [comment]
https://youtu.be/oIFL0CHzi20

**Review by Maldaris — APPROVED** [review]
In a "playable enough" state, that remaining issues with directional lighting can come in different PRs.

**Pull request merged**
