### PR TITLE
Fixes AAC Topic Breaking

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Closes: #421 

## Changelog
:cl:
fix: AACs should stop rapidly breaking the topic limits.
/:cl:

### CODE REVIEW

**Review by Maldaris — APPROVED** [review]

**Comment by Maldaris** [comment]
Speed. Fukken. Merge.

**Comment by MarkSuckerberg** [comment]
Let it pass, then merge

**Comment by MarkSuckerberg** [comment]
TGUI make you lose control

**Comment by Maldaris** [comment]
> Let it pass, then merge

Did I say speed merge? I meant let the pipeline pass, THEN speed merge.

**Comment by Superyodeler** [comment]
Merging bugfix

**Pull request merged**
