### PR TITLE
Completely overhauls pubby's white ship to not be a big stinky.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

Pubby's white ship is now overhauled to be way, way different (and bigger!) Also adds in a place where spacepods are recognized that isnt just the hangar on box.

## Why It's Good For The Game

I think the pictures speak for themselves.
Old: 
image
New: 
image

## Changelog
:cl:
tweak: The old abandoned UFO design around PubbyStation has been taken to NT for recycling. However, it seems another UFO is floating around the station. A bigger mining/scout carrier, the NTSC "Boomer".
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
I wish it was a bit dingier, but it'll do.

**Comment by Vorak2** [comment]
Dont realy like the mining vendor as it opens upp for a lot of stuff and the ORM realy needs to be moved somewhere else as its curent location is ugly and in the way.
would also sugest adding some type of hostile mob to it to balance out the fact it is an evac ship first and foremost. and then the fact is has a lot of quite powerfull loot in it to boot

**Comment by SynnGraffkin** [comment]
Were there any updates made to this, such as possibly adding some form of hostile mobs and maybe adding some more details to make it feel more abandoned such as dirt, trash, cobwebs, ect?

**Comment by Baldir-Odensen** [comment]
you could replace the dining chairs in the cockpit with the shuttle seats.

also remove the back 2 it makes it look wierd

**Comment by CRITAWAKETS** [comment]
The lack of hostile mobs and drit/trash/cobwebs is intentional. As for the first one, it is because the death of a player affects a lowpop station way more than a highpop station. As for the second one, i just wanted a slight mystery as to why such a pristine vessel is just floating about and abandoned.

**Pull request merged**
