### PR TITLE
[Port] All about the slaps

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

This ports face and ass slapping from Citadel, without the obvious horny code. This includes a 0 costing trait, Buns of Steel, which can swiftly stamcrit anyone who attempts to slap your derrière. Slapping costs 3 stamina to use.

To slap someone in the face, select mouth and click them with disarm intent. 

To ass slap, select groin with disarm intent and be behind them.

With the current numbers, Buns of Steel causes 50 stamina damage and 5 brute to the offending limb.

Also, attempting to use disarm related actions while you have more than 50 stamina damage will just show that you're exhausted. This is a measure to inhibit repetitive slapping (see speen abuse).

## Why It's Good For The Game

Slaps are funny. Breaking people's hands with buns of steel is funnier.

image

## Changelog
:cl: BigFatAnimeTiddies
add: You can now slap someone in the face by targeting their mouth with disarm intent.
add: You can now slap someone's booty by targeting the groin with disarm intent, and being behind the target.
add: New trait: Buns of Steel - Cost: 0 - This trait punishes people who dare to slap your booty, while also causing significant stamina damage, as well as some brute damage to the limb that was used.
balance: Disarm actions when stamina is greater than or equal to 50 will incur exhaustion until stamina regenerates. This surely won't bite me in the ass later. 
/:cl:

### CODE REVIEW

**Comment by Epsilos** [comment]
>trait that does actual damage to someone for hitting you
>0 cost
that sounds like a -1 bare minimum

**Comment by Superyodeler** [comment]
> without the obvious horny code

> ports face and ass slapping

**Comment by Superyodeler** [comment]
> 
> 
> > trait that does actual damage to someone for hitting you
> > 0 cost
> 
> that sounds like a -1 bare minimum

Only if you slap their ass

**Comment by SynnGraffkin** [comment]
The obvious horny code being stuff like Nymphos cooming from slaps, Masochisms getting arousal, all that jazz. 

Like Yodel pointed out, it's only a trait for ass slapping since some people won't want to be ass slapped and can opt in for booty training perk that prevents people from slapping said ass.

**Comment by dee-dubya** [comment]
DNM until it's passed a week of public voting

personally indifferent to it but I know this could be very contentious

**Comment by dee-dubya** [comment]
> 
> 
> > trait that does actual damage to someone for hitting you
> > 0 cost
> 
> that sounds like a -1 bare minimum

it's 0 because its meant to function as effective protection from people that want to do this to you, ergo a cost free sign that you do not wish to participate by any means

**Comment by Sparrowbird611** [comment]
Seems a little pointless given the slap emote exists, no? I don't see the reason for adding this.

**Comment by SynnGraffkin** [comment]
Why *slap when you can just DO the slap?

**Comment by Sparrowbird611** [comment]
I see it as a pointless waste of time to add this when we already have an emote dedicated to doing this function effectively.

Additionally, if I understand correctly, you heavily nerfed the disarm intent, which I'm gonna have to say no to. A single stun baton strike or two-three disabler shots will put you at more than 50 stamina damage and prevent the disarm usage.

There's really little point to these mechanics, and I don't see why we need ass slapping or face slapping code when the slap emote exists.

**Comment by dee-dubya** [comment]
PR vote is a draw after a week of voting. Going to just veto this entirely. Reasons being that it's too contentious, and adds nothing of value or critical importance to our gameplay experience.

Save the ass slapping for coomerstation.

**Pull request closed without merging**
