### PR TITLE
Box Facelift 1: AI Core, Grav Gen, Maint Bar.

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

This PR deletes the AI Satellite and moves the AI to the center of the station once again. The Gravity generator was moved to be below the SMES room, using Citadel's map for reference. I've also updated the Maintenance bar to be larger instead of the pitiful 4x4 room it was in. VG was used for reference on how to rebuild the AI core within the bridge.

## Why It's Good For The Game

It makes Box stand out a bit more as I am working on making it hopefully be a more preferred map among players. Considering Box used to have the AI in the center, it would be nice to have them there once again. 

## AI

AI Core includes: 
- AI Integrity Restorer, accessible from the Foyer and making a left. 
- Cyborg Recharging Station, where cyborgs will also spawn round start. 
- AI Upload, where all modules and properly secured similar to how it was previously for Box, and the turret control functions properly. 
- AI Core, which is blocked off via a door that the AI has control of. Everything within the core is powered by the same SMES unit once used on the AI sat, and can receive external power through the station. I double checked to make sure the CE's console couldn't shut off the APCs within the core and that the RD's camera console can see everything within the core. 

image

image

## Maintenance Bar 

The maintenance bar has been rebuilt and furnished by assistants shift to shift, but rumors have it that some people can hear greyshirts screaming from down the tunnels.

image

## Changelog
:cl: BigFatAnimeTiddies
add: The AI core has been relocated to the center of the station, and the gravity generator has been relocated to Engineering. All systems appear to be functional.
del: AI Satellite has been yeeted from existence on Boxstation
add: The maintenance bar has been receiving a lot of work from various assistants throughout every shift, but rumor has it that greyshirts have gone missing and were last seen having a bite to eat there. A Nanotrasen representative was deployed to do an inspection in a recent shift and was served a strange, but still tasty, burger.
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
I'm not sure that the door to the AI's chamber should only be openable by the AI, but since a rogue AI would bolt that door first, it probably won't have a big effect.

**Comment by SynnGraffkin** [comment]
It is no different that Meta's AI sat having a shutter over the door. If it is a malf AI, you can still bust in like your normally would with thermite / deconing walls.

**Comment by Debonaircorsiar** [comment]
You can get through a shutter, with enough time and effort, you can't get through that thicc ass door UNLESS its connected to the AI upload APC, in which you can just disable the atmospherics and crow bar it open but honestly the difference is so negligable its probably not a big deal

Also this makes is significantly easier to get into and destroy a AI now that you can just break 1 R wall and 1 normal wall to get to it, and with a properly made EMP it can easily hit the Core and APC from the bridge

**Comment by Debonaircorsiar** [comment]
also the walls around the core should be reinforced

**Comment by SynnGraffkin** [comment]
I would like to see how things work in a test merge.

**Comment by Debonaircorsiar** [comment]
I think it would need to be a few days long of a test merge to really see the impact of moving the AI back onto the station 

The reason the AIs are all off station in their own mini-sat is because they're too vulnerable on station, they have little to no means to actually protect themselves other then their easily cheeseable, flimsly turrets that you don't even need to break to get through to get to the AI core, the added layer of protection being in space balanced it out enough that they could still have somewhat of a chance of defending themselves from being lynched or destroyed.

**Pull request merged**
