### PR TITLE
5 droonk respritts

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
changes like 5 drink sprites, 4 of them made by bunzel, 1 made by torgiuuuuus
## Why It's Good For The Game
better sprites are better
## Changelog
:cl:
imageadd: added a better allied cocktail sprite by Tergius
imageadd: new sprites for quadsec, quintuplesec, manly dorf, and tequila sunrise by Bunzel
imagedel: the old allied cocktail, quinsec, quadsec, manly dorf, and tequila sunrise sprites
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
You changed the wrong .dmi. Make your changes to drink sprites in the waspstation icons folder.

also I was going to do this you fuck

**Comment by TheNeoGamer42** [comment]
the old allied cocktail was in the current drinks.dmi, and no, terg DMed me it so beat it moth

**Comment by triplezeta** [comment]
ok but the new allied cocktail should go in the modularized folder, along with all the other resprites, *because the drinks were repathed in PR #395 to use the modularized folder.*

**Comment by TheNeoGamer42** [comment]
should I just delete the drinks.dmi in the not waspstation folder then

**Comment by triplezeta** [comment]
you probably could and it wouldn't affect anything to my knowledge, though there could be other things I don't know about that uses that .dmi for icon reference

**Comment by TheNeoGamer42** [comment]
ok so should I or should I not

**Comment by triplezeta** [comment]
went back to check and there's a few things outside of drinks.dm that path to the original icons folder, so I don't recommend deleting it.

**Comment by TheNeoGamer42** [comment]
ok well now its changed in both DMI files so you can't complain now

**Comment by triplezeta** [comment]
based

**Comment by MarkSuckerberg** [comment]
image
if possible please remove the changed icon in the unmodularized icon and redirect the drink's icon in code to the modularized one

**Comment by TheNeoGamer42** [comment]
after forgetting this existed for like 7 days I reverted the changing of the not modularized

**Comment by TheNeoGamer42** [comment]
pretty sure the drinks are already redirected to the modularized folder too

**Comment by TheNeoGamer42** [comment]
bunzel threw srpits at me so I did moar

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
