### PR TITLE
Tool Resprite

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
image

Resprites all the base tools (screwdriver, welding tool, crowbar, wrenches, wirecutters)! New sprites entirely done by @triplezeta!

## Why It's Good For The Game
It looks really good, and it helps differentiate us from /tg/.

## Changelog
:cl:
imageadd: all base tools have new sprites!
imageadd: all old sprites are still used as `tool/old` and are used only in the traitor assistant's ancient toolbox.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
fwa.

**Comment by dinnerwoerror** [comment]
look at how they massacred my boy

**Comment by MarkSuckerberg** [comment]
pr #100 woo yea oh yea

**Comment by ADepressedPyroshark** [comment]
Wake me up when we get 250 prs

**Pull request merged**
