### PR TITLE
Adds Maint Access to all Jobs.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Do I need to explain this?

I'm not 100% confident on this PR, so if you have arguments against it, please, bring them. My logic is that if the lowest person on the rung, assistants, get maint access, everyone else is entitled to that as well. I'd like some thoughts on this though.

🆑
add: All jobs now have maintenance access.
/🆑

### CODE REVIEW

**Comment by ADepressedPyroshark** [comment]
Whats the point of emergency maint access then?

**Comment by Sparrowbird611** [comment]
There is little point to the mechanic if this changes. It could be used in case someone's ID was lost or stolen, but otherwise it would be largely useless.

**Comment by SynnGraffkin** [comment]
Not every job needs maint access, putting a hard "No" from me here.

**Comment by Sparrowbird611** [comment]
Then by your very logic, we should remove it from assistants, since they don't need maintenance access.

**Comment by SynnGraffkin** [comment]
game config exists 
image

**Comment by Sparrowbird611** [comment]
Apologies then, I didn't know that was a thing.

**Pull request closed without merging**
