### PR TITLE
Digi-magboots

### PR DESCRIPTION
**Pull request by MaltVinegar**
Adds digitigrade magboots which can be welded into shape and makes CE's magboots and Syndie magboots able to be toggled between being digitigrade and normal, it also adds a way to make shoes able to be worn by people with digitigrade legs and plantigrade legs though it isn't used.

Why it's good for the game

These are fairly important clothing items that shouldn't just exclude certain people from wearing them.

## Changelog
:cl:
add: Digitigrade magboots, normal, syndie, and advanced varieties
add: Adds a way to make shoes wearable by those with digitigrade and plantigrade legs
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
ok since icondiffbot is being a bitch here's the new sprites for stuff (redundant mob sprites not shown)
magbootshowcase

**Review by triplezeta — APPROVED** [review]
sprites are mine therefore good

**Comment by MaltVinegar** [comment]
I can finally sleep

**Comment by AsciiSquid** [comment]
\*Suffers in squid noises*

**Comment by Superyodeler** [comment]
blub blub

**Review by Maldaris — APPROVED** [review]

**Pull request merged**
