### PR TITLE
More Borg Icon Selections DAMMIT!

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

I had to look at Citcode in order to properly get the icons to show via modularization.

This ports the VG cyborg icons and selection options for various modules.

image

Left to right: Standard, Engineering, Service, Janitor, Medical, Security, Mining 
Top to bottom: 
Sleek series 
R34 Series 
Noble Series 
Marina Series 
Droid Series 
"Antique" Series
Not sure what to call these are than #number boxboy Series

Misc: Spider is Standard, Engiseer is Engineering, HAN-D is Janitorial, Mechaduster is Janitor, Needles is Medical, Securitron is Security, Wall-A is mining, Wall-E is Engineering, EVE is Medical.

"Default" borgs are what we can recognize as defaults in TG code.

## Why It's Good For The Game

Adds more choice for silicon players when selecting a module.

## Changelog
:cl:
add: Ports VG cyborg appearances.
/:cl:

### CODE REVIEW

**Comment by ADepressedPyroshark** [comment]
Bro service gets a ghost as droid that pretty wild

**Comment by dee-dubya** [comment]
Before this gets merged, I'd like to see the green highlights on medborgs be replaced with the light blue that the department is associated with. Theming and consistency are more important than one might think.

**Comment by SynnGraffkin** [comment]
@dee-dubya I don't really think that is entirely necessary, since almost every medical module there is a form of sterile white compared to the rest of the models for each series.

**Comment by kurpingspace2** [comment]
Add wormbot from uriststation or I kill you

**Comment by ADepressedPyroshark** [comment]
> 
> 
> Add wormbot from uriststation or I kill you

send pics

**Comment by kurpingspace2** [comment]
i don't know where the sprites are but it looks like this https://cdn.discordapp.com/attachments/653381375272943649/654192238036779019/unknown.png

**Pull request merged**
