### PR TITLE
the lieutenant finally gets an office at the expense of someone who never deserved it

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

the lawyer is evicted from their office because they're a piece of shit that never deserved it, so they voluntarily gave it to the lieutenant who's had their locker weirdly located in the ass crack of the bridge for the longest time

## Why It's Good For The Game

the lieutenant gets an office with their own fax machine and recharger and all the other nice things

the lawyer is made even more irrelevant and is relegated to a nearby maintenance tunnel

## Changelog
:cl:
add: the lieutenant's office
remove: the lawyer's office
/:cl:

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
margent tell me if i missed something

**Comment by Vorak2** [comment]
How about you switch places there and give your new sec oficer the maint room.

**Comment by dee-dubya** [comment]
Doesn't literally every map have a vacant office that could be repurposed for the lieutenant, assuming we even decide to keep the lieutenant?

**Comment by Baldir-Odensen** [comment]
windows is a sec man
he hates the lawyer and as soon as someone came up with the idea of merging the lawyer and luitenant he jumped on it and wanted to give the luitenant the lawyers office so the luitenant who isnt officialy a sec officer and turn him into a sec suport role simular to the detective

**Comment by dinnerwoerror** [comment]
haha, controversial! do not merge! moth!!

**Pull request closed without merging**
