### PR TITLE
[Cit Port] Randomized Box Engine

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Sauce:
[Make Box's Engine be randomised between SM, Tesla and Singulo V2 [TEST-MERGE]](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10245)
[Allowed random engines to be weighted]( #10463)

Ports Citadel's random engine system for Box, and their framework for station "ruins" that can be expanded upon to make maps become more varied.

## Why It's Good For The Game

More engine variety than just a standard SM is good. Each engine also has a weight for how often it may occur, which can be changed in the config.

BOX_RANDOM_ENGINE Box SM,3 - Standard SM
BOX_RANDOM_ENGINE Box Tesla,3 - Standard Tesla
BOX_RANDOM_ENGINE Box Singulo,3 - Standard Singulo
BOX_RANDOM_ENGINE Box SM 1x3,1 - Non-standard one by three SM
BOX_RANDOM_ENGINE Box SM 5x5,1 - Non-standard five by five SM
BOX_RANDOM_ENGINE Box SM 3x,0 - Glorious NT blessing us with THREE supermatter crystals to make spicy
BOX_RANDOM_ENGINE Box TEG,3 - A robust TEG setup, devised by @MrJWhit 
BOX_RANDOM_ENGINE Box Empty,0 - Just an empty room, which can be good for those who want to build their engine from scratch.
BOX_RANDOM_ENGINE Box Antimatter,1 - A dedicated spot for an underappreciated piece of legacy technology.
BOX_RANDOM_ENGINE Box P.A.C.M.A.N,1 - You get a room full of SMES units and Pacman units.

## Changelog
:cl: BigFatAnimeTiddies
add: Citadel's framework for randomized "station ruins".
add: Boxstation engine can now be randomized between a select few engine setups, such as the Supermatter, Tesla, Singulo, and TEG.
tweak: Minor wiring changes on Box
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
This looks like a mapdiffbot issue

**Comment by SynnGraffkin** [comment]
Yeah, mapdiff bot doesn't like it. Currently testing the engines right now.

**Comment by SynnGraffkin** [comment]
Every map tested and every engine spawns and works correctly. The only issue right now is the Tesla / Singulo airlock controllers are being jank and try to scan both doors as interiors and not one or the other.

**Comment by Superyodeler** [comment]
It might be because it's enclosed??? I'd need to look at the monstermos source, and from what I've glanced at, it doesn't look very well documented.

**Comment by SynnGraffkin** [comment]
It's weird because the same airlocks work on Empty and TEG.

**Comment by SynnGraffkin** [comment]
AAC issues should be resolved in #391

**Comment by SynnGraffkin** [comment]
Tested locally and AAC works fine on the Singulo / Tesla maps.

**Comment by SynnGraffkin** [comment]
Which is kind of odd because this was the last known work I can find about engine weights on Cit. 
[Allowed random engines to be weighted](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10463/files)

**Comment by SynnGraffkin** [comment]
I asked Putnam and they told me there was a fix for 0 weights. @Superyodeler 
Should work now.
[made engine rotation properly blacklist 0-weighted ones #10725](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10725)

**Comment by SynnGraffkin** [comment]
Fixed the DME conflict, we good to marg?

**Pull request merged**
