### PR TITLE
New Space Ruin: The Space Gym

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

This adds a space gym ruin that has a possible chance to spawn, as long as it is enabled in the config.

image

## Why It's Good For The Game

This basically ports the Space Gym ruin from VG, and we lack gachi memes outside of the Jabroni outfit.

## Changelog
:cl: BigFatAnimeTiddies
add: A new space ruin can be possibly located near the station, known as the Space Gym.
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
Gachi gang

**Comment by SynnGraffkin** [comment]
Well screw you, bot

**Comment by Superyodeler** [comment]
Looks like you're still working on the outfits

**Comment by SynnGraffkin** [comment]
More so just trying to get it to not runtime. It works fine.

**Comment by Superyodeler** [comment]
Wierd

**Pull request merged**
