### PR TITLE
JUMPKILTS - They may take away our lives, but they'll never take our freedom!

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Blame @AsciiSquid for this; Skirts are lame, but rather than remove them out right (because fuck your trap degeneracy) _we make them manly kilts_.

## Why It's Good For The Game
Anti-Horny: the PR
## Changelog
:cl:
refactor: Jumpskirt -> Jumpkilt
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
yems

**Comment by Picklesoup** [comment]
mald really do be trying to make a reason to put a skirt on their character smh........

**Comment by dinnerwoerror** [comment]
plasmamen will always keep the skirts

**Comment by AsciiSquid** [comment]
Aye

**Comment by Maldaris** [comment]
> mald really do be trying to make a reason to put a skirt on their character smh........

nah I just want a reason to take one off yours. 😏

**Comment by kurpingspace2** [comment]
cringe just remove them smh

**Comment by dee-dubya** [comment]
why

**Comment by TheNeoGamer42** [comment]
because why not

**Comment by triplezeta** [comment]
based

**Comment by Picklesoup** [comment]
> 
> 
> > mald really do be trying to make a reason to put a skirt on their character smh........
> 
> nah I just want a reason to take one off yours. 😏

I THOUGHT THIS WAS ANTI-HORNY :flushed:

**Pull request closed without merging**
