### PR TITLE
Squidpeople

### PR DESCRIPTION
**Pull request by AsciiSquid**
## About The Pull Request
Brings back the squidpeople, with some added flair.

Added calamari so they no longer produce human meat.
Rylethian now appears as Minecraft Enchantment Table to non-speakers.
Squid gang squid gang

## Why It's Good For The Game
Squid gang squid gang

## Changelog
:cl:
add: Squid gang returns
/:cl:

### CODE REVIEW

**Comment by Baldir-Odensen** [comment]
Yees they truly speak enchantment table

**Comment by MarkSuckerberg** [comment]
Try merging the master again, it should work. Other than that, it's all good.

**Comment by MarkSuckerberg** [comment]
:/ I think that's just the codebase being fucky. Your PR is fine, as far as I can tell.

**Comment by MarkSuckerberg** [comment]
WE DID IT LADS

**Pull request merged**
