### PR TITLE
griefs the server

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
griefs the server
grief

## Why It's Good For The Game
do you really think it is
## Changelog
:cl:
add: grief
del: nongriefy things
tweak: griefs the server
server: griefed
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
coder fools was like 2 weeks ago

**Comment by Maldaris** [comment]
June 10th was Coder Fools. Late to the party.

**Comment by TheNeoGamer42** [comment]
I did this joke on coderfools too, but mald said grief the server

**Comment by Maldaris** [comment]
> I did this joke on coderfools too, but mald said grief the server

So you've got poor timing AND you're unoriginal 👀

**Comment by dee-dubya** [comment]
oh no

**Pull request closed without merging**
