### PR TITLE
Solgov offices on metastation

### PR DESCRIPTION
**Pull request by theboy6545**
## About The Pull Request

Adds solgov offices where the firing range is for the solgov dude

## Why It's Good For The Game

The funny man needs his funny office

## Changelog
:cl:
add: SolGov Representative office to Metastation.
del: Meta's Firing Range
/:cl:

### CODE REVIEW

**Comment by theboy6545** [comment]
yes i know my changelog is bad i shall fix it when i've done with the changed

**Comment by theboy6545** [comment]
I am gonna go to mr github and steal him and everything he values

**Comment by theboy6545** [comment]
Alright we're ready for the funky times

**Review by MarkSuckerberg — APPROVED** [review]
Looks good!

**Pull request merged**
