### PR TITLE
Merge moth, and spider eyes into compound eyes

### PR DESCRIPTION
**Pull request by Jack7D1**
## About The Pull Request
This will remove spider eyes and moth eyes, replacing them with new compound eyes.
New eyes will be identical to spider eyes.

## Why It's Good For The Game
Gets bug eyes all together and centralized

## Changelog
:cl:
remove: Removes moth eyes and spider eyes.
add: Adds compound eyes, which are flash vulnerable and have some nightvision ability.
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
hobld on can someone find the bug eye sprites i made a while back that never got added i didnt save them theyre on the dscirdo somewhere @triplezeta

**Comment by triplezeta** [comment]
image
image

**Comment by Jack7D1** [comment]
@tiramisuapimancer ooo, I'll try to find!

**Comment by tiramisuapimancer** [comment]
Thank u zeta

**Comment by triplezeta** [comment]
too late, moth

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by MarkSuckerberg** [comment]
Passed the vote, merging.

**Pull request merged**
