### PR TITLE
Porting my ruins

### PR DESCRIPTION
**Pull request by Vorak2**
## About The Pull Request

ports most of the ruins I made on bee with some small fixes like removing the alien aloy golem att the entrance of the power puzzle. should be working now.
power_puzzle
macspace
Asteroid

## Why It's Good For The Game

More ruins more fun and I am 90% shure they are working
## Changelog
:cl:
add: A fast food restaurant has gone dark in your area the last message from the establishment said something about plushies
add: A secure storage site that has been depowerd and abandoned for years has floated into your area it is said to contain some rare items
add: an asteroid mining operation in your area has gone dark after reports of monsters being active in the area bee on the lookout for it as the last report stated they had a considerable amount of ores in the base

/:cl:

### CODE REVIEW

**Comment by Vorak2** [comment]
Not 100 on if my modularisation of the areas worked but as I said I cant test it fully so input on that is needed

**Comment by Vorak2** [comment]
> Your areas should probably be under waspstation/code/game/area/areas/ruins/space.dm so it can be similar to match the code folder.
> 
> image

Gitkraken is not coperating with me so I cant fix this as of now. might se if I can get things working on another computer but that might take time.

**Comment by Vorak2** [comment]
The reson I did not do the entire Ladder of folders as I didnt think we will need the entire ladder due to uss probably not going to need that manny new areas

**Comment by SynnGraffkin** [comment]
It's easier to just do the entire ladder since this is expanding upon the existing space ruins areas.

**Comment by SynnGraffkin** [comment]
This just makes me irritated. 

image

Also @MarkSuckerberg , Linter machine broke.

**Comment by Vorak2** [comment]
I do think that was the correct thing for file pathing to ruin maps. Though I agree it is somewhat irritating and probably unnecessary as these are new maps and if there is a change it wont matter if they are modularised.

**Comment by Superyodeler** [comment]
I got the same linter error in my pr.

**Comment by Maldaris** [comment]
So there's [this issue](https://github.com/storybookjs/storybook/issues/10477) upstream with babel, looks like there's something funky going on with the cache/CRAs for this particular package. The strategy would be to `npm update` inside the JS directory, `rm -rf ./node_modules` then run `npm install` again.

If need be I can get this in as a separate PR, @MarkSuckerberg

**Comment by Maldaris** [comment]
Fix for build issue is in #237

**Pull request merged**
