### PR TITLE
Ports Yog mice and reverts TG #48558

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Ports: [[BOUNTY] Yogstation Mouse Expansion pack, only 19,99$
](https://github.com/yogstation13/Yogstation/pull/7838)
Reverts: [Mice will now eat cheese slices, resulting in a mouse problem.](https://github.com/tgstation/tgstation/pull/48558)

## Why It's Good For The Game

Gives people another ghost role to mess around with.

Features:
- They can't chew wires (only player controlled)
- They hide under items now (only player controlled)
- They only have 15 health
- Night vision
- They can't pull items
- They can't push items
- They can pass under airlocks like drones
- They have their own language now, others can only understand it as Squeak? or Squeak!(its all in the microtone variations man)
- AI turrets now ignores mice
- They can eat stuff by control clicking it and waiting 3 seconds, during that time, they lose their ability to hide, they can eat trash,vomit and food that is not secured on tables
- Each food item eaten heals 5 damage except for cheese which does 10
- When eating an item while already healed, the remaining HP will go into a global counter that when it hits 35 spawns a new mouse in maint
- Mouse traps now hide under items, it also only does between 7 and 12 damage to player controlled mouse instead of an instant kill
- When a mouse eats cheese, they become THICC(bigger sprite), have doubled health and double speed for 3 minutes after which they become back normal
- Walking on the same tile as drinks or beakers not on tables will make the contents fall over

## Changelog
:cl:
add: Yogstation Mice possession
del: Mice repopulating from cheese eating PR from TG
/:cl:

### CODE REVIEW

**Comment by dee-dubya** [comment]
we are the rats

**Comment by Superyodeler** [comment]
As someone who plays a lot of chef this sounds terrifying.

**Comment by SynnGraffkin** [comment]
Who else is gonna eat all that food? Actual crew? :^)

**Comment by Superyodeler** [comment]
It hurts, but that's the truth.

**Pull request merged**
