### PR TITLE
Wig suicides drop items

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

When certain non-human species attempt acts to terrible to contemplate and are justly smitten from this world, whatever force safeguards us from their monstrous acts is gracious enough to leave their items behind.

Also organizes the code a little.

## Why It's Good For The Game

I didn't consider important items being lost when creating wig suicides, this fixes that.

## Changelog
:cl:
fix: wig suicides drop items
code: organized wig suicides
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
I'm the force that safeguards you from their monstrous acts
on my honor we will never see moth hair here.

**Comment by FancyCyclops** [comment]
Moth hair!

**Comment by Superyodeler** [comment]
I'll fix this tomorrow.

**Comment by Superyodeler** [comment]
Apparently this is just Travis being dumb.

**Pull request merged**
