### PR TITLE
Reverts the TG changes that made mimes unable to PDA anyone anything other than emojis

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
Reverts https://github.com/tgstation/tgstation/pull/47177 and https://github.com/tgstation/tgstation/pull/47420
## Why It's Good For The Game
Mimes can actually PDA people something meaningful again. Also Mark SAID they were gonna do it but I did it first
## Changelog
:cl:
del: The PDA emotes that only mimes could use
tweak: Mimes can now use WORDS (on PDAs)
imagedel: Deleted the image files for said PDA emotes
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
it would be really funny if you made pda emojis usable by everyone instead of flatout removal

I want to spam emojis to everyone with the lawyer cart

**Comment by TheNeoGamer42** [comment]
yeah uh based on the way it was coded, it looked like it fucking stripped out any text that WASNT emojis, and well, it was already a pain to fuckin remove

**Comment by TheNeoGamer42** [comment]
but if I knew how to make em usable to everyone, I would, but I probably couldn't without running into a shitton of issues caused by the fact it was hardcoded to remove any non emoji text

**Comment by triplezeta** [comment]
from looking at the code with my extremely limited knowledge of how this works, it appears that text sanitation only applies due to the emoji_sanitize proc. I would have to test this myself in order to see if it's possible to remove that and make emojis available to everyone easily.

**Comment by TheNeoGamer42** [comment]
it was also variable based so you would probably need to try to tack that variable onto ALL PDAs or just something else I guess, and well, gitkraken decided to not cooperate anymore and I cant go to master branch

**Comment by triplezeta** [comment]
couldnt you just add it to the base PDA that every other PDA is a child of

**Comment by TheNeoGamer42** [comment]
I mean, yeah, but also, gitkraken machine stopped working

**Comment by triplezeta** [comment]
how did you make the pr doe...

**Comment by TheNeoGamer42** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh I did it before it broke

**Comment by dee-dubya** [comment]
didn't we already decide that this wasn't coming back

pick literally any other role that isn't a fucking mute if you want to communicate using words, or break the mime vow

**Comment by TheNeoGamer42** [comment]
Nobody ever told me that this wasn't coming back, and mark said something about doing it, so I did it with my spare time, also why SHOULDN'T a mime be able to use PDAs, its not like the guy who can't speak can't text on a phone like a normal person

**Comment by AsciiSquid** [comment]
Mimes can't PDA for the same reason they can't use sign language with the me verb. It's a sidestep to the entire gimmick of mimes not talking.

If you want to communicate with people without being creative about it you can pick any other job.

**Comment by Victor239** [comment]
It's not a sidestep at all when PDAing is slower, more inconvenient, can only be used 1:1, can't use department channels etc. 

It's already hugely limited, so making it out like there's mimes who totally avoid the gimmick is not reality.

**Comment by TheNeoGamer42** [comment]
No PDA means they basically can't do shit at all in terms of interacting with people not directly infront of them, such as, say, the AI, who they basically cannot interact with in any way since PDAs are basically fucking useless to them as they are now

**Comment by triplezeta** [comment]
you can show papers to cameras



it's very effective at annoying the absolute hell out of the AI

**Comment by TheNeoGamer42** [comment]
yeah but thats what prisoners do

**Comment by triplezeta** [comment]
it's still a way of communicating with the AI effectively. I've seen mimes do it all the time.

**Comment by TheNeoGamer42** [comment]
I can almost assure you that 90% of AIs who have dealt with perma prisoners tryna spam their camera with a paper of LAW 2 AI OPEN DOOR will ignore any and all papers shown to cameras

**Comment by triplezeta** [comment]
that's because releasing perma prisoners out of prison is a potential law 1 violation

**Comment by TheNeoGamer42** [comment]
I still don't really see why they SHOULDN'T be able to PDA people other than "haha mime can't speak!!!"

**Comment by triplezeta** [comment]
also can i put this up for a vote already

**Comment by TheNeoGamer42** [comment]
not like I would stop you, so, yes?

**Comment by dee-dubya** [comment]
There are two very simple methods for avoiding this scenario that don't involve removing a cool and flavor-based feature. A feature that also happens to prevent people from sidestepping **the entire point of the role**.

https://i.imgur.com/Tesynsa.png
https://i.imgur.com/8InRYJR.png

If you hate not being able to use traditional communication methods, **don't pick the role specifically designed to not use traditional communication methods**. If it's important enough that you absolutely need to communicate with people normally, it's important enough to temporarily break your vow of silence over. As an aside, mimes are NOT auto-valid here for breaking their vow of silence. All you lose is your ability to use your mime powers...and your dignity.

**Comment by TheNeoGamer42** [comment]
The code was hardcoded to make having emojis not allow any normal text at all, and I don't know byonds shitcode enough to make it actually able to allow everyone to be able to use it and still PDA properly, also I don't think you should be able to veto it when it has more upvotes than downvotes

**Comment by dee-dubya** [comment]
It's also worth noting that there is already a method ingame for mimes to PDA people normally, making this PR for the most part entirely pointless.

**Comment by MarkSuckerberg** [comment]
Upon *actually looking at* the code, I realized that it's linked to the PDA itself, and not the mime mob in question. That means you can either ask the HoP for a new one or print/find another one.

**Comment by AsciiSquid** [comment]
> I don't think you should be able to veto it when it has more upvotes than downvotes
We wouldn't need to veto a pr that's already voted down. Secondly since the emoji thing is tied to the PDA itself just get a normal one if you want to break your vow so badly.

**Comment by Maldaris** [comment]
This has been vetoed by @dee-dubya, closing.

**Comment by Superyodeler** [comment]
There was more discussion on this in the dev channel.

**Comment by dinnerwoerror** [comment]
oh boy are we gonna be trading shots now where one tribe keeps closing the PR and another tribe keeps reopening the PR

**Pull request closed without merging**
