### PR TITLE
Hyper-Gamer Dev-Tool (For Mapper Chads ONLY) 2025 BLUESPACE Edition (Turf Decals and Medians)

### PR DESCRIPTION
**Pull request by MrFagetti**
image
(Old image but still relevant, note not all decals are shown)

Sup gamers

## About The Pull Request

Adds prefab decals, plus some smaller decals for your mapping pleasure. This is mostly a resource for mappers so they can decals floors faster and more engine-efficient (So instead of four corners it's one whole decal, making it faster for you to place and faster for the engine to add)

Medians are for making more specific changes to the floors, adding very small detailing to and otherwise making the floor look more smexy.

## Why It's Good For The Game

Makes mapping atad faster, plus some of the new decals are pretty noice, if I say so myself. As for medians, overall makes the floors abit less boxy (of done properly).

## Changelog
:cl:
add: Prefab Decals
add: Small new Decals
add: Medians
/:cl:

### CODE REVIEW

**Comment by Maldaris** [comment]
@triplezeta @SynnGraffkin I'd like you guys to take a look at this one and evaluate it based on how our existing mapping works, and if it's:
A) An improvement
B) Valuable addition
We've had issues with decals everywhere in the past, really the people who map the most should have a direct voice in this.

**Comment by triplezeta** [comment]
biggest issue with decals is the sheer number of them on maps, with Delta having the most and Kilo having the greatest density of them

https://github.com/tgstation/tgstation/issues/53798 <- this goes into more detail on the problems with them

I support this because it means the overall number of decals needed to detail a station goes down :thumbsup:

**Comment by MrFagetti** [comment]
NarrowHauntingFlyingfish-small
NICE FLOOR

**Comment by Maldaris** [comment]
> NarrowHauntingFlyingfish-small
> NICE FLOOR

up next: Beetlejuice clown suit

**Comment by SynnGraffkin** [comment]
I'm not particularly fond of decals being adhered to the tiles. Even though decaling is a pain in the ass at times, having the freedom to just go over a blank tile with decal is preferred, imo.

**Review by Maldaris — APPROVED** [review]

**Comment by MrFagetti** [comment]
Merge or non?

**Pull request merged**
