### PR TITLE
adds oganesson

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

adds oganesson and the ability to make oganesson and also a cargo bounty for oganesson so that it has a reason to exist

the reason why my branch is called ram ranch 5 is because that was the song i was listening to when i started making this, i'm on ram ranch 17 now

other than that there is no other reasons why oganesson is being added

nope, none at all, i swear on me mom, really, no other reasons whatsoever that i could possibly perceive of

## Why It's Good For The Game

this pr is good for the game beacuse its my first time coding so tell me if i did something wrong and also it adds to cargo so that too

## Changelog
:cl:
adds oganesson as a reagent
also adds the ability to make oganesson by mixing togethor corazone and calomel
also also adds oganesson as a cargo bounty so that it has a reason to exist
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
But why tho

**Comment by dinnerwoerror** [comment]
i did it because i could

**Comment by Baldir-Odensen** [comment]
It does nothing and serves no point

**Comment by dinnerwoerror** [comment]
but it's got a cargo bounty to go with it

**Comment by MarkSuckerberg** [comment]
Sorry, but it failed the vote.

**Comment by dinnerwoerror** [comment]
damn, well, this kind of was a test run anyways, this was just kind of me figuring out how git hub worked, it's not like i was expecting it to pass

**Pull request closed without merging**
