### PR TITLE
Steppy, the Cargonian Gator

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Adds a Steppy, an alligator, as a new cargo pet, and a related propaganda poster.

## Why It's Good For The Game

Fuck paperwork. Hail Cargonia.

## TODO

- [x] Add Steppy
- [x] Sprite approval/tweaks
- [x] Replace Paperwork with Steppy on maps.

## Changelog
:cl:
add: Steppy, the Cargonian Gator.
add: A contraband poster depicting Steppy and his slogan.
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
🤖🔫

**Comment by Maldaris** [comment]
@triplezeta still needs dithering, yeah?

**Comment by triplezeta** [comment]
Yes

**Comment by Maldaris** [comment]
Was test-merged for a couple rounds, works fine.

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
