### PR TITLE
The Infamous "Sword of the Meth-King"

### PR DESCRIPTION
**Pull request by AsciiSquid**
## About The Pull Request
Adds blade of the grey-king, an infamous weapon used during the 'Grey Tide' rebellion of 2532. Forged using spare razor-blades and cheap replica swords. Then ritually soaked in every narcotic on the Solar Government *Prohibited Substances Regiment*, along with several drugs they don't even know about.

Getting attacked by this weapon yields a high risk of pricking yourself on one of the many drug-soaked tips, resulting in a trace amount of narcotics to enter your bloodstream.

This relic of chaos and war is now available as an Assistant/Chemist restricted traitor item (2 TC) or found as legendary maint loot.

## Why It's Good For The Game
Only real piece of code to survive my since-deleted black market overhaul. Might as well put it to use.

## Changelog
:cl:
add: Added sword that is also drugs.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
finally

**Comment by Superyodeler** [comment]
I like this. You should add the bit about razor blades to the desc.

**Comment by AsciiSquid** [comment]
The price is due to a number of the reagents it can inject you with are beneficial mid-combat (pump-up, earthsblood, etc) meaning its generally unreliable as a weapon

**Comment by triplezeta** [comment]
add to black market :flushed:

**Pull request merged**
