### PR TITLE
Weaponry tweaks

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Probably going to piss people off, but that's what happens when you rebalance shit.

Performs numerous weapon rebalances, which I'll go over here. Description updated to include new changes.

X-ray laser AP buffed to 40.

Xeno sentinel neuro spit stats changed. It no longer hardstuns, and instead deals 60 stamina damage, a 3 second knockdown, and 3 seconds of eyeblur.

Removed the damage dropoff on makeshift shotgun shells (not that any one uses them any way.)

Decreased stamina damage on the disabler and rubber revolver rounds to 20.

Reworked the hybrid taser, the alt mode now fires weak lethal bolts instead better stun projectiles.

Removed all instances of the commander, the lethal mode on the taser will suffice.

Reworked the shotgun taser slug, it now inflicts 4 seconds of knockdown, 45 stamina damage, and only travels four tiles.

Heavily nerfed shotguns. Damage was decreased on buckshot and slugs (stamina and regular types) and are afflicted by damage falloff.

Nerfed batons a bit. Regular stun baton does 40 stamina damage, the other types now do 35 and don't instant knockdown. Regular baton still has delayed knockdown because I couldn't figure that bit of code out.

Third pass complete, ghosting time.

### CODE REVIEW

**Comment by triplezeta** [comment]
> X-ray laser AP buffed to 40.

dont really see a purpose for this, as the X-ray laser already has a pretty strong niche, but I guess it's fine

>Xeno sentinel neuro spit stats changed. It no longer hardstuns, and instead deals 60 stamina damage, a 3 second knockdown, and 3 seconds of eyeblur.

based 

>Removed the damage dropoff on makeshift shotgun shells (not that any one uses them any way.)

based

>Decreased stamina damage on the disabler and rubber revolver rounds to 20.

...Cringe. Rubber revolver rounds are now *worse* at takedowns than lethals are. 

>Removed all instances of the hybrid taser, returning the disabler as the standard issue weapon.

Don't mind this one personally as even our nerfed tasers are unbased cringe that will takedown faster than a stun baton could ever hope to, though I'd prefer a rebalance of taser shots.

>Removed all instances of the commander, and gave no replacement.

Grade A Cringe. The commander is supposed to be the lethal last resort for security officers, and ammo isn't given to them roundstart. Removal of this will make security officers unable to deal with threats that nonlethals cannot handle.

>Reworked the shotgun taser slug, it now inflicts 4 seconds of knockdown, 45 stamina damage, and only travels four tiles.

based

**Comment by Sparrowbird611** [comment]
Forgot about the lethal rounds, I will look into this ~~by removing the detective's revolver~~ and possibly rebalance it ~~by making the detective's revolver deal 20 lethal dmg instead~~.

X-ray laser was due to the fact that I felt it would have far too much trouble penetrating armor. I will look into the stats on the x-ray rifle further if it's an issue, but I frankly don't see much problem giving it AP.

Commander removal is due to my own personal belief that people will escalate to their most lethal weapon at the slightest sign of opposition, which has been proven to me time and time again on multiple servers, including boomer. I see little reason to give security access to roundstart lethals, so I took them away. They may use the armory to acquire lethal weaponry if they must, and they have more than enough tools to escape stun resistant targets, including bolas, flashbangs, and other equipment.

Also, all security castes spawns with a mag in their backpack according to the code.

**Comment by Maldaris** [comment]
>Removed all instances of the hybrid taser, returning the disabler as the standard issue weapon.

>Removed all instances of the commander, and gave no replacement.

Both of these are bad, here's why:

Hybrid taser gives an alternate weapon for seccies to use other than disablers. There's no reason to remove them, and I've yet to see anyone complain about their use. If that is not the case please correct me.

Commander is NOT a great pistol lets be real here. It's a stock WT-550 with less ammo, and less accuracy/ROF. As far as lethals go it is tame. If we want to rework how these are issued, that's fine, but realize seccies start with A) Just the magazine, and B) only one magazine available to them without armory access. The few times I've seen it deployed, it didn't go well for the security officer.

>Commander removal is due to my own personal belief that people will escalate to their most lethal weapon at the slightest sign of opposition, **which has been proven to me time and time again on multiple servers, including boomer**.

Calling bullshit on this one.

As a point of policy: if you're going to remove content, you need to replace it with something. There is little enough actual content in most departments (especially sec) to justify wholesale removal. 

In addition, we have escalation rules in place. Citing overescalation as a reason to remove content is not justifiable, as the response to instances of that is admin involvement.

**Comment by SynnGraffkin** [comment]
Don't commanders spawn in security lockers in the equipment room and Sec off spawn with just the mag? Further magazines would need to be obtained from the armory lethal locker.

**Comment by Maldaris** [comment]
> Don't empty commanders spawn in security lockers in the equipment room and Sec off spawn with just the mag? Further magazines would need to be obtained from the armory lethal locker.

Correct.

**Comment by MarkSuckerberg** [comment]
Also I still don't know why nobody has said anything about the fact the locker in the armoury spawns with a little more than 12 full commander mags for some reason

**Comment by Maldaris** [comment]
> Also I still don't know why nobody has said anything about the fact the locker in the armoury spawns with a little more than 12 full commander mags for some reason

Because the shotgun don't miss.

**Comment by Sparrowbird611** [comment]
We were supposed to have left the age of the golden bolt behind, and reworked the HoS gun to be less oppressive in it's hardstun mode, but some absolute smoothbrain decided to give it back to the security staff. This was idiotic. Security already has numerous options for dealing with all situations, they did not require extra "options" in the form of a two shot disabler. The one downside is that it's got "low" range of seven tiles, but it inflicts slowdown in a single shot and makes the baton redundant. We do not need redundant "content."

The commander doesn't need a replacement when it should not have been added in the first place. Security does not need roundstart lethal weaponry. The only justification I've received for them having it are stun immune people, which are countered by bolas and the dragnet and simple mobs, which are seldom a threat and the armory is meant to kill those. There is no reason for officers to have roundstart access to a lethal firearm.

I'll be handling shotguns shortly. Not missing won't do you much good with damage falloff existing.

**Comment by Sparrowbird611** [comment]
You cite "improve don't remove," but the disabler did not need improvement, and security officers didn't need a lethal firearm to improve their power level. Officers already have so many options to take down criminals, they do not need these new ones with questionable design decisions behind them.

I will be reverting the disabler and rubberround nerf shortly.

**Comment by Maldaris** [comment]
>they did not require extra "options" in the form of a two shot disabler. 

If you have a problem with the "golden bolt" efficacy that's one thing. 

Also, your hint was on the tin: The BoomerStation theme often means old stuff is back on the table to revisit, rework, and enjoy again. The hybrid taser PR was voted on and passed.

https://github.com/WaspStation/WaspStation-1.0/pull/273 For reference here is the original PR. If you see something in the description there that isn't actually what's going on in the game, please feel free to point it out so that it can be fixed addressed.

**Comment by Sparrowbird611** [comment]
And it has been reworked, quite effectively, in the form of the HoS laser, a high powered weapon that can two shot criminals and replace the baton. Handing a two shot gun to regular officers is exceptionally idiotic balance, along with destroying any real usage of the baton except for niche scenarios.

The weapon is horribly balanced for standard issue gear. It should not exist past the HoS weapon. It does not add more options, it makes half the other options redundant, which is unacceptable. With it's existence, you may as well remove the baton and the disabler, as the taser is the superior option, and there is no way to balance it for standard issue usage without making the stun baton redundant or just being another disabler bolt.

**Comment by Maldaris** [comment]
> And it has been reworked, quite effectively, in the form of the HoS laser, a high powered weapon that can two shot criminals and replace the baton. Handing a two shot gun to regular officers is exceptionally idiotic balance, along with destroying any real usage of the baton except for niche scenarios.
> 
> The weapon is horribly balanced for standard issue gear. It should not exist past the HoS weapon. It does not add more options, it makes half the other options redundant, which is unacceptable. With it's existence, you may as well remove the baton and the disabler, as the taser is the superior option, and there is no way to balance it for standard issue usage without making the stun baton redundant or just being another disabler bolt.

Okay I tried being nice. Now I'll be blunt. 

FIX. TASER.

**Comment by Sparrowbird611** [comment]
Well then, as you wish, I'll make it into the sidegrade it was intended to be, though it pains me the HoS gun will be hit in the process.

**Comment by Maldaris** [comment]
> Well then, as you wish, I'll make it into the sidegrade it was intended to be, though it pains me the HoS gun will be hit in the process.

Spitballing here since I've not looked at gun code almost ever: You might be able to subclass the projectile, keep the current stats, and give the upgraded version to the HoS gun.

**Comment by Sparrowbird611** [comment]
I'm aware, it was sarcasm to be honest. I can most likely get what I want done, but the only thing it will do is be a redundant creation.

**Comment by Sparrowbird611** [comment]
I'll hit it in the third pass, which is coming soon.

**Comment by dee-dubya** [comment]
This is gonna take a bit to go over so let's start.



> X-ray laser AP buffed to 40.

this is fine, it's thematic and gives the x-ray laser a bit more of a reason to exist

> Xeno sentinel neuro spit stats changed. It no longer hardstuns, and instead deals 60 stamina damage, a 3 second knockdown, and 3 seconds of eyeblur.

also fine, stun based combat is cringe and the further we move away from it the better, also xenos are pretty OP as-is

> Removed the damage dropoff on makeshift shotgun shells (not that any one uses them any way.)

weird flex but okay
 
> Decreased stamina damage on the disabler and rubber revolver rounds to 20.

I'm torn on this, as far as the disabler part goes. The revolver rounds being nerfed is no bueno, since people already see rubbershot as useless as-is. The disabler nerf feels like it'd encourage more shotgun sec, when in reality we want them to always have the option and preference to non-lethal takedowns. This would bring the effective amount of consecutive disabler shots needed to down someone to 6-7, which is quite a lot to hit in a combat situation. It feels like enough to discourage their use entirely compared to just using a lethal alternative, which doesn't have the benefit of having its damage healed off quickly between bursts.

> Removed all instances of the hybrid taser, returning the disabler as the standard issue weapon.

Based, I didn't get to veto this one in time and I abhor ranged instant stuns. Make sure to remove the stun function from the HoS gun and Lieutenant's gun as well.
 
> Removed all instances of the commander, and gave no replacement.

care to explain the logic behind this one?

> Reworked the shotgun taser slug, it now inflicts 4 seconds of knockdown, 45 stamina damage, and only travels four tiles.

Nobody uses these as-is, and people will continue to not use them after this.

**Comment by Sparrowbird611** [comment]
Er, unless there was some wonky math going on, a disabler would be five shots with this change, since it requires 100 stamina damage to crit. I'm reverting both non lethal changes, however.

Mald is overruling me on the hybrid taser, so I'm going with plan B.

Security did not need a roundstart lethal weapon in their inventory. Why it was ever given to them is BYOND me. Mald is probably overruling me on this too.

**Comment by Maldaris** [comment]
> Er, unless there was some wonky math going on, a disabler would be five shots with this change, since it requires 100 stamina damage to crit. I'm reverting both non lethal changes, however.
> 
> Mald is overruling me on the hybrid taser, so I'm going with plan B.
> 
> Security did not need a roundstart lethal weapon in their inventory. Why it was ever given to them is BYOND me. Mald is probably overruling me on this too.

For the record I'm not overriding, I'm just stating opinion for the most part. The policy of "fix, don't just remove" is about the only authoritative thing I've said thus far. 

If you *actually* want to remove the hybrid taser, please make the changes in its own PR so that it's not sandbagged by other, reasonable changes.

**Comment by Maldaris** [comment]
> Reworked the shotgun taser slug, it now inflicts 4 seconds of knockdown, 45 stamina damage, and only travels four tiles.

As an idea, hybrid taser being reworked to operate similar/weaker compared to the shotgun taser slug could be a viable route.

**Comment by Sparrowbird611** [comment]
I stand by the opinion that it's unfixable still without being made useless. I can literally list all the tools that security officers have.

Disabler: long range stun bolt
Stun baton: close ranged but powerful melee stunner.
Flashbulb: AoE incapacitator
Pepperspray: Short ranged one shot disarmer
Bola: Anti stun immunity/deflection counter
Flashbang: Crowd control and anti deflection counter
Gripper gloves: Anti deflection counter

Then we have the taser, which somehow manages to fill the niche of stun bolt and powerful close quarters beam. The shotgun taser slug is straight up too strong for standard issue usage, since all that is required to stun a weakened foe is a shove and it disarms the foe.

I don't see a niche for the taser that could work easily, but I'm going with my own route for now.

**Comment by dee-dubya** [comment]
I have seen no major issues with the implementation and deployment of the commander. It's a fairly low damage ranged lethal option, and is the only thing an officer can rely on when dealing with stun-proof targets. On top of that, they only have easy access to a single magazine of it, so they have to pick their spots very carefully.

**Comment by Sparrowbird611** [comment]
Refer to the previous listing. Stun immune targets are meant to be countered via the bola, not a handgun all of security was given.

**Comment by triplezeta** [comment]
bolas dont even takedown and they dont work on simplemobs

**Comment by Sparrowbird611** [comment]
Bolas give you enough time to delay your foe, throw stuff, or regroup and acquire weapons from the armory. They take..... was it 10 seconds to remove, if I recall? And all it takes is a simple shove to reattach the bola. They're pretty much inescapable if you can prevent your target from standing still, which is an easy thing to do and lets you harmbaton or retreat with ease. I know because I've done it myself.

**Comment by triplezeta** [comment]
it takes 2 seconds to remove an energy bola, 3 seconds to remove a regular one. The freedom implant of traitors and biodegrade of the changeling will free you from bolas as well.

**Comment by Sparrowbird611** [comment]
I'm gonna look that up, cause that sounds slightly off....

**Comment by Sparrowbird611** [comment]
Regular ghetto bola is 3.5 seconds, energy is 6 seconds. That's a whole lot of time to keep some one from breaking out.

**Comment by dinnerwoerror** [comment]
pewpewpewpwepshewpjewmpewmpsewmshomshoomshoewpshewmpewpewpopewoeerrnmewmpewmenewkeewkwepkwew

guns are cool

**Comment by Sparrowbird611** [comment]
Swords are cooler, begone.

**Comment by dee-dubya** [comment]
This version is much better overall, but still one major gripe and one minor nitpick:

Rather than remove the commander and all associated code, simply move them from sec lockers into the armory roundstart. There's no real reason to just remove them from the code entirely. It'd be nice if when the warden wants to give out a lethal ballistic, his only option isn't SHOTGUN.

Rename the hybrid taser to the hybrid disabler. If the taser doesn't tase, why call it a taser? (also, remove the tase mode from the HOS and LT guns reeeeeeee)

Otherwise this all actually seems to be going in the right direction now.

**Comment by dinnerwoerror** [comment]
the controversial tag shouldnt exist since its a lie

**Comment by Sparrowbird611** [comment]
All commander code still exists, I just removed it from all spawning locations.

I could give a commander or two I suppose, but I'd have to figure out what weapon to replace it with. I think the armory is in a good place right now though, and the only real times you need to hand out ballistics are when shit is heavily fucked, so I don't see a need to fill it with commander pistols. If we really want to use it in some way, we could always give it to some off site roles or something.

HoS gun taser I can live with, idk why the LT has a taser tbh, and I'd be fine with removing that.

I can rename it hybrid disabler, but that's a tiny nitpick tbh.

**Comment by Sparrowbird611** [comment]
> the controversial tag shouldnt exist since its a lie

every PR I've ever made is controversial and has devolved into week long arguments, fake fact.

**Comment by Sparrowbird611** [comment]
Uh, looking at the LT's gun, he doesn't seem to have a taser bolt mode, only a disabler, lethal, and (surprisingly) a net gun mode.

I won't question why this is a thing, especially since I think it's a stupid bloat role, but whatever. At least it's an interesting gun.

**Comment by dinnerwoerror** [comment]
i would like to remind you that you can thank me for all of those things

**Comment by Sparrowbird611** [comment]
You're good windows, but you make me tear my hair out sometimes.

**Comment by dee-dubya** [comment]
I swear LT gun had a stun mode at one point. It was before we even re-added the hybrid taser too, so that one really churned my butter.

Maybe yeet some shotguns from the armory to make room for the stockpile of commanders? Personally I'd like to get rid of all the roundstart armory shotguns, but maybe leaving one or two in there would work.

**Comment by Sparrowbird611** [comment]
Not sure if I should do that in this PR tbh. There's three shotguns currently, so I could either do 2 shotguns and 2 commanders or 1 shotgun and 2 commanders, causing having just one commander by itself would be awkward imo.

Speaking of which, I probably ought to tone down the number of mags in the armory, cause there's a literal dozen of them.

**Comment by AsciiSquid** [comment]
Put commanders in the Sec-Vendor at least. If you really hate them just make them a contraband or expensive.

Whole point was commanders was sub-par lethal gun you don't tide the armory for.

**Comment by Sparrowbird611** [comment]
I've already provided a replacement for to the "sub-par" lethal gun. It is unnecessary to fill the vendor with them. At most, I will consider dee-dubya's suggestion.

**Comment by dee-dubya** [comment]
re: armory; trading them off at a rate of one shotgun per two commanders would probably be ideal.

That being said, the suggestion of putting them in the secvend at decent expense is actually an incredibly good one. Coming up with more ways to make the economy system actually matter is a good initiative.

**Comment by dinnerwoerror** [comment]
luh mayo isnt this the third attempt at a combat weaponry rebalance

**Comment by MarkSuckerberg** [comment]
🍿 🤏

**Comment by Sparrowbird611** [comment]
Impossible, everything I do is completely original and perfect.

Jokes aside, I wasn't at all aware of other weapon tweaking PRs.

**Comment by dinnerwoerror** [comment]
now, my personal opinion for what a combat weaponry rebalance should be is instead not to focus on offensive weapons, but mayhaps more defensive or passive measures and weapons instead, such as preset nonlethal grenades and having armor be worth a damn in particular

who even uses the tear gas grenades Paul, just give your troops extra ammo like a normal person
maybe make EMPs a bit less bullshit considering how the reason why they're 2 tc is no longer as big of a reason anymore
i was planning on making commander ammunition variants but i never got around to it (please no rubber bullets or nonlethal shit i beg of you)
on that note don't forget about armor, instead of just generic steel armor, bulletproof ceramic armor, or reflective glass armor, maybe an upgraded plasteel/titanium/plastitanium armor variant

i very much appreciate the action movie trope of "combat pragmatism", using uncommon, unique, or otherwise out of the box methods to achieve victory, surprise, or generally gain an advantage in a certain situation, but sadly if everyone took this approach to combat, key antagonists and other characters would probably be dead or defeated too soon and the round would be over a little too quickly

oh yea, and don't forget that the HoS and the warden and the craptain and all the heads are meant to get all of the cool and unique shit, not just the mid level seccie caste, there's a reason why the detective has his revolver with all the ammo variants and not the commander with its vanilla 9

https://tvtropes.org/pmwiki/pmwiki.php/Main/AuthorityEqualsAsskicking
https://tvtropes.org/pmwiki/pmwiki.php/Main/CombatPragmatist

**Comment by dinnerwoerror** [comment]
isn't that basically every addition to space station 13 ever

**Comment by triplezeta** [comment]
image
linter doesnt like your code

**Comment by DerFlammenwerfer** [comment]
> image
> linter doesnt like your code

All he has to do is add an empty line to the end of the file.

**Comment by MarkSuckerberg** [comment]
Failed the vote on the [discord](https://discord.com/invite/BUM8uRc). A few of the changes added may pass if put into a separate PR, so if you want to try again, be my guest.

**Comment by dinnerwoerror** [comment]
nah it wasn't that bad

**Comment by dee-dubya** [comment]
if this was tg this would have been merged two days ago

**Comment by dinnerwoerror** [comment]
you know, that actually reminds me of something

hey @CRITAWAKETS

**Pull request closed without merging**
