### PR TITLE
Potential shotgun nerf #3

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

Nerfs buckshot, slugs, rubbershot, beanbag, and improvised rounds for the shotgun
Buckshot and rubbershot now deal a total of 60 damage, with 10% damage reduction per tile. In testing, shotguns could down in two shots in the first two tiles, three shots at three, and four at four tiles. They also have a significant reduction to armor penetration, at -20, to make them less effective at spamming against nukies or sec officers.

Slugs deal 45 damage with no dropoff. Beanbag rounds deal 45 stamina damage and 5 brute damage, for the purpose of allowing bartenders to down with one magazine. Rubber slugs have -10 armor pen, regular slugs have 0.

Now also nerfs laser shot to 42 damage.

## Why It's Good For The Game

Makes shotguns less powerful without making them worthless. With this change using buckshot just for the can't miss potential is significantly less effective due to heavy damage dropoff, while leaving it powerful at close ranges. Also makes the point blank autoshotty spraydown less effective against armored targets.

## Changelog
:cl:
balance: Nerfs shotguns
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
what's with the slugs having negative AP too?

**Comment by Superyodeler** [comment]
They still dealt a pretty good amount of damage, and I kinda wanted to weaken shotguns in general against armor. I can remove it if people want me to.

**Comment by Sparrowbird611** [comment]
I would say this doesn't fix any of the issues with shotguns tbh, and adds more issues. They're still curbstomping both unarmored assassination targets and most traitors, and now they suck against cultists and nukies, people who can actually justify bigger guns.

**Comment by Superyodeler** [comment]
Apparently there is not a market for hollow point shotgun shells, so lethal slugs have been reverted to 0 AP.

**Comment by Superyodeler** [comment]
Just waiting for someone to approve at this point

**Review by MarkSuckerberg — APPROVED** [review]
Code is sound

**Pull request merged**
