### PR TITLE
0w0 semi wandomized wooms UwU *nuzzle wuzzle*

### PR DESCRIPTION
**Pull request by Debonaircorsiar**
Something I made for another server that I ported to this. 

I problably fucked up porting ngl.

lets you load room templates

### CODE REVIEW

**Comment by Debonaircorsiar** [comment]
fuck I forgot to remove my test maps from the thingy. I'll fix it when I get home.

**Comment by Maldaris** [comment]
>Uwu in the PR name
I want to close this on principle.

**Comment by Maldaris** [comment]
Memes aside please rename this PR to something descriptive of what you're adding.

**Comment by Debonaircorsiar** [comment]
Is that a better title.

**Comment by Maldaris** [comment]
Thanks I hate it.

**Comment by dinnerwoerror** [comment]
do i even know you

**Comment by MarkSuckerberg** [comment]
Still doesn't beat PR #242 somehow

**Comment by Debonaircorsiar** [comment]
I'm taking this down because I'm a retard and forgot to remove the bits for the test maps for the old server I used for this

**Comment by dinnerwoerror** [comment]
damn that was quick

**Comment by TheNeoGamer42** [comment]
moment

**Comment by Maldaris** [comment]
Screen Shot 2020-06-01 at 5 19 29 PM
I mean...

**Comment by Maldaris** [comment]
> Still doesn't beat PR #242 somehow

I dunno man, I still had more detail in the description than this entire PR.

**Pull request closed without merging**
