### PR TITLE
gives the CMO advanced hypospray kit the upgraded trek chems

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

replaces the original set of bicaridine, kelotane, anti toxin, and dexalin for its upgraded variants of bicaridine plus, dermaline, carthatoline, and dexalin plus

## Why It's Good For The Game

it's astounding how fast you piss through the basic trek chems, it's unbecoming of a CMO how fast

20 units from bicaridine, kelotane, antitoxin, and dexalin heal only 32 damage of their respective calibers, as opposed to the 128 damage that is healed from 20 units of the upgraded chemicals

## Changelog
:cl:
balance: the CMO hypospray kit comes with the upgraded chemicals instead of the basic ones, as is befitting of their status
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
based

**Comment by triplezeta** [comment]
oh while you're here can you rename the regular-sized hypovial filled with dylovene so that it says its filled with dylovene
image

**Comment by dinnerwoerror** [comment]
but it's not filled with dylovene

**Comment by dinnerwoerror** [comment]
oh wait

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
