### PR TITLE
The Centcom Galactic Ban DB (Global Ban Database)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

Ports BeeStation/BeeStation-Hornet#2207 and tgstation/tgstation#52519

From the original PR:
> See: https://centcom.melonmesa.com/swagger/index.html
>
> Supported servers:
>
>   * BeeStation
>   * /vg/station
>   * FTL13
>
> Planned support that bobbah is working on:
>
>  *  Yogstation
>  *  Oraclestation
>  *  World Server

## Why It's Good For The Game
It makes it a lot easier to see if people are repeat griefers, or just to get a general picture of their history. Basically, it's just an easier way to check other server's ban lists.

From the original PR:
> It makes the Feweh Global Ban Database a reality.

## Changelog
:cl: ike709 and bobbahbrown
add: Admins can now see your bans on (some) other servers.
/:cl:

### CODE REVIEW

**Comment by AsciiSquid** [comment]
Gonna just make a note here as headmin that the Global DB will only be used as a reference point for egregious repeat offenders. We're still about being impartial and no bans will be given out through this global list alone.

Any questions or discussion on how this would affect our ruling and administration should be held on our discord or on the forums, only codestuffs here kthanks.

**Comment by MarkSuckerberg** [comment]
Awaiting an update from Ike and Bobbah that shows server's RP levels on ban list entries. DNM until then.

**Comment by SynnGraffkin** [comment]
Ike opened a new PR on TG, you may need to update this. 

https://github.com/tgstation/tgstation/pull/52588

**Comment by MarkSuckerberg** [comment]
Nope, handled that in 937091a

**Pull request merged**
